'use strict';
(()=>{
 const G=window.CasualGame,U=window.CasualCore,$=id=>document.getElementById(id),KEY='casual-'+G.id+'-v1',BEST=KEY+'-best';
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}};
 let saved=read(KEY,null),state=null,history=[],mode=G.modes[0].id,playing=false,paused=false,active=true,view={},lastTick=performance.now(),lastAction=performance.now(),best=read(BEST,{});
 if(!best||typeof best!=='object'||Array.isArray(best))best={};
 try{if(saved?.state&&G.validate(saved.state)){state=saved.state;for(const k of ['score','moves','seconds','aids'])if(!Number.isFinite(state[k])||state[k]<0)state[k]=0;history=Array.isArray(saved.history)?saved.history.filter(G.validate).slice(-80):[];mode=state.mode;}}catch{state=null;}
 const time=n=>{n=Math.floor(n);return (n>=3600?Math.floor(n/3600)+':':'')+String(Math.floor(n/60)%(n>=3600?60:100000)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');};
 function save(){if(state&&!write(KEY,{state,history}))$('save-status').textContent='Сохранение недоступно. Не закрывайте страницу до конца партии.';}
 function message(s){$('message').textContent=s;}
 function lobby(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('continue').hidden=!state||state.won||state.lost;$('continue').textContent=state?'Продолжить · '+time(state.seconds):'Продолжить';const value=best[mode];$('record').textContent=Number.isFinite(value)?G.record==='time'?time(value):Math.floor(value).toLocaleString('ru-RU'):'—';}
 function close(){$('dialog').close();lastTick=performance.now();lastAction=performance.now();}
 function modal(title){$('dialog-body').replaceChildren();const h=document.createElement('h2');h.id='dialog-title';h.textContent=title;$('dialog-body').append(h);if(!$('dialog').open)$('dialog').showModal();return $('dialog-body');}
 function text(body,value){const p=document.createElement('p');p.textContent=value;body.append(p);}
 function button(body,label,fn,style='primary'){const b=document.createElement('button');b.className=style;b.textContent=label;b.onclick=fn;body.append(b);return b;}
 function canPlay(){return playing&&!paused&&active&&!document.hidden&&!$('dialog').open&&!state.won&&!state.lost;}
 function render(){if(!state)return;$('playfield').replaceChildren();$('game-tools').replaceChildren();$('metric-label').textContent='СЧЁТ';$('metric').textContent=state.score;$('timer').textContent=time(state.seconds);$('difficulty').textContent=G.modes.find(m=>m.id===state.mode)?.label||'';$('undo').hidden=!G.undo;$('undo').disabled=!history.length||state.won||state.lost;
  const api={board:$('playfield'),view,send,message,redraw:render,modal,text,button,close,cell:(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;return b;},tool:(label,fn,on=false)=>{const b=document.createElement('button');b.textContent=label;b.classList.toggle('active',on);b.onclick=()=>{if(canPlay())fn();};$('game-tools').append(b);return b;},status:(label,value)=>{$('metric-label').textContent=label;$('metric').textContent=value;},aid:()=>{state.aids++;save();}};G.draw(state,api);$('window').classList.toggle('won',state.won);
 }
 function end(){const won=state.won,record=G.record==='time'?Math.floor(state.seconds):state.score,old=best[state.mode];if((won||G.record==='score')&&!state.aids&&(!Number.isFinite(old)||(G.record==='time'?record<old:record>old))){best[state.mode]=record;write(BEST,best);}const body=modal(won?'Отличная партия!':G.lossTitle||'Партия завершена');const icon=document.createElement('div');icon.className='result-art';icon.textContent=won?'✦':'◈';body.append(icon);text(body,`${G.title} · ${time(state.seconds)} · ${state.moves} ходов${G.record==='score'?' · '+state.score+' очков':''}.`);if(!won&&G.lossText)text(body,G.lossText);button(body,'Сыграть ещё',()=>{close();start(true);});button(body,'К выбору режима',()=>{close();back();},'secondary');}
 function send(action){if(!canPlay())return false;const before=G.undo?U.clone(state):null;if(!G.act(state,action))return false;if(before){history.push(before);if(history.length>80)history.shift();}state.moves++;save();render();window.Телеграм?.отклик?.('карта');if(state.won||state.lost)end();return true;}
 function screens(on){playing=on;for(const [id,v]of [['экран-лобби',!on],['экран-игры',on]]){$(id).hidden=!v;$(id).classList.toggle('экран--виден',v);}window.scrollTo(0,0);lastTick=lastAction=performance.now();}
 function pause(value){paused=value;$('resume').hidden=!paused||!playing;$('playfield').inert=paused;$('playfield').setAttribute('aria-hidden',String(paused));$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Продолжить':'Пауза');lastTick=lastAction=performance.now();}
 function start(fresh=false){if(fresh||!state||state.won||state.lost){state=G.create(mode,crypto.getRandomValues(new Uint32Array(1))[0]);history=[];}mode=state.mode;view={};screens(true);pause(false);render();save();message(G.startMessage||'Выберите действие. Правила — под знаком «?».');}
 function back(){if($('dialog').open){close();return;}if(playing){save();screens(false);lobby();}else location.href='index.html';}
 function launch(){if(state&&!state.won&&!state.lost){const body=modal('Начать новую партию?');text(body,'Текущая партия будет заменена. Личные рекорды сохранятся.');button(body,'Начать новую',()=>{close();start(true);});button(body,'Продолжить текущую',()=>{close();start();},'secondary');}else start(true);}
 $('play').onclick=launch;$('continue').onclick=()=>start();$('back').onclick=e=>{e.preventDefault();back();};$('collection').onclick=back;$('new').onclick=launch;$('pause').onclick=()=>pause(!paused);$('resume').onclick=()=>pause(false);$('close-dialog').onclick=close;
 $('undo').onclick=()=>{if(canPlay()&&history.length){const seconds=state.seconds,aids=state.aids;state=history.pop();state.seconds=seconds;state.aids=Math.max(state.aids,aids);view={};save();render();message('Последний ход отменён');}};
 $('help').onclick=()=>{const body=modal('Как играть: '+G.title);G.help.forEach(p=>text(body,p));text(body,'Партия и рекорды сохраняются на этом устройстве. Время на паузе и в свёрнутом приложении не считается.');button(body,'Понятно',close);};
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;lobby();});
 document.addEventListener('keydown',e=>{if(!canPlay())return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();return;}if(G.key&&!e.ctrlKey&&!e.metaKey&&!e.altKey){const action=G.key(state,e.key);if(action){e.preventDefault();send(action);}}});
 setInterval(()=>{const now=performance.now(),delta=(now-lastTick)/1000;lastTick=now;if(!canPlay())return;if(delta<2)state.seconds+=delta;$('timer').textContent=time(state.seconds);if(G.interval&&now-lastAction>=G.interval(state)){lastAction=now;send({type:'tick'});}else if(Math.floor(state.seconds)%3===0)save();},100);
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){pause(true);save();}});window.addEventListener('pagehide',save);
 let bound=null;function telegram(){window.Телеграм?.показатьСтрелку(back);window.Телеграм?.цветОкна('#0c1919');const tg=window.Telegram?.WebApp;if(tg&&bound!==tg){bound=tg;tg.onEvent?.('deactivated',()=>{active=false;if(playing)pause(true);save();});tg.onEvent?.('activated',()=>{active=true;lastTick=lastAction=performance.now();});}}telegram();window.addEventListener('load',telegram);lobby();
})();
