'use strict';
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./casual-core'));else r.CasualGame=f(r.CasualCore);})(globalThis,U=>{
 const modes=[{id:'3',label:'Разминка',detail:'3 × 3 · 8 фишек',size:3,steps:70},{id:'4',label:'Классика',detail:'4 × 4 · 15 фишек',size:4,steps:180},{id:'5',label:'Мастер',detail:'5 × 5 · 24 фишки',size:5,steps:350}];
 function neighbors(s){const z=s.tiles.indexOf(0);return [z-1,z+1,z-s.size,z+s.size].filter(i=>i>=0&&i<s.tiles.length&&Math.abs(i%s.size-z%s.size)+Math.abs(Math.floor(i/s.size)-Math.floor(z/s.size))===1);}
 const solved=s=>s.tiles.every((v,i)=>v===(i+1)%s.tiles.length);
 function create(mode,seed){const m=modes.find(m=>m.id===mode)||modes[1],s={...U.base(m.id,seed),size:m.size,tiles:Array.from({length:m.size*m.size},(_,i)=>(i+1)%(m.size*m.size)),witness:[]},rng=U.random(seed);let previous=-1;for(let n=0;n<m.steps||solved(s);n++){const empty=s.tiles.indexOf(0),options=neighbors(s).filter(i=>i!==previous),i=options[Math.floor(rng()*options.length)];[s.tiles[i],s.tiles[empty]]=[s.tiles[empty],s.tiles[i]];s.witness.push(empty);previous=empty;}return s;}
 function act(s,a){if(s.won||s.lost||a.type!=='slide'||!neighbors(s).includes(a.i))return false;const empty=s.tiles.indexOf(0);[s.tiles[a.i],s.tiles[empty]]=[s.tiles[empty],s.tiles[a.i]];s.won=solved(s);s.score=s.tiles.filter((v,i)=>v&&v===i+1).length;return true;}
 function reachable(s){const t=s.tiles.filter(Boolean);let inv=0;for(let i=0;i<t.length;i++)for(let j=i+1;j<t.length;j++)if(t[i]>t[j])inv++;return s.size%2?inv%2===0:(inv+s.size-Math.floor(s.tiles.indexOf(0)/s.size))%2===1;}
 function validate(s){const m=modes.find(m=>m.id===s?.mode);return !!m&&s.size===m.size&&U.ints(s.tiles,m.size*m.size,0,m.size*m.size-1)&&new Set(s.tiles).size===s.tiles.length&&reachable(s);}
 function key(s,k){const delta={ArrowLeft:1,ArrowRight:-1,ArrowUp:s.size,ArrowDown:-s.size}[k];return delta==null?null:{type:'slide',i:s.tiles.indexOf(0)+delta};}
 function draw(s,api){api.board.className='game-board fifteen-board';api.status('ХОДОВ',s.moves);const grid=document.createElement('div');grid.className='sliding-grid';grid.style.setProperty('--slide-size',s.size);const previous=api.view.tiles;api.view.tiles=s.tiles.slice();for(let i=0;i<s.tiles.length;i++){const v=s.tiles[i];if(!v)continue;const b=api.cell(String(v),()=>{if(!api.send({type:'slide',i}))api.message('Сдвиньте фишку, которая соседствует с пустой клеткой.');});b.className='slide-tile'+(v===i+1?' correct':'')+(neighbors(s).includes(i)?' movable':'');b.style.left=`calc(${i%s.size*100/s.size}% + 4px)`;b.style.top=`calc(${Math.floor(i/s.size)*100/s.size}% + 4px)`;b.dataset.cell=i;b.setAttribute('aria-label','Сдвинуть '+v);grid.append(b);if(previous&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const j=previous.indexOf(v);if(j!==i){const x=(j%s.size-i%s.size)*(100+8*s.size/Math.max(1,api.board.clientWidth)),y=(Math.floor(j/s.size)-Math.floor(i/s.size))*(100+8*s.size/Math.max(1,api.board.clientWidth));b.animate([{transform:`translate(${x}%,${y}%)`},{transform:'translate(0,0)'}],{duration:150,easing:'ease-out'});}}}api.board.append(grid);const note=document.createElement('div');note.className='slide-caption';note.textContent=`На месте: ${s.tiles.filter((v,i)=>v&&v===i+1).length} из ${s.tiles.length-1}`;api.board.append(note);api.tool('Образец',()=>{const body=api.modal('Соберите по порядку');for(let y=0;y<s.size;y++)api.text(body,Array.from({length:s.size},(_,x)=>y*s.size+x+1===s.tiles.length?'□':String(y*s.size+x+1)).join('   '));api.text(body,'Числа по возрастанию слева направо. Пустая клетка — справа внизу.');api.button(body,'Понятно',api.close);});}
 return {id:'fifteen',key:'пятнашки',title:'Пятнашки',tag:'У КАЖДОГО ЧИСЛА ЕСТЬ СВОЁ МЕСТО',subtitle:'Один свободный шаг.\nТысячи путей к порядку.',modes,create,act,validate,draw,neighbors,solved,reachable,handleKey:key,undo:true,record:'time',startMessage:'Соберите числа по порядку. Пустая клетка должна оказаться справа внизу.',help:['Расположите фишки по возрастанию слева направо, строка за строкой. Пустое место должно остаться в правом нижнем углу.','Нажмите соседнюю с пустым местом фишку, чтобы сдвинуть её. Двигаться можно только по горизонтали и вертикали, за один ход — одна фишка.','На компьютере работают стрелки: они задают направление движения фишки в пустую клетку. Кнопка «Образец» показывает цель.','Все начальные позиции получены допустимыми ходами из собранного поля, поэтому у каждой есть решение. Можно отменять свои ходы. Личный рекорд — время победы для выбранного размера.']};
});
