'use strict';
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./casual-core'));else r.CasualGame=f(r.CasualCore);})(globalThis,U=>{
 const modes=[{id:'garden',label:'Сад',detail:'56 фишек · знакомство',layers:[[6,6],[4,4],[2,2]]},{id:'tower',label:'Башня',detail:'80 фишек · три яруса',layers:[[8,6],[6,4],[4,2]]},{id:'palace',label:'Дворец',detail:'144 фишки · большой стол',layers:[[10,8],[8,6],[4,4]]}];
 function free(s,i){const t=s.tiles[i];if(!t||t.gone)return false;const live=s.tiles.filter(t=>!t.gone);return !live.some(q=>q.z>t.z&&q.x===t.x&&q.y===t.y)&&(!live.some(q=>q.z===t.z&&q.y===t.y&&q.x===t.x-1)||!live.some(q=>q.z===t.z&&q.y===t.y&&q.x===t.x+1));}
 function pairs(s){const ids=s.tiles.map((_,i)=>i).filter(i=>free(s,i)),out=[];for(let a=0;a<ids.length;a++)for(let b=a+1;b<ids.length;b++)if(s.tiles[ids[a]].kind===s.tiles[ids[b]].kind)out.push([ids[a],ids[b]]);return out;}
 function create(mode,seed){const m=modes.find(m=>m.id===mode)||modes[0],s={...U.base(m.id,seed),cols:m.layers[0][0],rows:m.layers[0][1],tiles:[]},rng=U.random(seed),types=U.shuffle(Array.from({length:m.layers.reduce((n,[w,h])=>n+w*h,0)/2},(_,i)=>i%34),rng);m.layers.forEach(([w,h],z)=>{for(let y=0;y<h;y++)for(let x=0;x<w;x++)s.tiles.push({x:x+(s.cols-w)/2,y:y+(s.rows-h)/2,z,kind:0,gone:false});});
  // Remove random geometrically free pairs, then assign faces backwards along that legal witness.
  for(let attempt=0;attempt<100;attempt++){s.tiles.forEach(t=>t.gone=false);s.witness=[];while(s.tiles.some(t=>!t.gone)){const ids=U.shuffle(s.tiles.map((_,i)=>i).filter(i=>free(s,i)),rng);if(ids.length<2)break;s.witness.push(ids.slice(0,2));s.tiles[ids[0]].gone=s.tiles[ids[1]].gone=true;}if(s.witness.length===types.length)break;}
  if(s.witness.length!==types.length){s.witness=[];for(let z=2;z>=0;z--)for(let y=0;y<s.rows;y++){const row=s.tiles.map((t,i)=>({t,i})).filter(v=>v.t.z===z&&v.t.y===y);while(row.length)s.witness.push([row.shift().i,row.pop().i]);}}
  s.witness.forEach(([a,b],i)=>s.tiles[a].kind=s.tiles[b].kind=types[i]);s.tiles.forEach(t=>t.gone=false);return s;
 }
 function act(s,a){if(s.won||s.lost||a.type!=='pair'||a.a===a.b||!free(s,a.a)||!free(s,a.b)||s.tiles[a.a].kind!==s.tiles[a.b].kind)return false;s.tiles[a.a].gone=s.tiles[a.b].gone=true;s.score+=20;s.won=s.tiles.every(t=>t.gone);return true;}
 function validate(s){const m=modes.find(m=>m.id===s?.mode);if(!m||!Array.isArray(s.tiles))return false;const base={cols:m.layers[0][0],rows:m.layers[0][1],tiles:[]};m.layers.forEach(([w,h],z)=>{for(let y=0;y<h;y++)for(let x=0;x<w;x++)base.tiles.push({x:x+(base.cols-w)/2,y:y+(base.rows-h)/2,z});});return s.cols===base.cols&&s.rows===base.rows&&s.tiles.length===base.tiles.length&&s.tiles.every((t,i)=>t.x===base.tiles[i].x&&t.y===base.tiles[i].y&&t.z===base.tiles[i].z&&Number.isInteger(t.kind)&&t.kind>=0&&t.kind<34&&typeof t.gone==='boolean')&&s.tiles.filter(t=>!t.gone).length%2===0;}
 function face(kind){if(kind<9)return {text:String(kind+1)+'\n筒',name:(kind+1)+' кругов',suit:'circles'};if(kind<18)return {text:String(kind-8)+'\n竹',name:(kind-8)+' бамбуков',suit:'bamboo'};if(kind<27)return {text:['一','二','三','四','五','六','七','八','九'][kind-18]+'\n萬',name:(kind-17)+' знаков',suit:'characters'};return {text:['東','南','西','北','中','發','白'][kind-27],name:['Восток','Юг','Запад','Север','Красный дракон','Зелёный дракон','Белый дракон'][kind-27],suit:kind===31?'characters':'bamboo'};}
 function draw(s,api){const board=api.board;board.className='game-board mahjong-board';board.style.setProperty('--mah-cols',s.cols+.5);board.style.aspectRatio=(s.cols+.5)/(s.rows*1.35+.6);api.status('ОСТАЛОСЬ',s.tiles.filter(t=>!t.gone).length);const available=pairs(s);s.tiles.forEach((t,i)=>{if(t.gone)return;const f=face(t.kind),open=free(s,i),b=api.cell(f.text,()=>{if(!open){api.message('Фишку закрывает верхний ярус или соседи с двух сторон.');return;}const sel=api.view.selected;if(sel===i){api.view.selected=null;api.redraw();return;}if(sel!=null&&s.tiles[sel]?.kind===t.kind){api.view.selected=null;api.send({type:'pair',a:sel,b:i});return;}api.view.selected=i;api.message(f.name+': найдите такую же свободную фишку');api.redraw();});b.className='mah-tile '+f.suit+(open?' free':' blocked')+(api.view.selected===i?' selected-item':'')+(api.view.hint?.includes(i)?' hint-cell':'');b.style.left=`calc(${t.x*100/(s.cols+.5)}% + ${5-t.z*2}px)`;b.style.top=`calc(${t.y*1.35*100/(s.rows*1.35+.6)}% + ${8-t.z*3}px)`;b.style.zIndex=t.z*100+t.y;if(t.kind<18){b.textContent='';const marks=document.createElement('span');marks.className='mah-marks';for(let n=0;n<t.kind%9+1;n++){const mark=document.createElement('i');mark.textContent=t.kind<9?'◉':'┃';marks.append(mark);}b.append(marks);}if(window.CasualArt)b.innerHTML=CasualArt.mahjong(t.kind);b.dataset.tile=i;b.setAttribute('aria-label',f.name+(open?', свободна':', заблокирована'));b.setAttribute('aria-pressed',String(api.view.selected===i));board.append(b);});
  api.tool('✦ Подсказка',()=>{if(!available.length){api.message('Свободных пар нет. Отмените предыдущие ходы или начните новую раскладку.');return;}api.aid();api.view.hint=available[0];api.redraw();});if(!available.length&&!s.won)api.message('Нет свободных пар. Можно отменить ход и выбрать другой путь.');
 }
 return {id:'mahjong',key:'маджонг',title:'Маджонг',tag:'УБИРАЙТЕ ЛИШНЕЕ. НАХОДИТЕ ГАРМОНИЮ.',subtitle:'Пара за парой.\nТишина большого города.',modes,create,act,validate,draw,free,pairs,face,undo:true,record:'time',startMessage:'Уберите две одинаковые свободные фишки.',help:['Это маджонг-пасьянс для одного игрока: уберите все фишки одинаковыми парами. Это не многопользовательский риичи-маджонг.','Фишка свободна, если сверху ничего нет и хотя бы одна длинная сторона — слева или справа — открыта. Светлые фишки доступны, затемнённые пока заблокированы.','Нажмите первую свободную фишку, затем такую же вторую. Число и масть должны совпадать. В этой версии нет особых сезонных пар: все пары строго одинаковые.','Каждая начальная раскладка имеет решение. Неудачный выбор может оставить вас без ходов — используйте отмену. Подсказки исключают партию из личного рекорда.']};
});
