'use strict';
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./casual-core'));else r.CasualGame=f(r.CasualCore);})(globalThis,U=>{
 const modes=[{id:'calm',label:'Спокойно',detail:'Мягкий темп · со стенами',speed:250},{id:'classic',label:'Классика',detail:'Быстрее с каждым яблоком',speed:180},{id:'wrap',label:'Без границ',detail:'Проход сквозь край поля',speed:210}];
 const dirs=[[1,0],[0,1],[-1,0],[0,-1]];
 function food(s){const free=Array.from({length:256},(_,i)=>i).filter(i=>!s.body.includes(i));if(!free.length){s.food=-1;s.won=true;s.running=false;return;}s.food=free[Math.floor(U.random((s.seed+s.eaten*2654435761)>>>0)()*free.length)];}
 function create(mode,seed){const s={...U.base(modes.some(m=>m.id===mode)?mode:'calm',seed),size:16,body:[136,135,134,133],dir:0,queued:null,food:0,eaten:0,running:false,reason:''};food(s);return s;}
 function act(s,a){if(s.won||s.lost)return false;if(a.type==='start'&&!s.running){s.running=true;return true;}if(a.type==='turn'){if(!Number.isInteger(a.dir)||a.dir<0||a.dir>3||a.dir===(s.dir+2)%4||s.queued!=null||s.running&&a.dir===s.dir)return false;s.queued=a.dir;s.running=true;return true;}if(a.type!=='tick'||!s.running)return false;if(s.queued!=null){s.dir=s.queued;s.queued=null;}const [dx,dy]=dirs[s.dir],head=s.body[0];let x=head%16+dx,y=Math.floor(head/16)+dy;if(s.mode==='wrap'){x=(x+16)%16;y=(y+16)%16;}if(x<0||y<0||x>=16||y>=16){s.lost=true;s.running=false;s.reason='Змейка коснулась стены.';return true;}const i=y*16+x,eating=i===s.food,body=eating?s.body:s.body.slice(0,-1);if(body.includes(i)){s.lost=true;s.running=false;s.reason='Змейка столкнулась с собой.';return true;}s.body.unshift(i);if(eating){s.eaten++;s.score+=100;food(s);}else s.body.pop();return true;}
 function validate(s){return !!s&&modes.some(m=>m.id===s.mode)&&s.size===16&&Array.isArray(s.body)&&s.body.length>=4&&s.body.length<=256&&s.body.every(i=>Number.isInteger(i)&&i>=0&&i<256)&&new Set(s.body).size===s.body.length&&Number.isInteger(s.dir)&&s.dir>=0&&s.dir<4&&(s.queued===null||Number.isInteger(s.queued)&&s.queued>=0&&s.queued<4)&&Number.isInteger(s.eaten)&&s.eaten===s.body.length-4&&(s.food===-1&&s.body.length===256||Number.isInteger(s.food)&&s.food>=0&&s.food<256&&!s.body.includes(s.food));}
 function interval(s){return s.running?Math.max(s.mode==='calm'?150:85,modes.find(m=>m.id===s.mode).speed-s.eaten*3):Infinity;}
 function handleKey(s,k){const dir={ArrowRight:0,ArrowDown:1,ArrowLeft:2,ArrowUp:3,d:0,s:1,a:2,w:3,D:0,S:1,A:2,W:3}[k];return dir==null?null:{type:'turn',dir};}
 function draw(s,api){api.board.className='game-board snake-board';const grid=document.createElement('div');grid.className='snake-grid';grid.setAttribute('aria-label',`Змейка длиной ${s.body.length}. Яблок собрано: ${s.eaten}.`);const body=new Set(s.body);for(let i=0;i<256;i++){const c=document.createElement('span');c.className='snake-cell'+(body.has(i)?' snake-body':'')+(s.body[0]===i?' snake-head':'')+(i===s.food?' snake-food':'');if(i===s.body[0])c.style.transform=`rotate(${s.dir*90}deg)`;grid.append(c);}if(window.CasualArt)grid.innerHTML=CasualArt.snake(s);api.board.append(grid);const note=document.createElement('div');note.className='snake-caption';note.textContent=s.lost?s.reason:!s.running?'Нажмите направление, чтобы начать':`Яблок: ${s.eaten} · ${s.mode==='wrap'?'Края соединены':'Не касайтесь стен'}`;api.board.append(note);
  api.board.onpointerdown=e=>{if(e.button===0){api.view.swipeStart=[e.clientX,e.clientY];api.board.setPointerCapture(e.pointerId);}};api.board.onpointerup=e=>{const start=api.view.swipeStart;if(!start)return;const x=e.clientX-start[0],y=e.clientY-start[1];api.view.swipeStart=null;if(Math.max(Math.abs(x),Math.abs(y))<12)return;api.send({type:'turn',dir:Math.abs(x)>Math.abs(y)?x>0?0:2:y>0?1:3});};api.board.onpointercancel=()=>api.view.swipeStart=null;
  for(const [label,dir,name]of [['↑',3,'Вверх'],['←',2,'Влево'],['↓',1,'Вниз'],['→',0,'Вправо']]){const b=api.tool(label,()=>api.send({type:'turn',dir}));b.onpointerdown=e=>{e.preventDefault();api.send({type:'turn',dir});};b.onclick=e=>{if(e.detail===0)api.send({type:'turn',dir});};b.dataset.dir=dir;b.setAttribute('aria-label',name);}if(!s.running&&!s.lost&&!s.won)api.message('Стрелки, свайпы или клавиши WASD. Движение начнётся после выбора направления.');
 }
 return {id:'snake',key:'змейка',title:'Змейка',tag:'ПОЙМАЙТЕ РИТМ. СОХРАНИТЕ КУРС.',subtitle:'Ещё один поворот.\nЕщё один личный рекорд.',modes,create,act,validate,draw,interval,handleKey,resume:s=>{s.running=false;s.queued=null;},undo:false,record:'score',lossText:'Неудачный поворот — повод попробовать ещё раз. Личный рекорд уже сохранён на устройстве.',startMessage:'Нажмите направление: стрелки, свайпы или клавиши WASD.',help:['Собирайте золотые яблоки — каждое даёт 100 очков и увеличивает змейку на одну клетку. Не столкнитесь с собственным телом.','На телефоне используйте стрелки под полем или свайпы по полю. На компьютере — стрелки или WASD. Развернуться сразу назад нельзя; между двумя шагами принимается один поворот.','В режимах «Спокойно» и «Классика» касание стены завершает партию. В режиме «Без границ» змейка выходит с противоположного края. Скорость постепенно растёт при сборе яблок.','При возвращении к сохранённой партии змейка ждёт вашего направления. Сворачивание приложения ставит игру на паузу. Заполнить всё поле — победа.']};
});
