'use strict';
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./casual-core'));else r.CasualGame=f(r.CasualCore);})(globalThis,U=>{
 const modes=[{id:'classic',label:'Классика',detail:'Без поворота фигур'},{id:'relax',label:'Свобода',detail:'Фигуры можно вращать'}];
 const shapes=[[[0,0]],[[0,0],[1,0]],[[0,0],[1,0],[2,0]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[1,0],[1,1]],[[0,0],[0,1],[0,2],[1,2]],[[0,0],[1,0],[2,0],[1,1]],[[0,0],[1,0],[1,1],[2,1]],[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1]],[[0,0],[1,0],[2,0],[3,0],[4,0]],[[0,0],[1,0],[0,1]],[[0,0],[1,0],[2,0],[2,1],[2,2]]];
 function cells(p){let v=shapes[p.shape].map(c=>c.slice());for(let n=0;n<p.rot;n++)v=v.map(([x,y])=>[-y,x]);const minx=Math.min(...v.map(c=>c[0])),miny=Math.min(...v.map(c=>c[1]));return v.map(([x,y])=>[x-minx,y-miny]);}
 function fits(s,p,i){return Number.isInteger(i)&&i>=0&&i<64&&cells(p).every(([x,y])=>i%8+x<8&&Math.floor(i/8)+y<8&&!s.grid[i+y*8+x]);}
 function possible(s){return s.pieces.some(p=>p&&Array.from({length:s.mode==='relax'?4:1},(_,r)=>({...p,rot:(p.rot+r)%4})).some(q=>s.grid.some((_,i)=>fits(s,q,i))));}
 function refill(s){const rng=U.random((s.seed+s.round*2654435761)>>>0);s.pieces=Array.from({length:3},()=>({shape:Math.floor(rng()*shapes.length),rot:Math.floor(rng()*4),color:1+Math.floor(rng()*5)}));s.round++;}
 function create(mode,seed){const s={...U.base(mode==='relax'?'relax':'classic',seed),grid:Array(64).fill(0),pieces:[],round:0,combo:0,lines:0,lastClear:[]};refill(s);return s;}
 function act(s,a){if(s.lost||s.won)return false;const p=s.pieces[a.piece];if(!p)return false;if(a.type==='rotate'&&s.mode==='relax'){p.rot=(p.rot+1)%4;return true;}if(a.type!=='place'||!fits(s,p,a.i))return false;const size=cells(p).length;cells(p).forEach(([x,y])=>s.grid[a.i+y*8+x]=p.color);s.pieces[a.piece]=null;const rows=[],cols=[];for(let k=0;k<8;k++){if(s.grid.slice(k*8,k*8+8).every(Boolean))rows.push(k);if(Array.from({length:8},(_,r)=>s.grid[r*8+k]).every(Boolean))cols.push(k);}const cleared=new Set([...rows.flatMap(r=>Array.from({length:8},(_,c)=>r*8+c)),...cols.flatMap(c=>Array.from({length:8},(_,r)=>r*8+c))]);s.lastClear=[...cleared];cleared.forEach(i=>s.grid[i]=0);const n=rows.length+cols.length;s.combo=n?s.combo+1:0;s.lines+=n;s.score+=size*5+n*100*(s.combo||1);if(s.pieces.every(p=>!p))refill(s);s.lost=!possible(s);return true;}
 function validate(s){return !!s&&modes.some(m=>m.id===s.mode)&&U.ints(s.grid,64,0,5)&&Array.isArray(s.pieces)&&s.pieces.length===3&&s.pieces.every(p=>p===null||Number.isInteger(p.shape)&&p.shape>=0&&p.shape<shapes.length&&Number.isInteger(p.rot)&&p.rot>=0&&p.rot<4&&Number.isInteger(p.color)&&p.color>=1&&p.color<=5)&&Number.isInteger(s.round)&&s.round>0;}
 function draw(s,api){api.board.className='game-board blocks-board';if(!s.pieces[api.view.piece])api.view.piece=s.pieces.findIndex(Boolean);const chosen=s.pieces[api.view.piece],anchor=api.view.anchor,valid=chosen&&fits(s,chosen,anchor),preview=valid?cells(chosen).map(([x,y])=>anchor+y*8+x):[];const grid=document.createElement('div');grid.className='square-grid blocks-grid';for(let i=0;i<64;i++){const b=api.cell('',()=>{api.view.anchor=i;api.redraw();api.message(fits(s,chosen,i)?'Место подходит. Нажмите «Поставить фигуру».':'Здесь фигура не помещается. Выберите другое место.');});b.className='block-cell tone-'+s.grid[i]+(preview.includes(i)?' ghost tone-'+chosen.color:'')+(s.lastClear?.includes(i)?' just-cleared':'');b.dataset.cell=i;b.setAttribute('aria-label',`Строка ${Math.floor(i/8)+1}, столбец ${i%8+1}${s.grid[i]?', занято':''}`);grid.append(b);}api.board.append(grid);const tray=document.createElement('div');tray.className='block-tray';s.pieces.forEach((p,n)=>{const b=api.cell('',()=>{api.view.piece=n;api.view.anchor=null;api.redraw();api.message('Нажмите клетку для верхнего левого угла фигуры.');});b.className='piece-choice'+(n===api.view.piece?' selected-item':'');b.disabled=!p;b.dataset.piece=n;b.setAttribute('aria-label',p?'Выбрать фигуру '+(n+1):'Фигура использована');if(p){const xy=cells(p),w=Math.max(...xy.map(v=>v[0]))+1,h=Math.max(...xy.map(v=>v[1]))+1,mini=document.createElement('span');mini.className='mini-piece';mini.style.gridTemplateColumns=`repeat(${w},15px)`;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const c=document.createElement('i');c.className=xy.some(v=>v[0]===x&&v[1]===y)?'mini-block tone-'+p.color:'mini-gap';mini.append(c);}b.append(mini);}else b.textContent='✓';tray.append(b);});api.board.append(tray);
 api.tool('Поставить фигуру',()=>{if(!valid){api.message('Сначала выберите фигуру и свободное место на поле.');return;}const p=api.view.piece;api.view.anchor=null;api.send({type:'place',piece:p,i:anchor});api.message(s.lastClear.length?`Линии убраны · серия ×${s.combo} · всего линий ${s.lines}`:'Выберите место для следующей фигуры.');});if(s.mode==='relax')api.tool('↻ Повернуть',()=>api.send({type:'rotate',piece:api.view.piece}));
 }
 return {id:'blocks',key:'блоки',title:'Блоки 8×8',tag:'ПРОСТРАНСТВО ДЛЯ ВАШИХ РЕШЕНИЙ',subtitle:'Собирайте линии.\nОсвобождайте пространство.',modes,create,act,validate,draw,cells,fits,possible,shapes,undo:true,record:'score',lossText:'Ни одна из оставшихся фигур не помещается на поле. Попробуйте сохранить больше свободного пространства в новой партии.',startMessage:'Выберите фигуру, её место на поле и нажмите «Поставить фигуру».',help:['Размещайте фигуры на поле 8 × 8. Полностью заполненные строки и столбцы исчезают одновременно. Новые три фигуры появляются, когда использованы все три предыдущие.','Нажмите фигуру, затем клетку для её верхнего левого угла. Полупрозрачная подсветка показывает, где она окажется. Подтвердите кнопкой «Поставить фигуру».','Каждая клетка даёт 5 очков, линия — 100. Несколько ходов с очисткой подряд увеличивают множитель серии. Ход без очистки обнуляет серию.','В «Классике» фигуры не вращаются. В «Свободе» доступен бесплатный поворот. Партия заканчивается, когда ни одна оставшаяся фигура не помещается. Таймера на ход нет.']};
});
