'use strict';
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./casual-core'));else r.CasualGame=f(r.CasualCore);})(globalThis,U=>{
 const modes=[{id:'calm',label:'Прогулка',detail:'4 000 очков · 30 ходов',goal:4000,turns:30},{id:'classic',label:'Классика',detail:'6 500 очков · 30 ходов',goal:6500,turns:30},{id:'expert',label:'Вызов',detail:'9 000 очков · 25 ходов',goal:9000,turns:25}];
 function next(s){let x=s.rng>>>0||1;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0;return s.rng%6;}
 function matches(grid){const hit=new Set();for(let i=0;i<64;i++){const x=i%8,y=Math.floor(i/8),v=grid[i];if(x<6&&v===grid[i+1]&&v===grid[i+2]){let j=i;while(j<y*8+8&&grid[j]===v)hit.add(j++);}if(y<6&&v===grid[i+8]&&v===grid[i+16]){let j=i;while(j<64&&grid[j]===v){hit.add(j);j+=8;}}}return [...hit];}
 function adjacent(a,b){return Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&b>=0&&a<64&&b<64&&Math.abs(a%8-b%8)+Math.abs(Math.floor(a/8)-Math.floor(b/8))===1;}
 function swaps(s){const out=[];for(let a=0;a<64;a++)for(const b of [a+1,a+8]){if(!adjacent(a,b)||s.grid[a]===s.grid[b])continue;const copy=s.grid.slice();[copy[a],copy[b]]=[copy[b],copy[a]];if(matches(copy).length)out.push({type:'swap',a,b});}return out;}
 function fill(s){for(let attempt=0;attempt<100;attempt++){s.grid=[];for(let i=0;i<64;i++){const banned=[];if(i%8>=2&&s.grid[i-1]===s.grid[i-2])banned.push(s.grid[i-1]);if(i>=16&&s.grid[i-8]===s.grid[i-16])banned.push(s.grid[i-8]);let n=next(s);while(banned.includes(n))n=(n+1)%6;s.grid.push(n);}if(swaps(s).length)return;}throw Error('Cannot create playable board');}
 function create(mode,seed){const m=modes.find(m=>m.id===mode)||modes[0],s={...U.base(m.id,seed),grid:[],rng:seed>>>0||1,left:m.turns,goal:m.goal,cascade:0,changed:[],reshuffled:false};fill(s);return s;}
 function act(s,a){if(s.won||s.lost||a.type!=='swap'||!adjacent(a.a,a.b))return false;const grid=s.grid.slice();[grid[a.a],grid[a.b]]=[grid[a.b],grid[a.a]];let hit=matches(grid);if(!hit.length)return false;s.frames=[{kind:'swap',grid:grid.slice(),a:a.a,b:a.b}];s.grid=grid;s.left--;s.cascade=0;s.reshuffled=false;const changed=new Set();while(hit.length&&s.cascade<100){s.cascade++;s.frames.push({kind:'clear',grid:s.grid.slice(),hit:hit.slice(),cascade:s.cascade});s.score+=hit.length*50*s.cascade;hit.forEach(i=>{s.grid[i]=-1;changed.add(i);});const offsets=Array(64).fill(0);for(let x=0;x<8;x++){const keep=[];let incoming=-1;for(let y=7;y>=0;y--)if(s.grid[y*8+x]>=0)keep.push({v:s.grid[y*8+x],y});for(let y=7;y>=0;y--){const piece=keep.length?keep.shift():{v:next(s),y:incoming--};s.grid[y*8+x]=piece.v;offsets[y*8+x]=piece.y-y;changed.add(y*8+x);}}s.frames.push({kind:'fall',grid:s.grid.slice(),offsets});hit=matches(s.grid);}if(hit.length||!swaps(s).length){fill(s);s.reshuffled=true;s.frames.push({kind:'fall',grid:s.grid.slice()});}s.changed=[...changed];s.won=s.score>=s.goal;s.lost=!s.won&&s.left===0;return true;}
 async function animate(before,after,board){const grid=board.querySelector('.jewel-grid');if(!grid)return;const wait=ms=>new Promise(r=>setTimeout(r,ms));const paint=(values,cls='')=>{grid.querySelectorAll('.gem').forEach((el,i)=>{el.className='gem gem-'+values[i]+(cls?' '+cls:'');});};for(const frame of after.frames||[]){if(frame.kind==='swap'){const a=grid.children[frame.a],b=grid.children[frame.b],ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();const one=a.firstElementChild.animate([{translate:'0 0'},{translate:`${br.x-ar.x}px ${br.y-ar.y}px`}],{duration:180,easing:'ease-in-out'}),two=b.firstElementChild.animate([{translate:'0 0'},{translate:`${ar.x-br.x}px ${ar.y-br.y}px`}],{duration:180,easing:'ease-in-out'});await Promise.all([one.finished,two.finished]);paint(frame.grid);}else if(frame.kind==='clear'){paint(frame.grid);for(const i of frame.hit){const el=grid.children[i].firstElementChild;el.style.animationDelay='0ms';el.classList.add('is-clearing');}const rects=frame.hit.map(i=>grid.children[i].getBoundingClientRect());if(window.CasualStudio&&rects.length){CasualStudio.sound('gem');CasualStudio.burst(rects.reduce((n,r)=>n+r.x+r.width/2,0)/rects.length,rects.reduce((n,r)=>n+r.y+r.height/2,0)/rects.length,'+'+frame.hit.length*50*frame.cascade+(frame.cascade>1?' · ×'+frame.cascade:''));}await wait(290);}else{paint(frame.grid);const height=grid.children[8].getBoundingClientRect().y-grid.children[0].getBoundingClientRect().y;await Promise.all([...grid.children].map((cell,i)=>{const offset=frame.offsets?.[i]??-1;if(!offset)return Promise.resolve();return cell.firstElementChild.animate([{translate:`0 ${offset*height}px`,opacity:.45},{translate:'0 0',opacity:1}],{duration:310,easing:'cubic-bezier(.25,.5,.5,1)'}).finished;}));}}}
 function validate(s){const m=modes.find(m=>m.id===s?.mode);return !!m&&U.ints(s.grid,64,0,5)&&Number.isInteger(s.left)&&s.left>=0&&s.left<=m.turns&&s.goal===m.goal&&Number.isInteger(s.rng)&&s.rng>=0&&!matches(s.grid).length;}
 const symbols=['◆','●','✦','▲','⬟','■'],names=['Сапфир','Жемчуг','Рубин','Аметист','Янтарь','Изумруд'];
 function draw(s,api){api.board.className='game-board match-board';const summary=document.createElement('div');summary.className='match-summary';summary.innerHTML=`<span>Цель <b>${s.goal.toLocaleString('ru-RU')}</b></span><span>Ходов <b>${s.left}</b></span>`;api.board.append(summary);const progress=document.createElement('div');progress.className='match-progress';const bar=document.createElement('i');bar.style.width=Math.min(100,s.score/s.goal*100)+'%';progress.append(bar);api.board.append(progress);const grid=document.createElement('div');grid.className='square-grid jewel-grid';const animate=false;api.view.lastMove=s.moves;for(let i=0;i<64;i++){const b=api.cell('',()=>{if(performance.now()<(api.view.suppressUntil||0))return;const selected=api.view.selected;if(selected===i){api.view.selected=null;api.redraw();return;}if(selected!=null&&adjacent(selected,i)){api.view.selected=null;api.view.hint=null;if(!api.send({type:'swap',a:selected,b:i})){api.message('Нужен ряд из трёх одинаковых камней. Ход не потрачен.');api.redraw();}else api.message(`Каскадов: ${s.cascade}${s.reshuffled?' · Поле обновлено: прежних ходов не осталось.':''}`);return;}api.view.selected=i;api.redraw();});b.className='jewel-cell'+(api.view.selected===i?' selected-item':'')+(api.view.hint?.includes(i)?' hint-cell':'');b.dataset.cell=i;b.setAttribute('aria-label',names[s.grid[i]]+`, строка ${Math.floor(i/8)+1}, столбец ${i%8+1}`);const gem=document.createElement('span');gem.className='gem gem-'+s.grid[i]+(animate&&s.changed?.includes(i)?' gem-fall':'');gem.textContent=symbols[s.grid[i]];gem.style.animationDelay=Math.floor(i/8)*25+'ms';b.append(gem);grid.append(b);}api.board.append(grid);let down=null;grid.onpointerdown=e=>{const b=e.target.closest('[data-cell]');if(e.button===0&&b)down={i:Number(b.dataset.cell),x:e.clientX,y:e.clientY};};grid.onpointerup=e=>{if(!down)return;const d=down;down=null;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.max(Math.abs(dx),Math.abs(dy))<16)return;const b=d.i+(Math.abs(dx)>Math.abs(dy)?dx>0?1:-1:dy>0?8:-8);api.view.suppressUntil=performance.now()+400;api.view.selected=null;if(!api.send({type:'swap',a:d.i,b})){api.redraw();api.message('Нужен ряд из трёх. Ход не потрачен.');}};grid.onpointercancel=()=>down=null;api.tool('✦ Подсказка',()=>{const a=swaps(s)[0];if(a){api.aid();api.view.hint=[a.a,a.b];api.redraw();api.message('Поменяйте местами два выделенных камня.');}});}
 return {id:'match3',key:'три-в-ряд',title:'Три в ряд',tag:'КАЖДЫЙ КАМЕНЬ НА СВОЁМ МЕСТЕ',subtitle:'Найдите сочетание.\nЗапустите каскад.',modes,create,act,validate,draw,animate,matches,swaps,adjacent,undo:true,record:'score',startMessage:'Нажмите камень, затем соседний — соберите ряд из трёх.',lossText:'Ходы закончились. Цель не достигнута — попробуйте новую партию.',help:['Меняйте местами соседние камни по горизонтали или вертикали. Обмен допустим, только если получается ряд минимум из трёх одинаковых камней. Неверный обмен не расходует ход.','Совпадения исчезают, верхние камни падают, пустоты заполняются. Следующие совпадения образуют каскад: за каждый камень 50 очков, умноженные на номер каскада. Пересечения считаются один раз.','Достигните цели за указанное число ходов. Если возможных обменов не осталось, поле обновится бесплатно. Таймера на ход нет.','Камни отличаются формой и цветом. Подсказка показывает допустимый обмен, но партия с подсказкой не записывается в личный рекорд.']};
});
