'use strict';
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./casual-core'),require('./match3-levels'));else r.Match3Engine=f(r.CasualCore,r.Match3Levels);})(globalThis,(U,levels)=>{
 const classics=[{id:'calm',label:'Прогулка',detail:'4 000 очков · 30 ходов',goal:4000,turns:30},{id:'classic',label:'Классика',detail:'6 500 очков · 30 ходов',goal:6500,turns:30},{id:'expert',label:'Вызов',detail:'9 000 очков · 25 ходов',goal:9000,turns:25}],modes=[...levels,...classics];
 const names=['Сапфир','Жемчуг','Рубин','Аметист','Янтарь','Изумруд'],specialNames=['','Молния по горизонтали','Молния по вертикали','Взрыв','Радуга'];
 function next(s){let x=s.rng>>>0||1;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0;return s.rng%6;}
 function adjacent(a,b){return Number.isInteger(a)&&Number.isInteger(b)&&a>=0&&b>=0&&a<64&&b<64&&Math.abs(a%8-b%8)+Math.abs((a>>3)-(b>>3))===1;}
 function runs(grid){const out=[];for(const step of [1,8])for(let i=0;i<64;i++){const v=grid[i];if(v<0)continue;if(step===1?i%8&&grid[i-1]===v:i>=8&&grid[i-8]===v)continue;const cells=[];for(let j=i;j<64&&(step===8||(j>>3)===(i>>3))&&grid[j]===v;j+=step)cells.push(j);if(cells.length>=3)out.push({cells,step});}return out;}
 function matches(grid){return [...new Set(runs(grid).flatMap(r=>r.cells))];}
 function creations(grid,preferred=[]){const groups=[];for(const line of runs(grid)){const touching=groups.filter(g=>g.lines.some(r=>r.cells.some(i=>line.cells.includes(i))));const g={lines:[line,...touching.flatMap(g=>g.lines)]};for(const old of touching)groups.splice(groups.indexOf(old),1);groups.push(g);}return groups.flatMap(g=>{const cells=[...new Set(g.lines.flatMap(r=>r.cells))],longest=g.lines.reduce((a,b)=>a.cells.length>=b.cells.length?a:b),cross=g.lines.find(r=>r.step!==longest.step);const type=longest.cells.length>=5?4:cross?3:longest.cells.length===4?longest.step===1?1:2:0;if(!type)return [];const intersection=cells.find(i=>g.lines.filter(r=>r.cells.includes(i)).length>1);return [{at:preferred.find(i=>cells.includes(i))??intersection??longest.cells[Math.floor(longest.cells.length/2)],type}];});}
 function legal(s,a,b){if(!adjacent(a,b))return false;const specials=s.special||[];if(specials[a]===4||specials[b]===4||specials[a]&&specials[b])return true;const copy=s.grid.slice();[copy[a],copy[b]]=[copy[b],copy[a]];return matches(copy).some(i=>i===a||i===b);}
 function swaps(s){const out=[];for(let a=0;a<64;a++)for(const b of [a+1,a+8])if(legal(s,a,b))out.push({type:'swap',a,b});return out;}
 function fill(s){for(let attempt=0;attempt<100;attempt++){s.grid=[];for(let i=0;i<64;i++){const banned=[];if(i%8>=2&&s.grid[i-1]===s.grid[i-2])banned.push(s.grid[i-1]);if(i>=16&&s.grid[i-8]===s.grid[i-16])banned.push(s.grid[i-8]);let n=next(s);while(banned.includes(n))n=(n+1)%6;s.grid.push(n);}if(swaps(s).length)return;}throw Error('Cannot create playable board');}
 function resume(s){s.special??=Array(64).fill(0);s.ice??=Array(64).fill(0);s.collected??=Array(6).fill(0);s.iceBroken??=0;s.created??=0;s.activated??=0;}
 function create(mode,seed){const m=modes.find(m=>m.id===mode)||modes[0],s={...U.base(m.id,seed),grid:[],rng:seed>>>0||1,left:m.turns,goal:m.goal,cascade:0,changed:[],reshuffled:false};resume(s);s.ice=m.ice?.slice()||s.ice;fill(s);return s;}
 function objectives(s){const m=modes.find(m=>m.id===s.mode);return (m.objectives||[{type:'score',target:m.goal}]).map(g=>({...g,current:g.type==='score'?s.score:g.type==='ice'?s.iceBroken||0:s.collected?.[g.color]||0}));}
 const complete=s=>objectives(s).every(g=>g.current>=g.target);
 const progress=s=>objectives(s).reduce((n,g)=>n+Math.min(1,g.current/g.target),0)/objectives(s).length;
 function expand(s,initial,extra=[]){const hit=new Set([...initial,...extra]),activated=[],queue=[...hit];for(let k=0;k<queue.length;k++){const i=queue[k],type=s.special[i];if(!type)continue;activated.push(i);const add=j=>{if(!hit.has(j)){hit.add(j);queue.push(j);}};for(let j=0;j<64;j++){const dx=Math.abs(j%8-i%8),dy=Math.abs((j>>3)-(i>>3));if(type===1&&!dy||type===2&&!dx||type===3&&dx<=1&&dy<=1||type===4&&s.grid[j]===s.grid[i])add(j);}}return {hit:[...hit],activated};}
 function fall(s){const offsets=Array(64).fill(0);for(let x=0;x<8;x++){const keep=[];let incoming=-1;for(let y=7;y>=0;y--)if(s.grid[y*8+x]>=0)keep.push({v:s.grid[y*8+x],special:s.special[y*8+x],y});for(let y=7;y>=0;y--){const p=keep.length?keep.shift():{v:next(s),special:0,y:incoming--};s.grid[y*8+x]=p.v;s.special[y*8+x]=p.special;offsets[y*8+x]=p.y-y;}}return offsets;}
 function frame(s,kind,more={}){return {kind,grid:s.grid.slice(),special:s.special.slice(),ice:s.ice.slice(),...more};}
 function reshuffle(s){const pieces=s.grid.map((v,i)=>({v,special:s.special[i]}));for(let n=0;n<200;n++){for(let i=63;i>0;i--){next(s);const j=s.rng%(i+1);[pieces[i],pieces[j]]=[pieces[j],pieces[i]];}s.grid=pieces.map(p=>p.v);s.special=pieces.map(p=>p.special);if(!matches(s.grid).length&&swaps(s).length)return;}/* Exceptional fallback retains earned bonuses. */fill(s);}
 function act(s,a){if(!a||s.won||s.lost||a.type!=='swap'||!legal(s,a.a,a.b))return false;resume(s);const {a:x,b:y}=a;[s.grid[x],s.grid[y]]=[s.grid[y],s.grid[x]];[s.special[x],s.special[y]]=[s.special[y],s.special[x]];s.frames=[frame(s,'swap',{a:x,b:y})];s.left--;s.cascade=0;s.reshuffled=false;
  let forced=[],combo=s.special[x]&&s.special[y],prism=[x,y].find(i=>s.special[i]===4);
  if(prism!==undefined){const other=prism===x?y:x;if(s.special[other]===4)forced=Array.from({length:64},(_,i)=>i);else{forced=s.grid.flatMap((v,i)=>v===s.grid[other]?[i]:[]);if(s.special[other])forced.forEach(i=>{if(i!==prism)s.special[i]=s.special[other];});forced.push(prism);}s.special[prism]=0;s.activated++;}
  else if(combo){forced=[x,y];if(s.special[x]===3&&s.special[y]===3)forced=Array.from({length:64},(_,i)=>i).filter(i=>[x,y].some(p=>Math.abs(i%8-p%8)<=2&&Math.abs((i>>3)-(p>>3))<=2));}
  let hit=matches(s.grid),first=true;const changed=new Set();
  while((hit.length||forced.length)&&s.cascade<100){s.cascade++;const born=creations(s.grid,first?[y,x]:[]).filter(b=>!s.special[b.at]&&!forced.includes(b.at));const wave=expand(s,hit,forced),protectedCells=new Set(born.map(b=>b.at)),removed=wave.hit.filter(i=>!protectedCells.has(i));
   s.frames.push(frame(s,'clear',{hit:wave.hit,removed,cascade:s.cascade,born,activated:wave.activated}));s.score+=removed.length*50*s.cascade;s.activated+=wave.activated.length;
   for(const i of wave.hit){if(s.ice[i]){s.ice[i]--;s.iceBroken++;}changed.add(i);if(!protectedCells.has(i)){s.collected[s.grid[i]]++;s.grid[i]=-1;s.special[i]=0;}}
   born.forEach(b=>{s.special[b.at]=b.type;s.created++;});const offsets=fall(s);s.frames.push(frame(s,'fall',{offsets}));hit=matches(s.grid);forced=[];first=false;
  }
  if(hit.length||!swaps(s).length){reshuffle(s);s.reshuffled=true;s.frames.push(frame(s,'fall'));}s.changed=[...changed];s.won=complete(s);s.lost=!s.won&&s.left===0;return true;
 }
 function validate(s){const m=modes.find(m=>m.id===s?.mode);if(!m||!U.ints(s.grid,64,0,5)||!Number.isInteger(s.left)||s.left<0||s.left>m.turns||s.goal!==m.goal||!Number.isInteger(s.rng)||s.rng<0||s.rng>0xffffffff||matches(s.grid).length)return false;if(s.special===undefined)return !m.level;return U.ints(s.special,64,0,4)&&U.ints(s.ice,64,0,2)&&U.ints(s.collected,6,0,1e8)&&Number.isInteger(s.iceBroken)&&s.iceBroken>=0&&s.ice.every((v,i)=>v<=(m.ice?.[i]||0))&&s.ice.reduce((a,b)=>a+b,0)+s.iceBroken===(m.ice?.reduce((a,b)=>a+b,0)||0);}
 return {modes,levels,classics,names,specialNames,create,resume,act,validate,matches,runs,creations,swaps,adjacent,objectives,complete,progress,expand,reshuffle};
});
