'use strict';
(()=>{
 const R=window.Nonogram,bank=window.NonogramPuzzles,$=id=>document.getElementById(id),KEY='nonogram-game-v1',COLLECTION='nonogram-collection-v1';
 const labels={easy:'Лёгкий',medium:'Средний',hard:'Сложный'},descriptions={easy:'Небольшие рисунки 5 × 5: научитесь читать числа и находить первые клетки.',medium:'Рисунки 10 × 10: больше деталей и пересечений строк со столбцами.',hard:'Рисунки 15 × 15: подробные силуэты. Увеличьте поле и используйте «Двигать».'};
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}};
 let state=R.restore(read(KEY,null),bank),records=read(COLLECTION,{}),level=read('nonogram-level','easy'),chosen=null,playing=false,paused=false,brush='fill',selected=0,zoom=1,drag=null,checked=new Set(),lastTick=performance.now(),telegramActive=true;
 if(!R.sizes[level])level='easy';if(!records||typeof records!=='object'||Array.isArray(records))records={};
 const time=n=>{n=Math.floor(n);return (n>=3600?Math.floor(n/3600)+':':'')+String(Math.floor(n/60)%(n>=3600?60:100000)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');};
 const puzzle=()=>bank.find(p=>p.id===state.id),solved=id=>records[id]?.solved===true;
 function save(){if(state&&!write(KEY,state))$('save-status').textContent='Сохранение недоступно. Не закрывайте страницу до конца партии.';}
 function message(text){$('message').textContent=text;}
 function lobby(){const list=bank.filter(p=>p.level===level);if(!list.some(p=>p.id===chosen))chosen=(list.find(p=>!solved(p.id))||list[0]).id;
  document.querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',String(level===b.dataset.level)));$('level-description').textContent=descriptions[level];$('collection-count').textContent=bank.filter(p=>solved(p.id)).length+' / '+bank.length;
  $('puzzle-picker').replaceChildren();list.forEach((p,i)=>{const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0');b.dataset.puzzle=p.id;b.setAttribute('aria-pressed',String(p.id===chosen));b.setAttribute('aria-label',solved(p.id)?`Рисунок ${i+1}: ${p.name}, открыт`:`Рисунок ${i+1}, не открыт`);b.classList.toggle('solved',solved(p.id));b.onclick=()=>{chosen=p.id;lobby();};$('puzzle-picker').append(b);});
  const p=bank.find(p=>p.id===chosen),best=records[chosen]?.best;$('puzzle-info').textContent=solved(chosen)?p.name+(Number.isFinite(best)?' · лучшее без помощи '+time(best):' · рисунок открыт'):'Скрытый рисунок · единственное решение';$('play').firstChild.textContent=solved(chosen)?'Решить ещё раз ':'Открыть рисунок ';
  $('continue').hidden=!state||state.completed;$('continue').textContent=state?`Продолжить · ${state.n} × ${state.n} · ${time(state.seconds)}`:'Продолжить';write('nonogram-level',level);
 }
 function close(){$('dialog').close();lastTick=performance.now();}
 function modal(title){cancelDrag();$('dialog-body').replaceChildren();const h=document.createElement('h2');h.id='dialog-title';h.textContent=title;$('dialog-body').append(h);if(!$('dialog').open)$('dialog').showModal();lastTick=performance.now();return $('dialog-body');}
 function text(body,value){const p=document.createElement('p');p.textContent=value;body.append(p);}
 function button(body,label,fn,style='primary'){const b=document.createElement('button');b.className=style;b.textContent=label;b.onclick=fn;body.append(b);}
 function canPlay(){return playing&&!paused&&!state.completed&&!$('dialog').open&&!document.hidden&&telegramActive;}
 function setBrush(value){brush=value;document.querySelectorAll('[data-brush]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.brush===brush)));$('board-scroll').classList.toggle('pan',brush==='pan');if(playing)message(brush==='pan'?'Проведите по полю, чтобы переместить его. Закрашивание выключено.':brush==='cross'?'Крестиком отмечайте клетки, которые должны остаться пустыми.':brush==='erase'?'Стирайте отдельные отметки или проведите по ряду.':'Закрашивайте клетки. Повторное нажатие убирает отметку.');}
 function buildBoard(){const field=$('nonogram'),n=state.n;field.replaceChildren();field.style.setProperty('--size',n);field.setAttribute('aria-label',`Японский кроссворд ${n} на ${n}`);const corner=document.createElement('div');corner.className='corner';corner.textContent=n+' × '+n;field.append(corner);
  function clue(axis,i,values){const e=document.createElement('div');e.className=`clue ${axis}-clue`+(i%5===4&&i<n-1?(axis==='row'?' h-divider':' v-divider'):'');e.dataset.line=i;e.dataset.axis=axis;e.setAttribute('aria-label',`${axis==='row'?'Строка':'Столбец'} ${i+1}: ${values.join(', ')}`);for(const number of values){const span=document.createElement('span');span.textContent=number;e.append(span);}return e;}
  state.clues.cols.forEach((a,c)=>field.append(clue('col',c,a)));for(let r=0;r<n;r++){field.append(clue('row',r,state.clues.rows[r]));for(let c=0;c<n;c++){const b=document.createElement('button');b.className='pixel';b.type='button';b.dataset.index=r*n+c;b.style.setProperty('--row',r);b.onclick=e=>{if(e.detail===0&&canPlay()&&brush!=='pan'){selected=r*n+c;const value=brush==='cross'?-1:brush==='erase'?0:1;commit([{index:selected,value:state.board[selected]===value?0:value}]);}};field.append(b);}}
  resize();
 }
 function resize(){if(!state||!playing)return;const n=state.n,width=$('board-scroll').clientWidth,rowWidth=Math.max(...state.clues.rows.map(a=>a.reduce((sum,v)=>sum+String(v).length*10,0)+(a.length-1)*5+16)),colGroups=Math.max(...state.clues.cols.map(a=>a.length));const clueWidth=Math.max(35,rowWidth),base=Math.min(100,Math.max(16,Math.floor((width-clueWidth)/n))),cell=Math.round(base*zoom),font=Math.max(11,Math.min(17,cell*.48)),height=Math.ceil(colGroups*(font+2)+12);
  const field=$('nonogram');field.style.setProperty('--cell',cell+'px');field.style.setProperty('--clue-width',clueWidth+'px');field.style.setProperty('--clue-height',height+'px');$('board-scroll').style.scrollPadding=`${height}px 0 0 ${clueWidth}px`;$('zoom').textContent='Масштаб '+Math.round(zoom*100)+'%';$('zoom').setAttribute('aria-label','Масштаб '+Math.round(zoom*100)+'%, изменить');
 }
 function render(){if(!state)return;const n=state.n,board=state.board.slice();if(drag)for(const [i,v]of drag.changes)board[i]=v;const r=Math.floor(selected/n),c=selected%n;
  document.querySelectorAll('.pixel').forEach(b=>{const i=Number(b.dataset.index),row=Math.floor(i/n),col=i%n;b.className='pixel'+(board[i]===1?' filled':'')+(i===selected?' selected':'')+(row===r||col===c?' related':'')+(checked.has(i)?' error':'')+(drag?.changes.has(i)?' preview':'')+(col%5===4&&col<n-1?' v-divider':'')+(row%5===4&&row<n-1?' h-divider':'');b.textContent=board[i]===-1?'×':'';b.tabIndex=i===selected?0:-1;b.setAttribute('aria-label',`Строка ${row+1}, столбец ${col+1}: ${board[i]===1?'закрашено':board[i]===-1?'пусто':'не отмечено'}`);b.setAttribute('aria-pressed',String(board[i]===1));});
  document.querySelectorAll('.clue').forEach(e=>{const i=Number(e.dataset.line),row=e.dataset.axis==='row',values=Array.from({length:n},(_,j)=>board[row?i*n+j:j*n+i]),hints=state.clues[row?'rows':'cols'][i];e.classList.toggle('active',i===(row?r:c));e.classList.toggle('satisfied',JSON.stringify(R.runs(values))===JSON.stringify(hints));e.classList.toggle('impossible',!R.possibilities(values,hints,n).length);});
  $('selection-label').textContent=`Строка ${r+1} · столбец ${c+1}`;$('timer').textContent=time(state.seconds);$('difficulty').textContent=labels[state.level]+' · '+n+' × '+n;$('puzzle-number').textContent=String(bank.filter(p=>p.level===state.level).findIndex(p=>p.id===state.id)+1).padStart(2,'0');$('undo').disabled=!state.history.length||state.completed;$('redo').disabled=!state.future.length||state.completed;$('hint').disabled=state.completed;$('check').disabled=state.completed;
 }
 function complete(){document.body.classList.add('completed-picture');const record=records[state.id]||{};record.solved=true;if(!state.hints&&!state.checks&&(!Number.isFinite(record.best)||state.seconds<record.best))record.best=Math.floor(state.seconds);records[state.id]=record;write(COLLECTION,records);const p=puzzle(),body=modal('Вы открыли: '+p.name);const art=document.createElement('div');art.className='win-art';art.style.setProperty('--size',state.n);art.setAttribute('aria-label',p.name);for(const v of state.solution){const i=document.createElement('i');if(v)i.className='on';art.append(i);}body.append(art);text(body,`${state.n} × ${state.n} · ${time(state.seconds)} · подсказок: ${state.hints}. Рисунок добавлен в вашу коллекцию.`);button(body,'Следующий рисунок',()=>{close();const list=bank.filter(p=>p.level===state.level),next=list.find(p=>!solved(p.id));chosen=(next||list[(list.findIndex(p=>p.id===state.id)+1)%list.length]).id;start(true);});button(body,'К коллекции',()=>{close();back();},'secondary');window.Телеграм?.отклик?.('взятка');}
 function commit(changes){if(!canPlay()||!R.apply(state,changes))return;checked.clear();save();render();window.Телеграм?.отклик?.('карта');message('Ход сохранён');if(state.completed)complete();}
 function cancelDrag(){if(!drag)return;drag=null;render();}
 function setPaused(value){cancelDrag();paused=value;$('resume').hidden=!paused||!playing;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Продолжить игру':'Пауза');$('nonogram').inert=paused;$('nonogram').setAttribute('aria-hidden',String(paused));lastTick=performance.now();}
 function screens(game){playing=game;for(const [id,on]of [['экран-лобби',!game],['экран-игры',game]]){$(id).hidden=!on;$(id).classList.toggle('экран--виден',on);}lastTick=performance.now();window.scrollTo(0,0);}
 function start(fresh=false){if(fresh||!state||state.completed)state=R.create(bank.find(p=>p.id===chosen));level=state.level;chosen=state.id;selected=0;checked.clear();zoom=state.n===15?1.5:1;document.body.classList.remove('completed-picture');document.body.dataset.nonogramSize=state.n;screens(true);setPaused(false);buildBoard();setBrush('fill');render();save();$('board-scroll').scrollTo(0,0);}
 function launch(){if(state&&!state.completed){if(state.id===chosen){start(false);return;}const body=modal('Открыть другой рисунок?');text(body,'Текущая незавершённая партия будет заменена. Открытые рисунки останутся в коллекции.');button(body,'Открыть выбранный',()=>{close();start(true);});button(body,'Продолжить текущий',()=>{close();start(false);},'secondary');}else start(true);}
 function back(){if($('dialog').open){close();return;}if(playing){cancelDrag();save();screens(false);lobby();}else location.href='index.html';}
 function showHint(){if(!canPlay())return;const h=R.hint(state);if(!h)return;const body=modal('Следующий шаг'),position=`строка ${Math.floor(h.index/state.n)+1}, столбец ${h.index%state.n+1}`,verb=h.value===1?'закрашена':'пустой';state.hints++;save();
  text(body,h.kind==='logic'?`Посмотрите на ${h.axis==='row'?'строку':'столбец'} ${h.line+1}. При всех допустимых расположениях групп клетка (${position}) должна быть ${verb}.`:h.kind==='correction'?`В клетке (${position}) неверная отметка. По решению она должна быть ${verb}.`:`Можно открыть клетку (${position}): она должна быть ${verb}.`);text(body,'Подсказка учтена. Рисунок попадёт в коллекцию, но время этой партии не станет рекордом без помощи.');button(body,h.value===1?'Закрасить клетку':'Поставить крестик',()=>{close();selected=h.index;commit([{index:h.index,value:h.value}]);const cell=document.querySelector(`.pixel[data-index="${h.index}"]`);cell?.scrollIntoView({block:'nearest',inline:'nearest'});});button(body,'Продолжить самостоятельно',close,'secondary');
 }
 function help(){const body=modal('Как читать японский кроссворд');text(body,'Числа слева задают группы закрашенных клеток в строке, числа сверху — в столбце. Порядок важен. Между соседними группами должна быть хотя бы одна пустая клетка.');const example=document.createElement('div');example.className='nonogram-example';example.textContent='2  1   →   ■ ■ × ■ ×';body.append(example);text(body,'Например, «2 1» означает две закрашенные клетки подряд, затем пропуск и ещё одну клетку. Перед первой группой и после последней тоже могут быть пустые клетки. «0» — вся линия пустая.');text(body,'Переключайтесь между «Закрасить» и «Пусто». Повторное нажатие убирает отметку. Проведите вдоль строки или столбца, чтобы сделать несколько отметок одним ходом. «Отмена» возвращает весь такой ход.');text(body,'Числа линии становятся приглушёнными, когда группы совпадают. Красные числа означают, что текущие отметки противоречат этой линии. «Проверить» сверяет отметки с решением. Ошибки не отнимают жизни.');text(body,'На большом поле нажмите «Масштаб», затем «Двигать», чтобы прокрутить поле. Подсказки сверху и слева остаются видны. Для победы достаточно правильно закрасить рисунок — все пустые клетки отмечать не обязательно.');text(body,'Клавиатура: стрелки — клетка, пробел — закрасить, X — крестик, Delete — стереть, Ctrl/Cmd + Z — отмена. Правая кнопка мыши ставит крестик.');button(body,'Понятно',close);}
 const field=$('nonogram');field.addEventListener('contextmenu',e=>e.preventDefault());
 field.addEventListener('pointerdown',e=>{if(!canPlay()||brush==='pan'||drag||![0,2].includes(e.button))return;const cell=e.target.closest('.pixel');if(!cell)return;e.preventDefault();selected=Number(cell.dataset.index);const base=state.board[selected],target=e.button===2?-1:brush==='cross'?-1:brush==='erase'?0:1;drag={id:e.pointerId,start:selected,last:selected,axis:null,base,value:base===target?0:target,changes:new Map()};drag.changes.set(selected,drag.value);field.setPointerCapture(e.pointerId);render();});
 field.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const cell=document.elementFromPoint(e.clientX,e.clientY)?.closest('.pixel');if(!cell)return;const n=state.n,index=Number(cell.dataset.index),sr=Math.floor(drag.start/n),sc=drag.start%n,r=Math.floor(index/n),c=index%n;if(!drag.axis&&index!==drag.start)drag.axis=Math.abs(c-sc)>=Math.abs(r-sr)?'row':'col';if(!drag.axis)return;const from=drag.axis==='row'?drag.start%n:Math.floor(drag.start/n),to=drag.axis==='row'?c:r;for(let k=Math.min(from,to);k<=Math.max(from,to);k++){const i=drag.axis==='row'?sr*n+k:k*n+sc;if(state.board[i]===drag.base)drag.changes.set(i,drag.value);}selected=drag.axis==='row'?sr*n+c:r*n+sc;render();});
 field.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const changes=[...drag.changes].map(([index,value])=>({index,value}));drag=null;commit(changes);render();});field.addEventListener('pointercancel',cancelDrag);field.addEventListener('lostpointercapture',cancelDrag);
 document.querySelectorAll('[data-brush]').forEach(b=>{const choose=()=>{cancelDrag();setBrush(b.dataset.brush);};b.onclick=choose;b.addEventListener('pointerup',e=>{if(e.pointerType==='touch'){e.preventDefault();choose();}});});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;chosen=null;lobby();});
 $('play').onclick=launch;$('continue').onclick=()=>start(false);$('help').onclick=help;$('close-dialog').onclick=close;$('back').onclick=e=>{e.preventDefault();back();};$('collection').onclick=back;
 $('zoom').onclick=()=>{cancelDrag();zoom=zoom===1?1.5:zoom===1.5?2:1;resize();message(zoom>1?'Для прокрутки увеличенного поля выберите «Двигать».':'Поле уменьшено. Можно закрашивать клетки.');};
 $('pause').onclick=()=>setPaused(!paused);$('resume').onclick=()=>setPaused(false);$('hint').onclick=showHint;
 for(const name of ['undo','redo'])$(name).onclick=()=>{if(canPlay()&&R[name](state)){checked.clear();save();render();message(name==='undo'?'Ход отменён':'Ход повторён');if(state.completed)complete();}};
 $('check').onclick=()=>{if(!canPlay())return;checked=new Set(R.mistakes(state));state.checks++;save();render();message(checked.size?`Неверных отметок: ${checked.size}. Они выделены красным.`:'Все сделанные отметки верны. Продолжайте!');};
 $('restart').onclick=()=>{const body=modal('Начать этот рисунок заново?');text(body,'Все отметки текущей партии будут убраны. Коллекция открытых рисунков сохранится.');button(body,'Начать заново',()=>{close();chosen=state.id;start(true);});button(body,'Продолжить',close,'secondary');};
 document.addEventListener('keydown',e=>{if(!playing||$('dialog').open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'redo':'undo').click();return;}if(!canPlay()||e.altKey||e.ctrlKey||e.metaKey)return;const n=state.n,r=Math.floor(selected/n),c=selected%n,delta={ArrowLeft:c>0?-1:0,ArrowRight:c<n-1?1:0,ArrowUp:r>0?-n:0,ArrowDown:r<n-1?n:0};if(e.key in delta){e.preventDefault();selected+=delta[e.key];render();document.querySelector(`.pixel[data-index="${selected}"]`).focus();}else if([' ','x','X','Delete','Backspace'].includes(e.key)&&!e.target.closest('button:not(.pixel)')){e.preventDefault();const value=e.key===' '?1:e.key.toLowerCase()==='x'?-1:0;commit([{index:selected,value:state.board[selected]===value?0:value}]);}});
 setInterval(()=>{const now=performance.now(),elapsed=(now-lastTick)/1000;lastTick=now;if(canPlay()&&elapsed<3){state.seconds+=elapsed;$('timer').textContent=time(state.seconds);save();}},1000);
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){setPaused(true);save();}lastTick=performance.now();});window.addEventListener('pagehide',()=>{cancelDrag();save();});window.addEventListener('resize',resize);
 let bound=null;function telegram(){window.Телеграм?.показатьСтрелку(back);window.Телеграм?.цветОкна('#0c1919');const tg=window.Telegram?.WebApp;if(tg&&bound!==tg){bound=tg;tg.onEvent?.('deactivated',()=>{telegramActive=false;if(playing)setPaused(true);save();});tg.onEvent?.('activated',()=>{telegramActive=true;lastTick=performance.now();});}}telegram();window.addEventListener('load',telegram);lobby();
})();
