'use strict';
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./solitaire-core'));else r.SolitaireView=f(r.SolitaireCore);})(globalThis,S=>{
 const suits=['♠','♥','♣','♦'],ranks=['','A','2','3','4','5','6','7','8','9','10','J','Q','K'];
 function draw(s,api){api.board.className='game-board solitaire-board '+s.kind+(api.view.largeCards?' cards-large':'');api.board.style.setProperty('--piles',s.piles.length);const selection=api.view.selection;
  function choose(area,pile,index){const from={area,pile,index};if(selection){const move={type:'move',from:selection,to:{area,pile}};if(S.legal(s,move)){api.view.selection=null;api.send(move);return;}}
   const src=S.source(s,from);if(src?.[index]?.up){api.view.selection=from;api.message('Выбрано '+ranks[S.rank(src[index])]+suits[S.suit(src[index])]+'. Нажмите место назначения.');}else api.view.selection=null;api.redraw();
  }
  function card(c,fn){const b=api.cell('',fn);b.className='playing-card'+(!c?.up?' back-card':S.red(c)?' red-card':'');if(c?.up){b.innerHTML=`<span class="card-corner">${ranks[S.rank(c)]}<i>${suits[S.suit(c)]}</i></span><span class="card-suit">${suits[S.suit(c)]}</span><span class="card-mirror">${ranks[S.rank(c)]}${suits[S.suit(c)]}</span>`;if(window.КолодаРисунок){b.replaceChildren(window.КолодаРисунок.нарисовать(suits[S.suit(c)],({A:'Т',J:'В',Q:'Д',K:'К'})[ranks[S.rank(c)]]||ranks[S.rank(c)]));}b.dataset.card=c.id;b.setAttribute('aria-label',ranks[S.rank(c)]+suits[S.suit(c)]);}else{b.textContent='✥';b.setAttribute('aria-label','Закрытая карта');}if(c)b.dataset.card=c.id;return b;}
  const top=document.createElement('div');top.className='solitaire-top';api.board.append(top);
  if(s.kind==='freecell'){const cells=document.createElement('div');cells.className='free-cells';s.cells.forEach((p,i)=>{const b=p.length?card(p[0],()=>choose('cells',i,0)):api.cell('○',()=>choose('cells',i,0));b.classList.add('card-slot');if(selection?.area==='cells'&&selection.pile===i)b.classList.add('selected-item');cells.append(b);});top.append(cells);}
  else{const draw=card(null,()=>{api.view.selection=null;if(!api.send({type:'draw'}))api.message(s.kind==='spider'&&s.piles.some(p=>!p.length)?'Перед раздачей заполните пустые столбцы.':'Колода пуста.');});draw.classList.add('stock');draw.textContent=s.stock.length?'✥':'↶';draw.setAttribute('aria-label','Раздать карты');const counter=document.createElement('small');counter.textContent=s.stock.length;draw.append(counter);top.append(draw);if(s.kind==='klondike'){const w=s.waste.at(-1),b=w?card(w,()=>choose('waste',0,s.waste.length-1)):api.cell('·',()=>{});b.classList.add('card-slot');if(selection?.area==='waste')b.classList.add('selected-item');top.append(b);}}
  if(s.kind==='spider'){const done=document.createElement('div');done.className='spider-complete';done.textContent='Собрано '+s.finished.length+' / 8';top.append(done);}else{const foundations=document.createElement('div');foundations.className='foundations';s.foundations.forEach((p,i)=>{const b=p.length?card(p.at(-1),()=>choose('foundations',i,p.length-1)):api.cell(suits[i],()=>choose('foundations',i,0));b.classList.add('card-slot');b.setAttribute('aria-label','Дом '+suits[i]+(p.length?', '+ranks[p.length]:', пусто'));foundations.append(b);});top.append(foundations);}
  const table=document.createElement('div');table.className='tableau';s.piles.forEach((p,i)=>{const col=document.createElement('div');col.className='card-pile';col.style.height=`calc(var(--card-h) + ${Math.max(0,p.length-1)} * var(--card-step))`;col.dataset.pile=i;if(!p.length){const b=api.cell(s.kind==='klondike'?'K':'·',()=>choose('piles',i,0));b.className='card-slot empty-pile';col.append(b);}p.forEach((c,j)=>{const b=card(c,()=>choose('piles',i,j));b.style.top=`calc(${j} * var(--card-step))`;b.dataset.pile=i;b.dataset.index=j;if(c.up&&j<p.length-1){const label=document.createElement('span');label.className='card-stack-label';label.textContent=ranks[S.rank(c)]+suits[S.suit(c)];b.append(label);}if(selection?.area==='piles'&&selection.pile===i&&j>=selection.index)b.classList.add('selected-item');col.append(b);});table.append(col);});api.board.append(table);
  api.tool('Подсказать ход',()=>{const next=S.moves(s)[0];if(!next){api.message('Допустимых ходов не найдено. Можно отменить ход или начать новую раздачу.');return;}api.aid();if(next.type==='draw'){api.message('Можно открыть следующую порцию карт из колоды.');return;}api.view.selection=next.from;api.redraw();api.message('Выделенные карты можно перенести '+(next.to.area==='foundations'?'в дом '+suits[next.to.pile]:next.to.area==='cells'?'в свободную ячейку':'в столбец '+(next.to.pile+1))+'.');});
  if(s.kind!=='spider')api.tool('Карту в дом',()=>{const next=S.moves(s).find(a=>a.to?.area==='foundations');if(next){api.view.selection=null;api.send(next);}else api.message('Сейчас нет карты, которую можно перенести в дом.');});
  if(matchMedia('(max-width:599px)').matches&&s.kind!=='klondike')api.tool(api.view.largeCards?'Весь стол':'Крупные карты',()=>{api.view.largeCards=!api.view.largeCards;api.redraw();},!!api.view.largeCards);
  api.status(s.kind==='spider'?'СОБРАНО':'В ДОМАХ',s.kind==='spider'?s.finished.length+' / 8':s.foundations.reduce((n,p)=>n+p.length,0)+' / 52');
 }
 return {draw};
});
