'use strict';
(()=>{
 const R=window.Sudoku,$=id=>document.getElementById(id),KEY='sudoku-game-v1',LEVEL='sudoku-level',BEST='sudoku-best-v1';
 const labels={easy:'Лёгкий',medium:'Средний',hard:'Сложный',expert:'Эксперт'},descriptions={easy:'Разминка: ищите клетки, в которых возможна только одна цифра.',medium:'Понадобится искать единственное место для цифры в строке, столбце или квадрате.',hard:'Используйте заметки, пары кандидатов и связи между квадратами.',expert:'Задачи за пределами простых одиночек и пар. Для тех, кто любит сложную логику.'};
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}};
 let state=R.restore(read(KEY,null)),level=read(LEVEL,'easy'),records=read(BEST,{}),selected=-1,noteMode=false,playing=false,paused=false,telegramActive=true,checked=new Set(),lastTick=performance.now();
 if(!R.levels.includes(level))level='easy';if(!records||typeof records!=='object'||Array.isArray(records))records={};
 const time=n=>{n=Math.floor(n);return n>=3600?`${Math.floor(n/3600)}:${String(Math.floor(n/60)%60).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`:`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;};
 function save(){if(state&&!write(KEY,state))$('save-status').textContent='Сохранение недоступно. Не закрывайте страницу до конца партии.';}
 function lobby(){document.querySelectorAll('[data-level]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.level===level)));$('level-description').textContent=descriptions[level];const record=records[level];$('record').textContent=Number.isFinite(record)&&record>=0?time(record):'—';$('continue').hidden=!state||state.completed;$('continue').textContent=state?`Продолжить · ${labels[state.level]} · ${time(state.seconds)}`:'Продолжить партию';write(LEVEL,level);}
 function screens(game){playing=game;for(const [id,visible]of [['экран-игры',game],['экран-лобби',!game]]){$(id).hidden=!visible;$(id).classList.toggle('экран--виден',visible);}window.scrollTo(0,0);lastTick=performance.now();}
 function close(){$('dialog').close();lastTick=performance.now();}
 function modal(title){$('dialog-body').replaceChildren();const h=document.createElement('h2');h.id='dialog-title';h.textContent=title;$('dialog-body').append(h);if(!$('dialog').open)$('dialog').showModal();lastTick=performance.now();return $('dialog-body');}
 function paragraph(body,text){const p=document.createElement('p');p.textContent=text;body.append(p);}
 function action(body,label,fn,style='primary'){const b=document.createElement('button');b.className=style;b.textContent=label;b.onclick=fn;body.append(b);}
 function setPaused(value){paused=value;$('resume').hidden=!paused||!playing;$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Продолжить игру':'Пауза');$('board').inert=paused;$('board').setAttribute('aria-hidden',String(paused));lastTick=performance.now();}
 function canPlay(){return playing&&!paused&&!state.completed&&!$('dialog').open&&!document.hidden&&telegramActive;}
 function render(){if(!state)return;const bad=new Set([...R.conflicts(state.board),...checked]),value=state.board[selected],peer=new Set(selected>=0?R.peers[selected]:[]);
  [...$('board').children].forEach((cell,i)=>{const n=state.board[i];cell.replaceChildren();cell.className=[state.puzzle[i]?'given':'',peer.has(i)?'peer':'',value&&n===value?'same':'',selected===i?'selected':'',bad.has(i)?'error':''].join(' ');cell.setAttribute('aria-pressed',String(selected===i));cell.tabIndex=selected===i||selected<0&&i===0?0:-1;
   cell.setAttribute('aria-label',`Строка ${Math.floor(i/9)+1}, столбец ${i%9+1}: ${n||'пусто'}${state.puzzle[i]?', исходная цифра':''}${bad.has(i)?', ошибка':''}${!n&&state.notes[i]?', заметки '+R.bits(state.notes[i]).join(', '):''}`);
   if(n)cell.textContent=n;else if(state.notes[i]){const box=document.createElement('span');box.className='pencil';box.setAttribute('aria-hidden','true');for(let k=1;k<=9;k++){const span=document.createElement('span');span.textContent=state.notes[i]&(1<<(k-1))?k:'';box.append(span);}cell.append(box);}
  });
  const count=state.board.filter(Boolean).length;$('progress').textContent=count+' / 81';$('progress-fill').style.width=count/81*100+'%';$('timer').textContent=time(state.seconds);$('difficulty').textContent=labels[state.level];$('undo').disabled=!state.history.length||state.completed;$('erase').disabled=selected<0||!!state.puzzle[selected]||state.completed;$('notes').setAttribute('aria-pressed',String(noteMode));$('hint').disabled=state.completed;$('check').disabled=state.completed;
  [...$('keypad').children].forEach((button,i)=>{const remaining=Math.max(0,9-state.board.filter(n=>n===i+1).length);button.querySelector('small').textContent=remaining;button.classList.toggle('done',remaining===0);button.setAttribute('aria-label',`Цифра ${i+1}, осталось ${remaining}`);});
 }
 function message(text){$('message').textContent=text;}
 function select(i,focus=false){if(!canPlay())return;selected=i;checked.clear();render();if(focus)$('board').children[i].focus({preventScroll:true});message(state.puzzle[i]?'Исходная цифра · выберите пустую клетку':noteMode?'Заметки: отметьте возможные цифры':'Введите цифру от 1 до 9');}
 function complete(){document.body.classList.add('complete');if(!state.hints){const prev=records[state.level];if(!Number.isFinite(prev)||state.seconds<prev){records[state.level]=Math.floor(state.seconds);write(BEST,records);}}
  window.Телеграм?.отклик?.('взятка');const body=modal('Всё на своих местах!'),symbol=document.createElement('div');symbol.className='win-symbol';symbol.textContent='✦';body.append(symbol);paragraph(body,`${labels[state.level]} · ${time(state.seconds)} · подсказок: ${state.hints}. Судоку решено правильно.`);action(body,'Ещё одна задача',()=>{close();start(true);});action(body,'Выбрать сложность',()=>{close();back();},'secondary');
 }
 function input(n){if(!canPlay())return;if(selected<0){message('Сначала выберите клетку на поле');return;}if(state.puzzle[selected]){message('Исходные цифры изменять нельзя');return;}if(R.enter(state,selected,n,noteMode&&n!==0)){checked.clear();save();render();window.Телеграм?.отклик?.('карта');const bad=R.conflicts(state.board);message(bad.length?'Есть повтор в строке, столбце или квадрате':noteMode?'Заметка сохранена':'Ход сохранён');if(state.completed)complete();}}
 function start(fresh=false){if(fresh||!state||state.completed){state=R.create(level,window.SudokuPuzzles,crypto.getRandomValues(new Uint32Array(1))[0]);noteMode=false;}level=state.level;selected=state.board.indexOf(0);checked.clear();document.body.classList.remove('complete');screens(true);setPaused(false);render();save();message('Выберите клетку и цифру');}
 function newGame(){if(state&&!state.completed){const body=modal('Начать новую задачу?');paragraph(body,'Сохранённая партия будет заменена. Лучшее время сохранится.');action(body,'Начать новую',()=>{close();start(true);});action(body,'Продолжить текущую',()=>{close();start(false);},'secondary');}else start(true);}
 function back(){if($('dialog').open){close();return;}if(playing){save();screens(false);lobby();}else location.href='index.html';}
 function hint(){if(!canPlay())return;const h=R.hint(state,selected);if(!h)return;const body=modal('Подсказка'),position=`строка ${Math.floor(h.index/9)+1}, столбец ${h.index%9+1}`;
  const explanations={deduction:`После исключения связанных кандидатов и пар в клетке (${position}) остаётся ${h.value}.`,single:`В клетке (${position}) все цифры, кроме ${h.value}, уже встречаются в её строке, столбце или квадрате.`,hidden:`Для цифры ${h.value} осталось единственное место в одной из её строки, столбца или квадрата: ${position}.`,correction:`В клетке (${position}) стоит неверная цифра. Правильная — ${h.value}.`,reveal:`Сейчас нужна более сложная цепочка рассуждений. Можно открыть значение клетки (${position}): ${h.value}.`};
  // Looking at the explanation already reveals information, even if insertion is declined.
  state.hints++;save();paragraph(body,explanations[h.technique]);paragraph(body,'Подсказка учтена. Эту партию можно завершить, но она не обновит рекорд без подсказок.');action(body,'Вставить '+h.value,()=>{close();selected=h.index;noteMode=false;R.enter(state,h.index,h.value);checked.clear();save();render();$('board').children[h.index].classList.add('hinted');message('Подсказка применена');if(state.completed)complete();});action(body,'Продолжить самостоятельно',close,'secondary');
 }
 function help(){const body=modal('Как играть в судоку');paragraph(body,'Заполните поле цифрами от 1 до 9. В каждой строке, каждом столбце и каждом квадрате 3 × 3 цифры должны встречаться ровно один раз.');paragraph(body,'Выберите клетку, затем цифру внизу или на клавиатуре. Тёмные цифры заданы условием; цветные — ваши. Подсвечиваются связанные клетки и одинаковые цифры.');paragraph(body,'«Заметки» позволяют записать несколько кандидатов. Повторное нажатие цифры убирает заметку. «Отмена» возвращает последний ход вместе с заметками. Красный цвет предупреждает о повторе. «Проверить» сверяет заполненные клетки с решением.');paragraph(body,'Подсказки объясняют следующий шаг, а если простой шаг не найден — предлагают открыть одну клетку. Ограничения по времени и жизням нет. Число под кнопкой цифры показывает, сколько таких цифр ещё не поставлено.');paragraph(body,'Клавиатура: стрелки — выбрать клетку, 1–9 — ввести, N — заметки, Delete — стереть, Ctrl/Cmd + Z — отмена.');action(body,'Понятно',close);}
 for(let i=0;i<81;i++){const cell=document.createElement('button');cell.type='button';cell.dataset.index=i;cell.dataset.row=Math.floor(i/9);cell.dataset.col=i%9;cell.onclick=()=>select(i);$('board').append(cell);}
 for(let n=1;n<=9;n++){const button=document.createElement('button');button.innerHTML=`<span>${n}</span><small>9</small>`;button.dataset.number=n;button.onclick=()=>input(n);$('keypad').append(button);}
 document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{level=b.dataset.level;lobby();});
 $('play').onclick=newGame;$('continue').onclick=()=>start(false);$('new').onclick=()=>{const body=modal('Новая игра');paragraph(body,'Вернитесь к выбору сложности. Текущая партия сохранится, пока вы не начнёте новую.');action(body,'Выбрать сложность',()=>{close();back();});action(body,'Остаться в игре',close,'secondary');};
 $('back').onclick=e=>{e.preventDefault();back();};$('help').onclick=help;$('close-dialog').onclick=close;
 $('notes').onclick=()=>{if(!canPlay())return;noteMode=!noteMode;render();message(noteMode?'Заметки включены · отмечайте возможные цифры':'Заметки выключены · вводите ответ');};$('erase').onclick=()=>input(0);
 $('undo').onclick=()=>{if(canPlay()&&R.undo(state)){checked.clear();save();render();message('Последний ход отменён');}};
 $('hint').onclick=hint;$('check').onclick=()=>{if(!canPlay())return;checked=new Set(state.board.map((n,i)=>n&&n!==state.solution[i]?i:-1).filter(i=>i>=0));render();message(checked.size?`Неверных клеток: ${checked.size}. Они выделены красным.`:'Заполненные клетки верны. Продолжайте!');};
 $('pause').onclick=()=>{if(playing)setPaused(!paused);};$('resume').onclick=()=>setPaused(false);
 document.addEventListener('keydown',e=>{if(!playing||$('dialog').open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();return;}if(e.ctrlKey||e.metaKey||e.altKey||!canPlay())return;
  if(/^[1-9]$/.test(e.key)){e.preventDefault();input(Number(e.key));}else if(['Delete','Backspace','0'].includes(e.key)){e.preventDefault();input(0);}else if(e.key.toLowerCase()==='n'){$('notes').click();}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const i=Math.max(0,selected),r=Math.floor(i/9),c=i%9,delta={ArrowLeft:c>0?-1:0,ArrowRight:c<8?1:0,ArrowUp:r>0?-9:0,ArrowDown:r<8?9:0}[e.key];select(i+delta,true);}
 });
 function tick(){const now=performance.now(),elapsed=(now-lastTick)/1000;lastTick=now;if(playing&&!paused&&!state.completed&&!$('dialog').open&&!document.hidden&&telegramActive&&elapsed<3){state.seconds+=elapsed;$('timer').textContent=time(state.seconds);save();}}
 setInterval(tick,1000);document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){setPaused(true);save();}lastTick=performance.now();});window.addEventListener('pagehide',save);
 let bound=null;function telegram(){window.Телеграм?.показатьСтрелку(back);window.Телеграм?.цветОкна('#0c1919');const tg=window.Telegram?.WebApp;if(tg&&bound!==tg){bound=tg;tg.onEvent?.('deactivated',()=>{telegramActive=false;if(playing)setPaused(true);save();});tg.onEvent?.('activated',()=>{telegramActive=true;lastTick=performance.now();});}}
 telegram();window.addEventListener('load',telegram);lobby();
})();
