/* Поле: изображения отдельно от правил; эффекты не меняют результат боя. */
(function(){'use strict';const R=window.Bastion;
class BastionField{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.images={};this.effects=[];this.weapons=new BastionWeapons.Weapons();this.visualTime=0;this.previous=[];this.ghosts=[];this.delayedHp=new Map();this.selected=-1;this.aim=false;this.motion=true;this.static=document.createElement('canvas');this.static.width=this.static.height=1000;this.map=-1;this.loaded=false;this.resize=new ResizeObserver(()=>this.fit());this.resize.observe(canvas);}
 async load(){const names=['island-a','island-b','island-c','pad','beacon',...Object.keys(R.TOWERS),'raider','crab','boss'];const versions=Object.fromEntries(names.map(n=>[n,'v1']));for(const name of ['mortar-overhead','ballista-overhead','weapon-plinth']){names.push(name);versions[name]='v4';}for(const name of Object.keys(R.ENEMIES)){names.push(name+'-walk');versions[name+'-walk']='v5';}names.push('pontoon');versions.pontoon='v5';this.spriteFrames={};this.spriteTiles={};this.renderImages={};const result=await Promise.allSettled(names.map(async k=>{const im=new Image();im.src='img/бастион/'+k+'-'+versions[k]+'.webp';await im.decode();this.images[k]=im;if(k.endsWith('-walk')){this.spriteFrames[k]=this.frames(im);this.spriteTiles[k]=this.spriteFrames[k].map(q=>[this.tile(im,q,false),this.tile(im,q,true)]);}else if(!k.startsWith('island-'))this.renderImages[k]=this.texture(im,320);else this.renderImages[k]=im;}));this.weapons.images=this.renderImages;this.loaded=result.every(r=>r.status==='fulfilled');this.map=-1;return this.loaded;}
 texture(im,size){const c=document.createElement('canvas'),scale=Math.min(1,size/Math.max(im.width,im.height));c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);return c;}
 tile(im,q,hit){const c=document.createElement('canvas');c.height=192;c.width=Math.ceil(c.height*q.w/q.h);const x=c.getContext('2d');if(hit)x.filter='brightness(1.6)';x.drawImage(im,q.x,q.y,q.w,q.h,0,0,c.width,c.height);return c;}
 fit(){const box=this.canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.round(box.width*dpr),h=Math.round(box.height*dpr);this.camera=box.height>box.width*1.05?{x:60,y:0,w:880,h:1000}:{x:0,y:0,w:1000,h:1000};if(w>0&&h>0&&(this.canvas.width!==w||this.canvas.height!==h)){this.canvas.width=w;this.canvas.height=h;}}
 screenPoint(p){this.fit();const a=this.camera;return {x:(p.x-a.x)/a.w,y:(p.y-a.y)/a.h};}
 worldPoint(x,y){this.fit();const a=this.camera;return {x:a.x+x*a.w,y:a.y+y*a.h};}
 // Альфа-границы считаются один раз: кадры имеют одну высоту и опору у ног.
 frames(im){const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(im,0,0);const data=x.getImageData(0,0,c.width,c.height).data,w=c.width/2,h=c.height/2,out=[];for(let n=0;n<4;n++){const ox=n%2*w,oy=Math.floor(n/2)*h;let l=w,r=0,t=h,b=0;for(let y=0;y<h;y++)for(let xx=0;xx<w;xx++)if(data[((oy+y)*c.width+ox+xx)*4+3]>40){l=Math.min(l,xx);r=Math.max(r,xx);t=Math.min(t,y);b=Math.max(b,y);}out.push({x:ox+l,y:oy+t,w:r-l+1,h:b-t+1});}return out;}
 background(map){const c=this.static.getContext('2d'),m=R.MAPS[map];c.clearRect(0,0,1000,1000);c.save();if(m.mirror){c.translate(1000,0);c.scale(-1,1);}if(this.images[m.skin])c.drawImage(this.images[m.skin],0,0,1000,1000);c.restore();for(const p of R.pads(map)){if(this.images.pad)c.drawImage(this.images.pad,p.x-52,p.y-40,104,82);}const p=R.position(map,0);c.fillStyle='#423220';c.fillRect(p.x-19,p.y-52,4,40);c.fillStyle='#692d49';c.beginPath();c.moveTo(p.x-15,p.y-52);c.lineTo(p.x+12,p.y-43);c.lineTo(p.x-15,p.y-30);c.fill();this.water=[];const pixels=c.getImageData(0,0,1000,1000).data;for(let y=25;y<1000;y+=65)for(let x=25;x<1000;x+=67){if(x>125&&x<875&&y>75&&y<920)continue;const i=(y*1000+x)*4;if(pixels[i+2]>pixels[i]*1.2&&pixels[i+1]>pixels[i]*1.25)this.water.push({x,y});}this.map=map;}

 event(e){
 if(e.type==='combo'&&this.effects.some(f=>f.type==='combo'&&f.kind===e.kind&&f.age<.55&&Math.hypot(f.x-e.x,f.y-e.y)<100))return;
 if(e.type==='shot'){
  const pad=R.pads(this.map).findIndex(p=>p.x===e.from.x&&p.y===e.from.y),t=this.state?.towers.find(t=>t.pad===pad);
  const duration=e.tower==='mortar'?.42:e.tower==='ballista'?.24:.2;
  if(t&&!['mortar','ballista'].includes(t.type))this.weapons.fire(t,e.from,e.to,this.motion);
  const muzzle=t&&['mortar','ballista'].includes(t.type)?this.weapons.fire(t,e.from,e.to,this.motion):{x:e.from.x,y:e.from.y-70};
  if(this.motion){for(const q of e.targets){for(const g of this.ghosts){if(Math.hypot(g.p.x-q.x,g.p.y-q.y)<9)g.until=Math.max(g.until,this.visualTime+duration);}for(const fx of this.effects){if(['kill','death','combo'].includes(fx.type)&&Math.hypot(fx.x-q.x,fx.y-q.y)<9)fx.age=-duration;}const old=this.previous.find(a=>Math.hypot(a.p.x-q.x,a.p.y-q.y)<9);if(old){this.effects.push({type:'hit',id:old.e.id,age:-duration,duration:.13});const hold=this.delayedHp.get(old.e.id);this.delayedHp.set(old.e.id,{until:Math.max(hold?.until||0,this.visualTime+duration),hp:hold?.hp??old.e.hp});}}
   this.effects.push({...e,from:muzzle,age:0,duration,flight:duration});this.effects.push({type:'impact',tower:e.tower,...e.to,age:-duration,duration:.55,color:e.tower==='tide'||e.tower==='storm'?'#8fe8ff':'#ffb34a',radius:e.splash||18});
   if(e.tower==='mortar')this.effects.push({type:'smoke',...muzzle,age:0,duration:1.1});
  }if(this.effects.length>200)this.effects.splice(0,this.effects.length-200);return;
 }
 if(e.type==='kill'&&this.motion){const old=this.previous.find(a=>e.id===a.e.id||Math.hypot(a.p.x-e.x,a.p.y-e.y)<9);if(old){this.ghosts.push({e:old.e,p:{x:e.x,y:e.y},until:this.visualTime+.32});this.effects.push({type:'death',e:old.e,x:e.x,y:e.y,age:-.32,duration:.38});}}
 if(!this.motion&&e.type==='kill')return;
 const duration=e.type==='meteor'?.85:e.type==='kill'?.9:e.type==='tide'?1:1.2;this.effects.push({...e,age:e.type==='kill'?-.32:0,duration});if(this.effects.length>200)this.effects.splice(0,this.effects.length-200);
 }
 draw(s,dt){if(!s)return;this.state=s;this.visualTime+=dt;this.fit();if(this.map!==s.map){this.weapons.reset();this.ghosts=[];this.previous=[];this.delayedHp.clear();this.background(s.map);}const c=this.ctx,a=this.camera,k=this.canvas.width/a.w,j=this.canvas.height/a.h;c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,this.canvas.width,this.canvas.height);c.setTransform(k,0,0,j,-a.x*k,-a.y*j);c.drawImage(this.static,0,0);this.ambient(s.time);this.tidalPath(s);const pads=R.pads(s.map),t=s.towers.find(t=>t.pad===this.selected);
 if(this.selected>=0&&pads[this.selected]){const p=pads[this.selected],radius=t?R.stats(t,s).range:210;c.beginPath();c.arc(p.x,p.y,radius,0,Math.PI*2);c.fillStyle='#75e9d21b';c.fill();c.strokeStyle='#bff7d998';c.lineWidth=2;c.setLineDash([7,9]);c.stroke();c.setLineDash([]);}
 for(let i=0;i<pads.length;i++){if(s.towers.some(t=>t.pad===i))continue;const p=pads[i];c.fillStyle=i===this.selected?'#ffffff':'#fff5cc';c.font='bold 35px Georgia';c.textAlign='center';c.fillText('+',p.x,p.y+11);}
 for(const tower of s.towers){const p=pads[tower.pad],st=R.stats(tower,s);let range=st.range;for(const ally of s.towers){if(ally.type==='signal'&&ally.level===3&&ally.branch===1&&Math.hypot(p.x-pads[ally.pad].x,p.y-pads[ally.pad].y)<=R.stats(ally,s).range)range=st.range*1.25;}const target=R.targets(s,tower,range)[0];this.weapons.aim(tower,p,target?R.position(s.map,target.d,target.route):null,dt,this.motion);}
 const entities=s.towers.map(t=>({y:pads[t.pad].y,draw:()=>this.tower(t,pads[t.pad],s.time)}));s.enemies.filter(e=>e.hp>0).forEach(e=>{const p=R.position(s.map,e.d,e.route);entities.push({y:p.y,draw:()=>this.enemy(e,p,s.time)});});this.ghosts=this.ghosts.filter(g=>g.until>this.visualTime);for(const g of this.ghosts)entities.push({y:g.p.y,draw:()=>this.enemy(g.e,g.p,s.time)});entities.sort((a,b)=>a.y-b.y).forEach(e=>e.draw());
 const end=R.position(s.map,R.geometry(s.map).length);this.beacon(end,s.time,s.hp/s.maxHp);
 this.effects.forEach(e=>{const before=e.age;e.age+=dt;if(e.type==='impact'&&before<0&&e.age>=0)this.onImpact?.(e.tower);if(e.age>=0)this.effect(e);});this.previous=s.enemies.filter(e=>e.hp>0).map(e=>({e:{...e},p:R.position(s.map,e.d,e.route)}));for(const [id,h] of this.delayedHp){if(h.until<this.visualTime)this.delayedHp.delete(id);}this.effects=this.effects.filter(e=>e.age<e.duration);
 if(this.aim){c.fillStyle='#082a3a44';c.fillRect(0,0,1000,1000);c.strokeStyle='#ffe0a1';c.lineWidth=3;for(const e of s.enemies){const p=R.position(s.map,e.d,e.route);c.beginPath();c.arc(p.x,p.y,27,0,Math.PI*2);c.stroke();}}
 }
 ambient(time){if(!this.motion)return;const c=this.ctx;c.save();c.lineWidth=1.4;for(let i=0;i<(this.water||[]).length;i++){const p=this.water[i],phase=(time*.22+i*.37)%1;c.globalAlpha=Math.sin(phase*Math.PI)*.22;c.strokeStyle='#c5edf2';c.beginPath();c.ellipse(p.x+phase*9,p.y+phase*4,9+phase*8,2+phase*2,-.1,0,Math.PI);c.stroke();}c.restore();}
 tidalPath(s){const entry=R.routeEntry(s.map);if(!entry)return;const c=this.ctx,wave=s.phase==='build'?s.wave+1:s.wave,active=R.routesForWave(s.map,wave).includes(entry.key),g=R.geometry(s.map,entry.key),point=d=>R.position(s.map,d,entry.key);let bridge=0;for(let i=1;i<entry.points.length;i++)bridge+=Math.hypot(entry.points[i][0]-entry.points[i-1][0],entry.points[i][1]-entry.points[i-1][1]);c.save();const from=point(0),to=point(bridge),pontoon=this.images.pontoon;if(pontoon){c.save();c.translate((from.x+to.x)/2,(from.y+to.y)/2);c.rotate(Math.atan2(to.y-from.y,to.x-from.x));c.drawImage(pontoon,-bridge/2-5,-29,bridge+10,58);c.restore();}c.globalAlpha=active?.8:.18;c.strokeStyle='#83e9ef';c.lineWidth=3;c.setLineDash([12,16]);c.lineDashOffset=this.motion?-s.time*22:0;c.beginPath();for(let d=0;d<g.length;d+=12){const p=point(d);if(!d)c.moveTo(p.x,p.y);else c.lineTo(p.x,p.y);}c.stroke();c.setLineDash([]);const p=point(0),x=p.x>500?p.x-32:p.x+32;c.fillStyle='#072f37';c.beginPath();c.roundRect(x-51,p.y+28,102,25,6);c.fill();c.fillStyle='#c4f5f4';c.font='bold 13px Arial';c.textAlign='center';c.fillText(active?'ПРИЧАЛ ОТКРЫТ':'ПРИЧАЛ ЗАКРЫТ',x,p.y+45);c.restore();}
 tower(t,p,time){const c=this.ctx,im=this.renderImages?.[t.type]||this.images[t.type];c.save();if(t.pad===this.selected){c.shadowColor='#fee7a3';c.shadowBlur=18;}if(['mortar','ballista'].includes(t.type)){this.weapons.draw(c,t,p,this.motion,time);}else if(im){const flash=this.weapons.unit(t).flash/.13,pulse=this.motion?Math.sin(time*3+t.pad)*.015+flash*.03:0;c.drawImage(im,p.x-72,p.y-110-pulse*100,144,144);if(this.motion&&['tide','storm','fire'].includes(t.type)){const g=c.createRadialGradient(p.x,p.y-66,2,p.x,p.y-66,36);g.addColorStop(0,t.type==='fire'?'#ffb94466':'#71dfff66');g.addColorStop(1,'#71dfff00');c.fillStyle=g;c.globalCompositeOperation='screen';c.fillRect(p.x-36,p.y-102,72,72);c.globalCompositeOperation='source-over';}}else{c.fillStyle='#bda36b';c.fillRect(p.x-20,p.y-50,40,60);}if(t.level>=2&&!['mortar','ballista'].includes(t.type)){const n=t.level===3?(t.type==='storm'?(t.branch===0?5:1):t.branch===0?3:5):2;c.strokeStyle=t.type==='fire'?'#ffcb76':'#b9edeb';c.lineWidth=2;for(let i=0;i<n;i++){const angle=i*Math.PI*2/n+(this.motion?time*.4:0),x=p.x+Math.cos(angle)*43,y=p.y-28+Math.sin(angle)*16;c.beginPath();c.moveTo(x,y);c.lineTo(x,y-18);c.stroke();c.fillStyle='#ffdf99';c.beginPath();c.arc(x,y-18,4,0,Math.PI*2);c.fill();}}c.restore();c.fillStyle='#102e2de6';c.beginPath();c.roundRect(p.x-20,p.y+20,40,19,7);c.fill();c.fillStyle='#fbe3ad';c.textAlign='center';c.font='bold 15px Georgia';c.fillText(['','I','II','III'][t.level],p.x,p.y+34);}
 enemy(e,p,time,death=0){const hold=this.delayedHp.get(e.id);if(hold&&hold.until>this.visualTime)e={...e,hp:hold.hp};const c=this.ctx,boss=e.type==='boss',size=boss?112:e.type==='crab'?83:82,im=this.images[e.type+'-walk'],frames=this.spriteFrames?.[e.type+'-walk'];const step=this.motion?Math.floor(time*(e.type==='runner'?11:7)+e.id)%4:0;
 const next=R.position(this.map,e.d+8,e.route),flip=next.x<p.x?-1:1;
 c.fillStyle='#12252160';c.beginPath();c.ellipse(p.x,p.y+5,size*.27,size*.09,0,0,Math.PI*2);c.fill();c.save();c.translate(p.x,p.y+7);c.scale(flip,1);if(death){c.rotate(death*.9);c.globalAlpha=1-death;}
 const hit=this.effects.some(f=>f.type==='hit'&&f.id===e.id&&f.age>=0&&f.age<f.duration);if(im&&frames){const q=frames[step],w=size*q.w/q.h,tile=this.spriteTiles?.[e.type+'-walk']?.[step]?.[hit?1:0];if(tile)c.drawImage(tile,-w/2,-size,w,size);else c.drawImage(im,q.x,q.y,q.w,q.h,-w/2,-size,w,size);}else if(this.images[e.type]||this.images.raider)c.drawImage(this.images[e.type]||this.images.raider,-size/2,-size,size,size);c.restore();if(death)return;
 if(e.wet>0){c.strokeStyle='#70e3ff';c.lineWidth=3;c.beginPath();c.ellipse(p.x,p.y+8,24,8,0,0,Math.PI*2);c.stroke();}
 if(e.broken>0){c.strokeStyle='#ffcd83';c.lineWidth=3;for(const dx of [-1,1]){c.beginPath();c.moveTo(p.x+dx*22,p.y-38);c.lineTo(p.x+dx*27,p.y-26);c.lineTo(p.x+dx*35,p.y-31);c.stroke();}}
 if(e.burn>0){for(let i=0;i<3;i++){const x=p.x+(i-1)*10,h=15+(this.motion?Math.sin(time*19+i)*6:0);c.fillStyle=i===1?'#ffe0a0':'#fa9e42';c.beginPath();c.moveTo(x-5,p.y);c.quadraticCurveTo(x+7,p.y-h,x,p.y-h-8);c.quadraticCurveTo(x-11,p.y-h,x-5,p.y);c.fill();}}
 if(boss&&(e.charge>0||e.shield>0)){c.save();c.strokeStyle=e.shield>0?'#a5dfff':'#ffcf70';c.fillStyle=e.shield>0?'#79bdff18':'#ffc56212';c.lineWidth=e.shield>0?4:2;c.beginPath();c.ellipse(p.x,p.y-size*.45,size*.55,size*.66,0,0,Math.PI*2);c.fill();c.stroke();c.font='bold 16px Arial';c.textAlign='center';c.fillStyle=e.shield>0?'#d6f5ff':'#ffdf9e';c.fillText(e.shield>0?'ЩИТ':'ЩИТ ЧЕРЕЗ '+Math.ceil(1.5-e.charge)+' с',p.x,p.y-size-16);c.restore();}
 const w=boss?80:43,y=p.y-size-3;c.fillStyle='#102928';c.fillRect(p.x-w/2-1,y-1,w+2,7);c.fillStyle=boss?'#e6a2f6':'#ea7668';c.fillRect(p.x-w/2,y,w*Math.max(0,e.hp/e.maxHp),5);
 }
 beacon(p,time,health){const c=this.ctx;if(this.images.beacon){c.drawImage(this.renderImages?.beacon||this.images.beacon,p.x-65,p.y-110,130,130);return;}c.save();c.translate(p.x,p.y);c.shadowColor='#17221ccc';c.shadowBlur=12;c.fillStyle='#e7d4a3';c.beginPath();c.moveTo(-25,14);c.lineTo(-16,-68);c.lineTo(18,-68);c.lineTo(30,14);c.closePath();c.fill();c.shadowBlur=0;c.fillStyle='#976d35';c.fillRect(-23,-70,45,8);c.fillStyle='#0e656d';c.fillRect(-5,-48,12,25);c.fillStyle='#163d44';c.beginPath();c.moveTo(-28,-76);c.lineTo(0,-105);c.lineTo(29,-76);c.fill();const g=c.createRadialGradient(0,-73,1,0,-73,80);g.addColorStop(0,'#fff5b5cc');g.addColorStop(1,'#ffda6d00');c.fillStyle=g;c.fillRect(-80,-153,160,160);c.fillStyle='#fff3ac';c.fillRect(-13,-81,26,12);c.restore();}
 effect(e){const c=this.ctx,p=e.age/e.duration;c.save();c.globalAlpha=1-p;if(e.type==='shot'){
 const color={ballista:'#fff0ba',mortar:'#ffb951',tide:'#8feaff',storm:'#b3f8ff',fire:'#ffb044'}[e.tower]||'#fff';c.strokeStyle=color;c.fillStyle=color;c.globalAlpha=1;
 if(e.tower==='storm'){c.shadowColor='#80dcff';c.shadowBlur=14;c.lineWidth=3;for(const q of e.targets){c.beginPath();c.moveTo(e.from.x,e.from.y);for(let i=1;i<=7;i++){const f=i/7;c.lineTo(e.from.x+(q.x-e.from.x)*f+(i<7?Math.sin(i*13+e.age*80)*8:0),e.from.y+(q.y-e.from.y)*f);}c.stroke();}}
 else{const x=e.from.x+(e.to.x-e.from.x)*p,y=e.from.y+(e.to.y-e.from.y)*p-(e.tower==='mortar'?Math.sin(p*Math.PI)*85:0);c.shadowColor=color;c.shadowBlur=10;const trail=.08,prev=Math.max(0,p-trail),px=e.from.x+(e.to.x-e.from.x)*prev,py=e.from.y+(e.to.y-e.from.y)*prev-(e.tower==='mortar'?Math.sin(prev*Math.PI)*85:0);c.lineWidth=e.tower==='ballista'?2:4;c.beginPath();c.moveTo(px,py);c.lineTo(x,y);c.stroke();c.beginPath();c.arc(x,y,e.tower==='mortar'?5:2,0,Math.PI*2);c.fill();}
 }else if(e.type==='death'){this.enemy(e.e,{x:e.x,y:e.y},this.state.time,p);}else if(e.type==='combo'){c.strokeStyle=e.kind==='water'?'#96eaff':'#ffcd83';c.lineWidth=3;c.beginPath();c.ellipse(e.x,e.y,20+p*25,8+p*12,0,0,Math.PI*2);c.stroke();c.fillStyle=c.strokeStyle;c.font='bold 17px Arial';c.textAlign='center';c.fillText(e.kind==='water'?'+50%':'−БРОНЯ',e.x+30,e.y-48-p*16);}else if(e.type==='impact'){const radius=e.radius*(.2+p*.8),g=c.createRadialGradient(e.x,e.y,1,e.x,e.y,Math.max(2,radius));g.addColorStop(0,'#fff7cdcc');g.addColorStop(.22,e.color+'bb');g.addColorStop(1,e.color+'00');c.fillStyle=g;c.fillRect(e.x-radius,e.y-radius,radius*2,radius*2);for(let i=0;i<12;i++){const a=i*2.399,r=radius*(.5+(i%3)*.15);c.fillStyle=i%2?'#f7df9a':'#82562c';c.beginPath();c.arc(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r*.7-p*(1-p)*38,Math.max(.4,3*(1-p)),0,Math.PI*2);c.fill();}}
 else if(e.type==='smoke'){c.globalAlpha=(1-p)*.32;for(let i=0;i<5;i++){const r=6+p*15,cx=e.x+Math.sin(i*3)*p*21,cy=e.y-p*35-i*3;const g=c.createRadialGradient(cx,cy,0,cx,cy,r);g.addColorStop(0,'#c8c3ae');g.addColorStop(1,'#a9aa9a00');c.fillStyle=g;c.fillRect(cx-r,cy-r,r*2,r*2);}}
 else if(e.type==='kill'){c.fillStyle='#fff0b0';c.textAlign='center';c.font='bold 19px Georgia';c.fillText('+'+e.gold,e.x,e.y-25-p*28);}else if(e.type==='meteor'){c.fillStyle='#ffad4222';c.strokeStyle='#ffd982';c.lineWidth=8*(1-p);c.beginPath();c.arc(e.x,e.y,135*Math.min(1,p*3),0,Math.PI*2);c.fill();c.stroke();for(let i=0;i<12;i++){const a=i*Math.PI/6;c.fillStyle='#ffdf96';c.fillRect(e.x+Math.cos(a)*p*135,e.y+Math.sin(a)*p*135,6,6);}}else if(e.type==='tide'){c.strokeStyle='#a0f8ff';c.lineWidth=22;c.beginPath();c.arc(500,500,p*850,0,Math.PI*2);c.stroke();}else if(e.type==='build'){const q=R.pads(this.map)[e.pad];c.strokeStyle='#ffecac';c.lineWidth=4;c.beginPath();c.ellipse(q.x,q.y,35+p*55,22+p*35,0,0,Math.PI*2);c.stroke();}else if(e.type==='heal'){c.fillStyle='#bdffc6';c.font='26px Arial';c.fillText('+',e.x,e.y-30*p);}else if(e.type==='leak'){c.strokeStyle='#ff8d7a';c.lineWidth=14;c.strokeRect(7,7,986,986);}c.restore();}
}
window.BastionField=BastionField;
})();
