/* Правила «Бастиона прилива». Одинаковый фиксированный шаг в игре и проверках. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Bastion=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const VERSION=1, STEP=1/30;
const Campaign=typeof module==='object'&&module.exports?require('./бастион-кампания.js'):globalThis.BastionCampaign;
const PRIORITIES=['first','strong','armor'];
function metrics(s){return s.metrics||(s.metrics={kills:{},leaks:{},damage:{},combos:{}});}
function priority(s,pad,value){const t=s.towers.find(t=>t.pad===pad);if(!playable(s)||!t||t.type==='signal'||!PRIORITIES.includes(value))return false;t.priority=value;return true;}
function targets(s,t,range){const p=pads(s.map)[t.pad],mode=t.priority||'first';return s.enemies.filter(e=>e.hp>0&&dist(p,position(s.map,e.d,e.route))<=range).sort((a,b)=>(mode==='strong'?b.hp-a.hp:mode==='armor'?ENEMIES[b.type].armor-ENEMIES[a.type].armor:0)||(geometry(s.map,a.route).length-a.d)-(geometry(s.map,b.route).length-b.d)||a.id-b.id);}
function briefing(s){return Campaign.briefing(s.map,Math.min(8,s.wave+(s.phase==='build'?1:0)));}
const DIFFICULTIES={easy:{name:'Спокойный',hp:.78,gold:330},normal:{name:'Тактический',hp:1,gold:290},hard:{name:'Штормовой',hp:1.25,gold:270}};
const TOWERS={
 ballista:{name:'Баллиста',cost:70,damage:24,rate:.8,range:235,unlock:0,tip:'Точный дальний выстрел. Надёжна против быстрых целей.',branches:[['Тяжёлый арбалет','Пробивает броню · урон ×1,9'],['Батарея','Выстрелы вдвое чаще']]},
 mortar:{name:'Мортира',cost:100,damage:48,rate:2.1,range:245,splash:90,unlock:0,tip:'Взрыв по группе. Поставьте рядом с замедлением.',branches:[['Осадное орудие','Снимает броню на 4 с · урон ×1,5'],['Кассетный залп','Радиус взрыва ×1,6']]},
 tide:{name:'Прилив',cost:65,damage:7,rate:1,range:185,unlock:0,tip:'Замедляет и смачивает врагов. Вода усиливает молнию.',branches:[['Глубина','Замедление 65% вместо 45%'],['Большой прилив','Замедляет всю группу в радиусе 95']]},
 storm:{name:'Грозовая катушка',cost:110,damage:24,rate:1.2,range:210,unlock:2,tip:'Молния по трём целям. Мокрые враги получают +50% урона.',branches:[['Цепная буря','Молния по пяти целям'],['Разряд','Урон ×2 против одиночной цели']]},
 fire:{name:'Жаровня',cost:90,damage:13,rate:1.1,range:185,unlock:4,tip:'Поджигает группу на 3 секунды. Огонь обходит броню.',branches:[['Вечный огонь','Горение вдвое сильнее'],['Вспышка','Взрыв при попадании · урон ×2']]},
 signal:{name:'Сигнальная башня',cost:80,damage:0,rate:1,range:205,unlock:6,tip:'Ускоряет соседние башни на 20%. Эффекты нескольких сигналов не складываются.',branches:[['Боевой ритм','Ускорение соседей до 40%'],['Дальний дозор','Дальность соседей +25%']]}
};
const ENEMIES={raider:{name:'Налётчик',hp:55,speed:70,armor:0,gold:8,leak:1},runner:{name:'Разведчик',hp:38,speed:120,armor:0,gold:8,leak:1},crab:{name:'Бронекраб',hp:135,speed:49,armor:.5,gold:14,leak:2},shield:{name:'Щитоносец',hp:105,speed:62,armor:.3,gold:12,leak:2},healer:{name:'Хранитель',hp:85,speed:56,armor:0,gold:15,leak:2},boss:{name:'Повелитель шторма',hp:900,speed:37,armor:.25,gold:100,leak:8}};
const MAPS=[
 ['Тихая гавань','Лазурный берег',[[80,180],[805,180],[805,400],[220,400],[220,660],[815,660],[815,850]],'Одна дорога. Баллиста, мортира и прилив — ваше первое сочетание.'],
 ['Каменная коса','Лазурный берег',[[95,190],[410,190],[410,390],[810,390],[810,630],[250,630],[250,835],[810,835]],'Два длинных поворота. Мортира особенно сильна внутри изгиба.'],
 ['Мыс молний','Лазурный берег',[[90,200],[760,200],[760,450],[250,450],[250,760],[820,760]],'Открыта грозовая катушка. Мокрые враги уязвимы к молнии.'],
 ['Врата архипелага','Лазурный берег',[[120,100],[120,370],[710,370],[710,590],[320,590],[320,820],[840,820]],'Босс на восьмой волне. Сохраняйте удар маяка для тяжёлых целей.'],
 ['Янтарный залив','Штормовые воды',[[85,230],[740,230],[740,475],[200,475],[200,770],[850,770]],'Открыта жаровня. Огонь проходит сквозь броню.'],
 ['Расколотый риф','Штормовые воды',[[100,130],[460,130],[460,340],[810,340],[810,620],[275,620],[275,850],[820,850]],'Быстрые разведчики на смену броне. Держите дальний рубеж.'],
 ['Сигнальный мыс','Штормовые воды',[[110,150],[780,150],[780,380],[300,380],[300,600],[760,600],[760,830]],'Открыта сигнальная башня. Поддержка усиливает целый узел обороны.'],
 ['Око бури','Штормовые воды',[[100,210],[680,210],[680,430],[200,430],[200,700],[820,700],[820,870]],'Хранители лечат союзников. Уничтожайте группу взрывами.'],
 ['Чёрный причал','Последний рубеж',[[110,140],[360,140],[360,390],[800,390],[800,650],[250,650],[250,830],[850,830]],'Броня и скорость в одной волне. Комбинируйте роли башен.'],
 ['Утёс стражей','Последний рубеж',[[90,200],[820,200],[820,480],[250,480],[250,780],[820,780]],'Длинная дорога даёт огню время раскрыться.'],
 ['Последний пролив','Последний рубеж',[[140,100],[140,340],[720,340],[720,600],[280,600],[280,840],[820,840]],'С третьей волны вход чередуется. Западный причал открывает короткий путь к маяку — держите второй рубеж.'],
 ['Сердце прилива','Последний рубеж',[[100,190],[790,190],[790,420],[225,420],[225,690],[810,690],[810,865]],'Финальная оборона с двух причалов одновременно. Перекрёстный огонь важнее обороны одного входа.']
].map((m,id)=>({id,name:m[0],region:m[1],path:m[2],tip:m[3],waves:8}));
// Маршруты обведены по песчаной дороге художественных карт. Каждая область
// имеет обычную/зеркальную планировку и два направления нападения.
const ART_MAPS=[
 {skin:'island-a',path:[[150,125],[190,159],[285,184],[325,225],[405,247],[535,248],[598,285],[634,318],[702,344],[690,385],[643,430],[550,459],[475,466],[425,490],[393,532],[352,568],[354,603],[393,626],[467,646],[535,670],[560,712],[648,740],[742,766],[813,807],[860,840]],pads:[[470,195],[286,326],[565,406],[763,488],[240,555],[528,563],[440,720],[700,680]]},
 {skin:'island-b',path:[[150,140],[210,173],[285,200],[360,224],[454,221],[534,210],[592,219],[617,258],[655,303],[731,330],[768,360],[759,395],[712,430],[659,451],[595,449],[520,447],[445,435],[389,429],[337,456],[285,494],[279,535],[308,572],[360,604],[435,650],[520,667],[606,660],[677,654],[732,674],[780,708],[830,760],[883,820]],pads:[[387,137],[382,318],[690,263],[520,362],[787,465],[196,427],[401,552],[635,570],[605,765]]},
 {skin:'island-c',path:[[150,143],[184,180],[260,206],[310,240],[350,265],[445,273],[535,272],[593,296],[638,337],[700,368],[706,401],[673,430],[610,460],[534,477],[455,474],[386,490],[321,530],[276,573],[280,610],[328,639],[414,661],[516,670],[629,697],[723,734],[803,790],[860,830]],pads:[[411,188],[337,354],[568,398],[725,521],[196,504],[435,595],[580,578],[653,790]]}
];
function smoothPath(points){const out=[];for(let i=0;i<points.length-1;i++){const a=points[Math.max(0,i-1)],b=points[i],c=points[i+1],d=points[Math.min(points.length-1,i+2)];for(let j=0;j<6;j++){const t=j/6,t2=t*t,t3=t2*t;out.push([0,1].map(k=>.5*((2*b[k])+(-a[k]+c[k])*t+(2*a[k]-5*b[k]+4*c[k]-d[k])*t2+(-a[k]+3*b[k]-3*c[k]+d[k])*t3)));}}out.push(points.at(-1));return out;}
MAPS.forEach(m=>{const art=ART_MAPS[Math.floor(m.id/4)],mirror=m.id%2===1;const transform=p=>[mirror?1000-p[0]:p[0],p[1]];m.skin=art.skin;m.mirror=mirror;m.path=smoothPath(art.path.map(transform));if(m.id%4>=2)m.path.reverse();m.pads=art.pads.map(p=>{const q=transform(p);return {x:q[0],y:q[1]};});});
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),geometryCache={},padsCache={};
function routeEntry(map){if(map===7)return {key:'tide',name:'Морской настил',points:[[920,555],[860,550],[790,545],[721,535]]};if(map===10)return {key:'flank',name:'Западный причал',points:[[80,555],[150,560],[215,569],[276,573]]};if(map===11)return {key:'flank',name:'Восточный причал',points:[[920,555],[850,560],[785,569],[724,573]]};return null;}
function routeFor(map,wave,spawnIndex=0){if(map===7&&wave>=4&&wave%2===0)return 'tide';if(map===10&&wave>=3&&wave%2===1)return 'flank';if(map===11&&wave>=3&&spawnIndex%2===1)return 'flank';return 'main';}
function routesForWave(map,wave){return map===11&&wave>=3?['main','flank']:[routeFor(map,wave)];}
function routePath(map,route='main'){const entry=routeEntry(map);if(entry&&route===entry.key){const end=entry.points.at(-1),path=MAPS[map].path,join=path.findIndex(p=>Math.hypot(p[0]-end[0],p[1]-end[1])<.01);return smoothPath(entry.points).concat(path.slice(join+1));}return MAPS[map].path;}
function geometry(map,route='main'){const key=map+':'+route;if(geometryCache[key])return geometryCache[key];const points=routePath(map,route);let length=0;const segments=[];for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i],n=Math.hypot(b[0]-a[0],b[1]-a[1]);segments.push({a,b,start:length,length:n});length+=n;}return geometryCache[key]={segments,length};}
function position(map,d,route='main'){const g=geometry(map,route);d=Math.max(0,Math.min(g.length,d));let lo=0,hi=g.segments.length-1;while(lo<hi){const mid=(lo+hi)>>1;if(d>g.segments[mid].start+g.segments[mid].length)lo=mid+1;else hi=mid;}const s=g.segments[lo];const k=(d-s.start)/s.length;return {x:s.a[0]+(s.b[0]-s.a[0])*k,y:s.a[1]+(s.b[1]-s.a[1])*k};}
function pads(map){return MAPS[map].pads;}
function create(map=0,difficulty='normal',preparation='none'){if(!Number.isInteger(map)||!MAPS[map]||!Object.hasOwn(DIFFICULTIES,difficulty))throw Error('Неверная карта или сложность');if(!['none','hull','supply','optics'].includes(preparation))preparation='none';const hp=preparation==='hull'?24:20;return {version:VERSION,map,difficulty,preparation,phase:'build',time:0,wave:0,hp,maxHp:hp,gold:DIFFICULTIES[difficulty].gold+(preparation==='supply'?40:0),towers:[],enemies:[],queue:[],spawnClock:0,nextId:1,kills:0,leaks:0,cooldowns:{meteor:0,tide:0},metrics:{kills:{},leaks:{},damage:{},combos:{}},events:[]};}
function available(map){return Object.keys(TOWERS).filter(k=>TOWERS[k].unlock<=map);}
function stats(t,s){const def=TOWERS[t.type],l=t.level;const v={...def,damage:def.damage*(l===1?1:l===2?1.6:2),range:def.range+(l-1)*12,rate:def.rate,splash:def.splash||0,slow:.45,chain:3,burn:10,buff:1.2,pierce:false};if(s?.preparation==='optics')v.range*=1.1;if(l===3){const b=t.branch;if(t.type==='ballista'){if(b===0){v.damage*=1.9;v.pierce=true;}else v.rate*=.5;}if(t.type==='mortar'){if(b===0)v.damage*=1.5;else v.splash*=1.6;}if(t.type==='tide'){if(b===0)v.slow=.65;else v.splash=95;}if(t.type==='storm'){if(b===0)v.chain=5;else{v.chain=1;v.damage*=2;}}if(t.type==='fire'){if(b===0)v.burn=20;else{v.damage*=2;v.splash=90;}}if(t.type==='signal'&&b===0)v.buff=1.4;}return v;}
function upgradeCost(t){return Math.round(TOWERS[t.type].cost*(t.level===1?1.15:1.7));}
function playable(s){return s.phase==='build'||s.phase==='wave';}
function emit(s,e){s.events.push(e);if(s.events.length>80)s.events.shift();}
function build(s,pad,type){if(!playable(s)||!Number.isInteger(pad)||!pads(s.map)[pad]||!available(s.map).includes(type)||s.towers.some(t=>t.pad===pad)||s.gold<TOWERS[type].cost)return false;s.gold-=TOWERS[type].cost;s.towers.push({pad,type,level:1,branch:null,cooldown:0,spent:TOWERS[type].cost});emit(s,{type:'build',pad});return true;}
function upgrade(s,pad,branch=null){const t=s.towers.find(x=>x.pad===pad);if(!playable(s)||!t||t.level>=3||(t.level===2&&branch!==0&&branch!==1)||s.gold<upgradeCost(t))return false;const cost=upgradeCost(t);s.gold-=cost;t.spent+=cost;t.level++;if(t.level===3)t.branch=branch;emit(s,{type:'build',pad});return true;}
function sellValue(s,t){return Math.floor(t.spent*(s.wave===0?1:.7));}
function sell(s,pad){const i=s.towers.findIndex(t=>t.pad===pad);if(!playable(s)||i<0)return false;s.gold+=sellValue(s,s.towers[i]);s.towers.splice(i,1);return true;}
function waveList(map,wave){return Campaign.wave(map,wave);}
function preview(s){const list=waveList(s.map,Math.min(8,s.wave+1));const counts={};list.forEach(k=>counts[k]=(counts[k]||0)+1);return counts;}
function startWave(s){if(s.phase!=='build'||s.wave>=8)return false;s.wave++;s.phase='wave';s.queue=waveList(s.map,s.wave);s.spawnClock=0;emit(s,{type:'wave',wave:s.wave});return true;}
function damage(s,e,n,pierce=false,source=null){if(e.hp<=0)return;const armor=pierce||e.broken>0?0:ENEMIES[e.type].armor,before=e.hp;const shield=e.type==='boss'&&(e.shield||0)>0?.5:1;e.hp=Math.max(0,e.hp-n*(1-armor)*shield);const m=metrics(s);if(source)m.damage[source.pad]=(m.damage[source.pad]||0)+(before-e.hp);if(e.hp===0){s.gold+=ENEMIES[e.type].gold;s.kills++;m.kills[e.type]=(m.kills[e.type]||0)+1;emit(s,{type:'kill',id:e.id,enemy:e.type,...position(s.map,e.d,e.route),gold:ENEMIES[e.type].gold});}}
function cast(s,kind,point){if(s.phase!=='wave'||!['meteor','tide'].includes(kind)||s.cooldowns[kind]>0)return false;if(kind==='meteor'&&(!point||!Number.isFinite(point.x)||!Number.isFinite(point.y)||point.x<0||point.x>1000||point.y<0||point.y>1000))return false;s.cooldowns[kind]=kind==='meteor'?28:34;if(kind==='meteor'){s.enemies.forEach(e=>{if(dist(position(s.map,e.d,e.route),point)<=135)damage(s,e,150*(1+s.map*.09),true);});emit(s,{type:'meteor',...point});}else{s.enemies.forEach(e=>{e.slow=Math.max(e.slow,3.5);e.slowPower=Math.max(e.slowPower,.7);e.wet=Math.max(e.wet,5);});emit(s,{type:'tide'});}return true;}
function tick(s,dt=STEP){s.events=[];if(s.phase!=='wave')return;dt=Math.min(.1,Math.max(0,dt));if(!Number.isFinite(dt))return;s.time+=dt;Object.keys(s.cooldowns).forEach(k=>s.cooldowns[k]=Math.max(0,s.cooldowns[k]-dt));s.spawnClock=Math.max(0,s.spawnClock-dt);if(s.queue.length&&s.spawnClock<=0){const type=s.queue.shift(),def=ENEMIES[type],factor=(1+(s.wave-1)*.13+s.map*.085)*DIFFICULTIES[s.difficulty].hp;const hp=def.hp*factor;s.enemies.push({id:s.nextId++,type,hp,maxHp:hp,route:routeFor(s.map,s.wave,s.nextId-1),d:0,slow:0,slowPower:0,wet:0,burn:0,burnDamage:0,broken:0,heal:2,stormClock:8,shield:0,charge:0});s.spawnClock=type==='boss'?2:Math.max(.55,1.1-s.wave*.035);}
 const ps=pads(s.map);
 for(const e of s.enemies){if(e.hp<=0)continue;if(e.type==='boss'){e.stormClock=(e.stormClock??8)-dt;e.shield=Math.max(0,(e.shield||0)-dt);e.charge=e.stormClock<=1.5&&e.stormClock>0?1.5-e.stormClock:0;if(e.stormClock<=0){e.shield=3;e.stormClock=10;emit(s,{type:'boss-shield',id:e.id,...position(s.map,e.d,e.route)});}}for(const k of ['slow','wet','burn','broken'])e[k]=Math.max(0,e[k]-dt);if(e.slow===0)e.slowPower=0;if(e.burn>0)damage(s,e,e.burnDamage*dt,true);if(e.hp<=0)continue;if(e.type==='healer'){e.heal-=dt;if(e.heal<=0){e.heal=2;s.enemies.forEach(a=>{if(a.hp>0&&dist(position(s.map,a.d,a.route),position(s.map,e.d,e.route))<130)a.hp=Math.min(a.maxHp,a.hp+a.maxHp*.045);});emit(s,{type:'heal',...position(s.map,e.d,e.route)});}}e.d+=ENEMIES[e.type].speed*.65*dt*(e.slow>0?1-e.slowPower:1);const end=geometry(s.map,e.route).length;if(e.d>=end){e.d=end;e.hp=0;s.leaks++;const m=metrics(s);m.leaks[e.type]=(m.leaks[e.type]||0)+1;s.hp=Math.max(0,s.hp-ENEMIES[e.type].leak);emit(s,{type:'leak',...position(s.map,end)});if(s.hp===0){s.phase='lost';emit(s,{type:'lost'});return;}}}
 for(const t of s.towers){if(t.type==='signal')continue;const st=stats(t,s),p=ps[t.pad];let speed=1,range=st.range;for(const ally of s.towers){if(ally.type!=='signal')continue;const a=stats(ally,s);if(dist(p,ps[ally.pad])<=a.range){speed=Math.max(speed,a.buff);if(ally.level===3&&ally.branch===1)range=st.range*1.25;}}t.cooldown=Math.max(0,t.cooldown-dt*speed);if(t.cooldown>0)continue;const targetsList=targets(s,t,range);if(!targetsList.length)continue;const target=targetsList[0],tp=position(s.map,target.d,target.route);t.cooldown=st.rate;let hit=[target];if(st.splash)hit=s.enemies.filter(e=>e.hp>0&&dist(tp,position(s.map,e.d,e.route))<=st.splash);if(t.type==='storm')hit=targetsList.slice(0,st.chain);if(t.type==='fire'&&!st.splash)hit=s.enemies.filter(e=>e.hp>0&&dist(tp,position(s.map,e.d,e.route))<=65);
 for(const e of hit){if(t.type==='tide'){e.slow=Math.max(e.slow,2);e.slowPower=Math.max(e.slowPower,st.slow);e.wet=4;}if(t.type==='fire'){e.burn=3;e.burnDamage=st.burn*t.level;}if(t.type==='mortar'&&t.level===3&&t.branch===0)e.broken=4;if(t.type==='storm'&&e.wet>0){metrics(s).combos.water=(metrics(s).combos.water||0)+1;emit(s,{type:'combo',kind:'water',...position(s.map,e.d,e.route)});}if(t.type==='mortar'&&t.level===3&&t.branch===0)emit(s,{type:'combo',kind:'armor',...position(s.map,e.d,e.route)});damage(s,e,st.damage*(t.type==='storm'&&e.wet>0?1.5:1),st.pierce,t);}
 emit(s,{type:'shot',tower:t.type,level:t.level,branch:t.branch,targetId:target.id,from:p,to:tp,targets:hit.map(e=>position(s.map,e.d,e.route)),splash:st.splash});}
 s.enemies=s.enemies.filter(e=>e.hp>0);if(!s.queue.length&&!s.enemies.length){s.gold+=25+s.wave*4;s.phase=s.wave===8?'won':'build';emit(s,{type:s.phase==='won'?'won':'clear',wave:s.wave});}}
function stars(s){return s.phase!=='won'?0:s.hp===s.maxHp?3:s.hp>=s.maxHp*.75?2:1;}
function snapshot(s){return JSON.stringify({...s,events:[]});}
function restore(raw){try{const s=typeof raw==='string'?JSON.parse(raw):JSON.parse(JSON.stringify(raw));if(!s||s.version!==VERSION||!Number.isInteger(s.map)||!MAPS[s.map]||!Object.hasOwn(DIFFICULTIES,s.difficulty)||!['build','wave','won','lost'].includes(s.phase)||!['none','hull','supply','optics'].includes(s.preparation))return null;
 const num=(n,min,max)=>Number.isFinite(n)&&n>=min&&n<=max;for(const [k,min,max] of [['wave',0,8],['gold',0,1000000],['hp',0,24],['maxHp',20,24],['time',0,100000],['nextId',1,100000],['kills',0,100000],['leaks',0,10000],['spawnClock',-1,3]])if(!num(s[k],min,max))return null;if(!Number.isInteger(s.wave)||s.maxHp!==(s.preparation==='hull'?24:20)||s.hp>s.maxHp)return null;
 if(!Array.isArray(s.towers)||s.towers.length>pads(s.map).length||!Array.isArray(s.enemies)||s.enemies.length>100||!Array.isArray(s.queue)||s.queue.length>100||!s.queue.every(k=>Object.hasOwn(ENEMIES,k)))return null;
 if(s.draft!==undefined){if(!Array.isArray(s.draft)||s.draft.length>pads(s.map).length)return null;const used=new Set();for(const t of s.draft){if(!t||!Number.isInteger(t.pad)||!pads(s.map)[t.pad]||used.has(t.pad)||!available(s.map).includes(t.type))return null;used.add(t.pad);}}if(s.runId!==undefined&&(typeof s.runId!=='string'||s.runId.length>120))return null;
 if(s.metrics){for(const k of ['kills','leaks','damage','combos']){if(!s.metrics[k]||typeof s.metrics[k]!=='object'||Array.isArray(s.metrics[k]))return null;for(const [key,value] of Object.entries(s.metrics[k]))if(!Number.isFinite(value)||value<0||value>1e9||!(k==='damage'?/^[0-9]+$/.test(key)&&+key<pads(s.map).length:k==='combos'?['water','armor'].includes(key):Object.hasOwn(ENEMIES,key)))return null;}}
 const occupied=new Set();for(const t of s.towers){if(!Number.isInteger(t.pad)||!pads(s.map)[t.pad]||occupied.has(t.pad)||!available(s.map).includes(t.type)||![1,2,3].includes(t.level)||(t.level===3?![0,1].includes(t.branch):t.branch!==null)||!num(t.cooldown,-1,10)||!num(t.spent,0,2000))return null;if(t.priority!==undefined&&!PRIORITIES.includes(t.priority))return null;occupied.add(t.pad);let expected=TOWERS[t.type].cost;if(t.level>=2)expected+=upgradeCost({type:t.type,level:1});if(t.level===3)expected+=upgradeCost({type:t.type,level:2});if(t.spent!==expected)return null;}
 const ids=new Set();for(const e of s.enemies){if(!Object.hasOwn(ENEMIES,e.type)||!Number.isInteger(e.id)||e.id<1||e.id>=s.nextId||ids.has(e.id))return null;ids.add(e.id);if(e.route!==undefined&&!['main',routeEntry(s.map)?.key].filter(Boolean).includes(e.route))return null;for(const k of ['stormClock','shield','charge'])if(e[k]!==undefined&&!num(e[k],0,30))return null;for(const k of ['hp','maxHp','d','slow','slowPower','wet','burn','burnDamage','broken','heal'])if(!num(e[k],0,k==='d'?geometry(s.map,e.route).length:100000))return null;if(e.hp>e.maxHp||e.maxHp<=0||e.slowPower>1)return null;}
 if(!s.cooldowns||!num(s.cooldowns.meteor,0,28)||!num(s.cooldowns.tide,0,34))return null;if(s.phase==='wave'&&s.wave===0)return null;if(s.phase==='build'&&(s.enemies.length||s.queue.length||s.wave===8))return null;if(s.phase==='won'&&(s.wave!==8||s.hp<=0||s.enemies.length||s.queue.length))return null;if(s.phase==='lost'&&s.hp!==0)return null;s.events=[];return s;}catch(_){return null;}}
function profile(raw){let p;try{p=typeof raw==='string'?JSON.parse(raw):raw;}catch(_){}const clean={version:1,records:{},preparation:'none',sound:true,motion:true};if(!p||p.version!==1)return clean;for(const [key,r] of Object.entries(p.records||{})){if(!/^\d+:(easy|normal|hard)$/.test(key)||!MAPS[+key.split(':')[0]]||!r||!Number.isInteger(r.stars)||r.stars<1||r.stars>3||!Number.isFinite(r.time)||r.time<0)continue;clean.records[key]={stars:r.stars,time:r.time};}if(['none','hull','supply','optics'].includes(p.preparation))clean.preparation=p.preparation;clean.sound=p.sound!==false;clean.motion=p.motion!==false;return clean;}
function mapStars(p,map){return Math.max(0,...Object.entries(p.records).filter(([k])=>+k.split(':')[0]===map).map(([,r])=>r.stars));}
function unlocked(p){let i=0;while(i<11&&mapStars(p,i)>0)i++;return i;}
function record(p,s){if(s.phase!=='won')return false;const key=s.map+':'+s.difficulty,st=stars(s),prev=p.records[key];if(!prev||st>prev.stars||(st===prev.stars&&s.time<prev.time)){p.records[key]={stars:st,time:s.time};return true;}return false;}
return {VERSION,STEP,PRIORITIES,priority,targets,briefing,Campaign,DIFFICULTIES,TOWERS,ENEMIES,MAPS,routeEntry,routeFor,routesForWave,routePath,geometry,position,pads,create,available,stats,upgradeCost,build,upgrade,sell,sellValue,startWave,preview,waveList,cast,tick,stars,snapshot,restore,profile,mapStars,unlocked,record};
});
