/* Поле: изображения отдельно от правил; эффекты не меняют результат боя. */
(function(){'use strict';const R=window.Bastion;
class BastionField{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.images={};this.effects=[];this.selected=-1;this.aim=false;this.motion=true;this.static=document.createElement('canvas');this.static.width=this.static.height=1000;this.map=-1;this.loaded=false;this.resize=new ResizeObserver(()=>this.fit());this.resize.observe(canvas);}
 async load(){const names=['island-a','island-b','island-c','pad','beacon',...Object.keys(R.TOWERS),'raider','crab','boss'];const result=await Promise.allSettled(names.map(async k=>{const im=new Image();im.src='img/бастион/'+k+'-v1.webp';await im.decode();this.images[k]=im;}));this.loaded=result.every(r=>r.status==='fulfilled');this.map=-1;return this.loaded;}
 fit(){const size=Math.round(this.canvas.getBoundingClientRect().width*Math.min(devicePixelRatio||1,2));if(size>0&&this.canvas.width!==size){this.canvas.width=this.canvas.height=size;}}
 background(map){const c=this.static.getContext('2d'),m=R.MAPS[map];c.clearRect(0,0,1000,1000);c.save();if(m.mirror){c.translate(1000,0);c.scale(-1,1);}if(this.images[m.skin])c.drawImage(this.images[m.skin],0,0,1000,1000);c.restore();for(const p of R.pads(map)){if(this.images.pad)c.drawImage(this.images.pad,p.x-52,p.y-40,104,82);}const p=R.position(map,0);c.fillStyle='#423220';c.fillRect(p.x-19,p.y-52,4,40);c.fillStyle='#692d49';c.beginPath();c.moveTo(p.x-15,p.y-52);c.lineTo(p.x+12,p.y-43);c.lineTo(p.x-15,p.y-30);c.fill();this.map=map;}

 event(e){if(!this.motion&&['shot','kill'].includes(e.type))return;const duration=e.type==='shot'?.36:e.type==='meteor'?.85:e.type==='kill'?.9:e.type==='tide'?1:1.2;this.effects.push({...e,age:0,duration});if(this.effects.length>150)this.effects.splice(0,this.effects.length-150);}
 draw(s,dt){if(!s)return;this.fit();if(this.map!==s.map)this.background(s.map);const c=this.ctx,k=this.canvas.width/1000;c.setTransform(k,0,0,k,0,0);c.clearRect(0,0,1000,1000);c.drawImage(this.static,0,0);const pads=R.pads(s.map),t=s.towers.find(t=>t.pad===this.selected);
 if(this.selected>=0&&pads[this.selected]){const p=pads[this.selected],radius=t?R.stats(t,s).range:210;c.beginPath();c.arc(p.x,p.y,radius,0,Math.PI*2);c.fillStyle='#75e9d21b';c.fill();c.strokeStyle='#bff7d998';c.lineWidth=2;c.setLineDash([7,9]);c.stroke();c.setLineDash([]);}
 for(let i=0;i<pads.length;i++){if(s.towers.some(t=>t.pad===i))continue;const p=pads[i];c.fillStyle=i===this.selected?'#ffffff':'#fff5cc';c.font='bold 35px Georgia';c.textAlign='center';c.fillText('+',p.x,p.y+11);}
 const entities=s.towers.map(t=>({y:pads[t.pad].y,draw:()=>this.tower(t,pads[t.pad])}));s.enemies.filter(e=>e.hp>0).forEach(e=>{const p=R.position(s.map,e.d);entities.push({y:p.y,draw:()=>this.enemy(e,p,s.time)});});entities.sort((a,b)=>a.y-b.y).forEach(e=>e.draw());
 const end=R.position(s.map,R.geometry(s.map).length);this.beacon(end,s.time,s.hp/s.maxHp);
 this.effects.forEach(e=>{e.age+=dt;this.effect(e);});this.effects=this.effects.filter(e=>e.age<e.duration);
 if(this.aim){c.fillStyle='#082a3a44';c.fillRect(0,0,1000,1000);c.strokeStyle='#ffe0a1';c.lineWidth=3;for(const e of s.enemies){const p=R.position(s.map,e.d);c.beginPath();c.arc(p.x,p.y,27,0,Math.PI*2);c.stroke();}}
 }
 tower(t,p){const c=this.ctx,im=this.images[t.type];c.save();if(t.pad===this.selected){c.shadowColor='#fee7a3';c.shadowBlur=18;}if(im)c.drawImage(im,p.x-65,p.y-97,130,130);else{c.fillStyle='#bda36b';c.fillRect(p.x-20,p.y-50,40,60);}c.restore();c.fillStyle='#102e2de6';c.beginPath();c.roundRect(p.x-20,p.y+20,40,19,7);c.fill();c.fillStyle='#fbe3ad';c.textAlign='center';c.font='bold 15px Georgia';c.fillText(['','I','II','III'][t.level],p.x,p.y+34);}
 enemy(e,p,time){const c=this.ctx,boss=e.type==='boss',size=boss?87:e.type==='crab'?61:52,im=this.images[boss?'boss':e.type==='crab'?'crab':'raider'];const bob=this.motion?Math.sin(time*12+e.id)*1.8:0;c.fillStyle='#18272166';c.beginPath();c.ellipse(p.x,p.y+8,size*.34,size*.13,0,0,Math.PI*2);c.fill();if(im)c.drawImage(im,p.x-size/2,p.y-size*.75+bob,size,size);else{c.fillStyle='#683957';c.beginPath();c.arc(p.x,p.y,14,0,Math.PI*2);c.fill();}if(e.type==='shield'){c.fillStyle='#b9c9ca';c.beginPath();c.moveTo(p.x+6,p.y-12);c.lineTo(p.x+22,p.y-8);c.lineTo(p.x+19,p.y+10);c.lineTo(p.x+10,p.y+16);c.closePath();c.fill();}if(e.type==='healer'){c.fillStyle='#c8f6ac';c.font='bold 21px Arial';c.textAlign='center';c.fillText('+',p.x,p.y-10);}if(e.type==='runner'){c.strokeStyle='#ceefff';c.lineWidth=2;for(let i=0;i<2;i++){c.beginPath();c.moveTo(p.x-24,p.y-4+i*7);c.lineTo(p.x-35,p.y-4+i*7);c.stroke();}}if(e.wet>0){c.strokeStyle='#70e3ff';c.lineWidth=3;c.beginPath();c.ellipse(p.x,p.y+12,20,7,0,0,Math.PI*2);c.stroke();}if(e.burn>0){c.fillStyle='#ffc33a';c.beginPath();c.moveTo(p.x-6,p.y);c.lineTo(p.x+1,p.y-25);c.lineTo(p.x+9,p.y);c.fill();}const w=boss?66:34,y=p.y-size*.8-6;c.fillStyle='#102928';c.fillRect(p.x-w/2-1,y-1,w+2,6);c.fillStyle=boss?'#e6a2f6':'#ea7668';c.fillRect(p.x-w/2,y,w*e.hp/e.maxHp,4);}
 beacon(p,time,health){const c=this.ctx;if(this.images.beacon){c.drawImage(this.images.beacon,p.x-65,p.y-110,130,130);return;}c.save();c.translate(p.x,p.y);c.shadowColor='#17221ccc';c.shadowBlur=12;c.fillStyle='#e7d4a3';c.beginPath();c.moveTo(-25,14);c.lineTo(-16,-68);c.lineTo(18,-68);c.lineTo(30,14);c.closePath();c.fill();c.shadowBlur=0;c.fillStyle='#976d35';c.fillRect(-23,-70,45,8);c.fillStyle='#0e656d';c.fillRect(-5,-48,12,25);c.fillStyle='#163d44';c.beginPath();c.moveTo(-28,-76);c.lineTo(0,-105);c.lineTo(29,-76);c.fill();const g=c.createRadialGradient(0,-73,1,0,-73,80);g.addColorStop(0,'#fff5b5cc');g.addColorStop(1,'#ffda6d00');c.fillStyle=g;c.fillRect(-80,-153,160,160);c.fillStyle='#fff3ac';c.fillRect(-13,-81,26,12);c.restore();}
 effect(e){const c=this.ctx,p=e.age/e.duration;c.save();c.globalAlpha=1-p;if(e.type==='shot'){const colors={ballista:'#fff0ba',mortar:'#ffb951',tide:'#8feaff',storm:'#b3f8ff',fire:'#ffb044'};c.strokeStyle=colors[e.tower]||'#fff';c.fillStyle=c.strokeStyle;c.lineWidth=e.tower==='storm'?4:3;if(e.tower==='storm'){for(const q of e.targets){c.beginPath();c.moveTo(e.from.x,e.from.y-50);c.lineTo((e.from.x+q.x)/2+12,(e.from.y+q.y)/2-14);c.lineTo(q.x,q.y);c.stroke();}}else{const x=e.from.x+(e.to.x-e.from.x)*p,y=e.from.y-45+(e.to.y-e.from.y+45)*p-(e.tower==='mortar'?Math.sin(p*Math.PI)*80:0);c.beginPath();c.arc(x,y,e.tower==='mortar'?8:4,0,Math.PI*2);c.fill();if(p>.65&&e.splash){c.beginPath();c.arc(e.to.x,e.to.y,e.splash*p,0,Math.PI*2);c.stroke();}}}else if(e.type==='kill'){c.fillStyle='#fff0b0';c.textAlign='center';c.font='bold 19px Georgia';c.fillText('+'+e.gold,e.x,e.y-25-p*28);}else if(e.type==='meteor'){c.fillStyle='#ffad4222';c.strokeStyle='#ffd982';c.lineWidth=8*(1-p);c.beginPath();c.arc(e.x,e.y,135*Math.min(1,p*3),0,Math.PI*2);c.fill();c.stroke();for(let i=0;i<12;i++){const a=i*Math.PI/6;c.fillStyle='#ffdf96';c.fillRect(e.x+Math.cos(a)*p*135,e.y+Math.sin(a)*p*135,6,6);}}else if(e.type==='tide'){c.strokeStyle='#a0f8ff';c.lineWidth=22;c.beginPath();c.arc(500,500,p*850,0,Math.PI*2);c.stroke();}else if(e.type==='build'){const q=R.pads(this.map)[e.pad];c.strokeStyle='#ffecac';c.lineWidth=4;c.beginPath();c.ellipse(q.x,q.y,35+p*55,22+p*35,0,0,Math.PI*2);c.stroke();}else if(e.type==='heal'){c.fillStyle='#bdffc6';c.font='26px Arial';c.fillText('+',e.x,e.y-30*p);}else if(e.type==='leak'){c.strokeStyle='#ff8d7a';c.lineWidth=14;c.strokeRect(7,7,986,986);}c.restore();}
}
window.BastionField=BastionField;
})();
