/* Поле: изображения отдельно от правил; эффекты не меняют результат боя. */
(function(){'use strict';const R=window.Bastion;
class BastionField{
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.images={};this.effects=[];this.weapons=new BastionWeapons.Weapons();this.visualTime=0;this.previous=[];this.ghosts=[];this.delayedHp=new Map();this.selected=-1;this.aim=false;this.motion=true;this.static=document.createElement('canvas');this.static.width=this.static.height=1000;this.map=-1;this.loaded=false;this.resize=new ResizeObserver(()=>this.fit());this.resize.observe(canvas);}
 async load(){const names=['island-a','island-b','island-c','pad','beacon',...Object.keys(R.TOWERS),'raider','crab','boss'];const versions=Object.fromEntries(names.map(n=>[n,'v1']));for(const name of ['mortar-overhead','ballista-overhead','weapon-plinth']){names.push(name);versions[name]='v4';}const result=await Promise.allSettled(names.map(async k=>{const im=new Image();im.src='img/бастион/'+k+'-'+versions[k]+'.webp';await im.decode();this.images[k]=im;}));this.weapons.images=this.images;this.loaded=result.every(r=>r.status==='fulfilled');this.map=-1;return this.loaded;}
 fit(){const size=Math.round(this.canvas.getBoundingClientRect().width*Math.min(devicePixelRatio||1,2));if(size>0&&this.canvas.width!==size){this.canvas.width=this.canvas.height=size;}}
 background(map){const c=this.static.getContext('2d'),m=R.MAPS[map];c.clearRect(0,0,1000,1000);c.save();if(m.mirror){c.translate(1000,0);c.scale(-1,1);}if(this.images[m.skin])c.drawImage(this.images[m.skin],0,0,1000,1000);c.restore();for(const p of R.pads(map)){if(this.images.pad)c.drawImage(this.images.pad,p.x-52,p.y-40,104,82);}const p=R.position(map,0);c.fillStyle='#423220';c.fillRect(p.x-19,p.y-52,4,40);c.fillStyle='#692d49';c.beginPath();c.moveTo(p.x-15,p.y-52);c.lineTo(p.x+12,p.y-43);c.lineTo(p.x-15,p.y-30);c.fill();this.map=map;}

 event(e){
 if(e.type==='shot'){
  const pad=R.pads(this.map).findIndex(p=>p.x===e.from.x&&p.y===e.from.y),t=this.state?.towers.find(t=>t.pad===pad);
  const duration=e.tower==='mortar'?.42:e.tower==='ballista'?.24:.2;
  const muzzle=t&&['mortar','ballista'].includes(t.type)?this.weapons.fire(t,e.from,e.to,this.motion):{x:e.from.x,y:e.from.y-70};
  if(this.motion){for(const q of e.targets){for(const g of this.ghosts){if(Math.hypot(g.p.x-q.x,g.p.y-q.y)<9)g.until=Math.max(g.until,this.visualTime+duration);}for(const fx of this.effects){if(fx.type==='kill'&&Math.hypot(fx.x-q.x,fx.y-q.y)<9)fx.age=-duration;}const old=this.previous.find(a=>Math.hypot(a.p.x-q.x,a.p.y-q.y)<9);if(old){const hold=this.delayedHp.get(old.e.id);this.delayedHp.set(old.e.id,{until:Math.max(hold?.until||0,this.visualTime+duration),hp:hold?.hp??old.e.hp});}}
   this.effects.push({...e,from:muzzle,age:0,duration,flight:duration});this.effects.push({type:'impact',...e.to,age:-duration,duration:.55,color:e.tower==='tide'||e.tower==='storm'?'#8fe8ff':'#ffb34a',radius:e.splash||18});
   if(e.tower==='mortar')this.effects.push({type:'smoke',...muzzle,age:0,duration:1.1});
  }if(this.effects.length>200)this.effects.splice(0,this.effects.length-200);return;
 }
 if(e.type==='kill'&&this.motion){const old=this.previous.find(a=>Math.hypot(a.p.x-e.x,a.p.y-e.y)<9);if(old)this.ghosts.push({e:old.e,p:{x:e.x,y:e.y},until:this.visualTime+.32});}
 if(!this.motion&&e.type==='kill')return;
 const duration=e.type==='meteor'?.85:e.type==='kill'?.9:e.type==='tide'?1:1.2;this.effects.push({...e,age:e.type==='kill'?-.32:0,duration});if(this.effects.length>200)this.effects.splice(0,this.effects.length-200);
 }
 draw(s,dt){if(!s)return;this.state=s;this.visualTime+=dt;this.fit();if(this.map!==s.map){this.weapons.reset();this.ghosts=[];this.previous=[];this.delayedHp.clear();this.background(s.map);}const c=this.ctx,k=this.canvas.width/1000;c.setTransform(k,0,0,k,0,0);c.clearRect(0,0,1000,1000);c.drawImage(this.static,0,0);const pads=R.pads(s.map),t=s.towers.find(t=>t.pad===this.selected);
 if(this.selected>=0&&pads[this.selected]){const p=pads[this.selected],radius=t?R.stats(t,s).range:210;c.beginPath();c.arc(p.x,p.y,radius,0,Math.PI*2);c.fillStyle='#75e9d21b';c.fill();c.strokeStyle='#bff7d998';c.lineWidth=2;c.setLineDash([7,9]);c.stroke();c.setLineDash([]);}
 for(let i=0;i<pads.length;i++){if(s.towers.some(t=>t.pad===i))continue;const p=pads[i];c.fillStyle=i===this.selected?'#ffffff':'#fff5cc';c.font='bold 35px Georgia';c.textAlign='center';c.fillText('+',p.x,p.y+11);}
 for(const tower of s.towers){const p=pads[tower.pad],st=R.stats(tower,s);let range=st.range;for(const ally of s.towers){if(ally.type==='signal'&&ally.level===3&&ally.branch===1&&Math.hypot(p.x-pads[ally.pad].x,p.y-pads[ally.pad].y)<=R.stats(ally,s).range)range=st.range*1.25;}const target=s.enemies.filter(e=>e.hp>0).sort((a,b)=>b.d-a.d).find(e=>{const q=R.position(s.map,e.d);return Math.hypot(q.x-p.x,q.y-p.y)<=range+35;});this.weapons.aim(tower,p,target?R.position(s.map,target.d):null,dt,this.motion);}
 const entities=s.towers.map(t=>({y:pads[t.pad].y,draw:()=>this.tower(t,pads[t.pad],s.time)}));s.enemies.filter(e=>e.hp>0).forEach(e=>{const p=R.position(s.map,e.d);entities.push({y:p.y,draw:()=>this.enemy(e,p,s.time)});});this.ghosts=this.ghosts.filter(g=>g.until>this.visualTime);for(const g of this.ghosts)entities.push({y:g.p.y,draw:()=>this.enemy(g.e,g.p,s.time)});entities.sort((a,b)=>a.y-b.y).forEach(e=>e.draw());
 const end=R.position(s.map,R.geometry(s.map).length);this.beacon(end,s.time,s.hp/s.maxHp);
 this.effects.forEach(e=>{e.age+=dt;if(e.age>=0)this.effect(e);});this.previous=s.enemies.filter(e=>e.hp>0).map(e=>({e:{...e},p:R.position(s.map,e.d)}));for(const [id,h] of this.delayedHp){if(h.until<this.visualTime)this.delayedHp.delete(id);}this.effects=this.effects.filter(e=>e.age<e.duration);
 if(this.aim){c.fillStyle='#082a3a44';c.fillRect(0,0,1000,1000);c.strokeStyle='#ffe0a1';c.lineWidth=3;for(const e of s.enemies){const p=R.position(s.map,e.d);c.beginPath();c.arc(p.x,p.y,27,0,Math.PI*2);c.stroke();}}
 }
 tower(t,p,time){const c=this.ctx,im=this.images[t.type];c.save();if(t.pad===this.selected){c.shadowColor='#fee7a3';c.shadowBlur=18;}if(['mortar','ballista'].includes(t.type)){this.weapons.draw(c,t,p,this.motion,time);}else if(im){const pulse=this.motion?Math.sin(time*3+t.pad)*.015:0;c.drawImage(im,p.x-72,p.y-110-pulse*100,144,144);if(this.motion&&['tide','storm','fire'].includes(t.type)){const g=c.createRadialGradient(p.x,p.y-66,2,p.x,p.y-66,36);g.addColorStop(0,t.type==='fire'?'#ffb94466':'#71dfff66');g.addColorStop(1,'#71dfff00');c.fillStyle=g;c.globalCompositeOperation='screen';c.fillRect(p.x-36,p.y-102,72,72);c.globalCompositeOperation='source-over';}}else{c.fillStyle='#bda36b';c.fillRect(p.x-20,p.y-50,40,60);}c.restore();c.fillStyle='#102e2de6';c.beginPath();c.roundRect(p.x-20,p.y+20,40,19,7);c.fill();c.fillStyle='#fbe3ad';c.textAlign='center';c.font='bold 15px Georgia';c.fillText(['','I','II','III'][t.level],p.x,p.y+34);}
 enemy(e,p,time){const hold=this.delayedHp.get(e.id);if(hold&&hold.until>this.visualTime)e={...e,hp:hold.hp};const c=this.ctx,boss=e.type==='boss',size=boss?87:e.type==='crab'?61:52,im=this.images[boss?'boss':e.type==='crab'?'crab':'raider'];const bob=this.motion?Math.sin(time*12+e.id)*1.8:0;c.fillStyle='#18272166';c.beginPath();c.ellipse(p.x,p.y+8,size*.34,size*.13,0,0,Math.PI*2);c.fill();if(im)c.drawImage(im,p.x-size/2,p.y-size*.75+bob,size,size);else{c.fillStyle='#683957';c.beginPath();c.arc(p.x,p.y,14,0,Math.PI*2);c.fill();}if(e.type==='shield'){c.fillStyle='#b9c9ca';c.beginPath();c.moveTo(p.x+6,p.y-12);c.lineTo(p.x+22,p.y-8);c.lineTo(p.x+19,p.y+10);c.lineTo(p.x+10,p.y+16);c.closePath();c.fill();}if(e.type==='healer'){c.fillStyle='#c8f6ac';c.font='bold 21px Arial';c.textAlign='center';c.fillText('+',p.x,p.y-10);}if(e.type==='runner'){c.strokeStyle='#ceefff';c.lineWidth=2;for(let i=0;i<2;i++){c.beginPath();c.moveTo(p.x-24,p.y-4+i*7);c.lineTo(p.x-35,p.y-4+i*7);c.stroke();}}if(e.wet>0){c.strokeStyle='#70e3ff';c.lineWidth=3;c.beginPath();c.ellipse(p.x,p.y+12,20,7,0,0,Math.PI*2);c.stroke();}if(e.burn>0){c.fillStyle='#ffc33a';c.beginPath();c.moveTo(p.x-6,p.y);c.lineTo(p.x+1,p.y-25);c.lineTo(p.x+9,p.y);c.fill();}const w=boss?66:34,y=p.y-size*.8-6;c.fillStyle='#102928';c.fillRect(p.x-w/2-1,y-1,w+2,6);c.fillStyle=boss?'#e6a2f6':'#ea7668';c.fillRect(p.x-w/2,y,w*e.hp/e.maxHp,4);}
 beacon(p,time,health){const c=this.ctx;if(this.images.beacon){c.drawImage(this.images.beacon,p.x-65,p.y-110,130,130);return;}c.save();c.translate(p.x,p.y);c.shadowColor='#17221ccc';c.shadowBlur=12;c.fillStyle='#e7d4a3';c.beginPath();c.moveTo(-25,14);c.lineTo(-16,-68);c.lineTo(18,-68);c.lineTo(30,14);c.closePath();c.fill();c.shadowBlur=0;c.fillStyle='#976d35';c.fillRect(-23,-70,45,8);c.fillStyle='#0e656d';c.fillRect(-5,-48,12,25);c.fillStyle='#163d44';c.beginPath();c.moveTo(-28,-76);c.lineTo(0,-105);c.lineTo(29,-76);c.fill();const g=c.createRadialGradient(0,-73,1,0,-73,80);g.addColorStop(0,'#fff5b5cc');g.addColorStop(1,'#ffda6d00');c.fillStyle=g;c.fillRect(-80,-153,160,160);c.fillStyle='#fff3ac';c.fillRect(-13,-81,26,12);c.restore();}
 effect(e){const c=this.ctx,p=e.age/e.duration;c.save();c.globalAlpha=1-p;if(e.type==='shot'){
 const color={ballista:'#fff0ba',mortar:'#ffb951',tide:'#8feaff',storm:'#b3f8ff',fire:'#ffb044'}[e.tower]||'#fff';c.strokeStyle=color;c.fillStyle=color;c.globalAlpha=1;
 if(e.tower==='storm'){c.shadowColor='#80dcff';c.shadowBlur=14;c.lineWidth=3;for(const q of e.targets){c.beginPath();c.moveTo(e.from.x,e.from.y);for(let i=1;i<=7;i++){const f=i/7;c.lineTo(e.from.x+(q.x-e.from.x)*f+(i<7?Math.sin(i*13+e.age*80)*8:0),e.from.y+(q.y-e.from.y)*f);}c.stroke();}}
 else{const x=e.from.x+(e.to.x-e.from.x)*p,y=e.from.y+(e.to.y-e.from.y)*p-(e.tower==='mortar'?Math.sin(p*Math.PI)*85:0);c.shadowColor=color;c.shadowBlur=10;const trail=.08,prev=Math.max(0,p-trail),px=e.from.x+(e.to.x-e.from.x)*prev,py=e.from.y+(e.to.y-e.from.y)*prev-(e.tower==='mortar'?Math.sin(prev*Math.PI)*85:0);c.lineWidth=e.tower==='ballista'?2:4;c.beginPath();c.moveTo(px,py);c.lineTo(x,y);c.stroke();c.beginPath();c.arc(x,y,e.tower==='mortar'?5:2,0,Math.PI*2);c.fill();}
 }else if(e.type==='impact'){const radius=e.radius*(.2+p*.8),g=c.createRadialGradient(e.x,e.y,1,e.x,e.y,Math.max(2,radius));g.addColorStop(0,'#fff7cdcc');g.addColorStop(.22,e.color+'bb');g.addColorStop(1,e.color+'00');c.fillStyle=g;c.fillRect(e.x-radius,e.y-radius,radius*2,radius*2);for(let i=0;i<12;i++){const a=i*2.399,r=radius*(.5+(i%3)*.15);c.fillStyle=i%2?'#f7df9a':'#82562c';c.beginPath();c.arc(e.x+Math.cos(a)*r,e.y+Math.sin(a)*r*.7-p*(1-p)*38,Math.max(.4,3*(1-p)),0,Math.PI*2);c.fill();}}
 else if(e.type==='smoke'){c.globalAlpha=(1-p)*.32;for(let i=0;i<5;i++){const r=6+p*15,cx=e.x+Math.sin(i*3)*p*21,cy=e.y-p*35-i*3;const g=c.createRadialGradient(cx,cy,0,cx,cy,r);g.addColorStop(0,'#c8c3ae');g.addColorStop(1,'#a9aa9a00');c.fillStyle=g;c.fillRect(cx-r,cy-r,r*2,r*2);}}
 else if(e.type==='kill'){c.fillStyle='#fff0b0';c.textAlign='center';c.font='bold 19px Georgia';c.fillText('+'+e.gold,e.x,e.y-25-p*28);}else if(e.type==='meteor'){c.fillStyle='#ffad4222';c.strokeStyle='#ffd982';c.lineWidth=8*(1-p);c.beginPath();c.arc(e.x,e.y,135*Math.min(1,p*3),0,Math.PI*2);c.fill();c.stroke();for(let i=0;i<12;i++){const a=i*Math.PI/6;c.fillStyle='#ffdf96';c.fillRect(e.x+Math.cos(a)*p*135,e.y+Math.sin(a)*p*135,6,6);}}else if(e.type==='tide'){c.strokeStyle='#a0f8ff';c.lineWidth=22;c.beginPath();c.arc(500,500,p*850,0,Math.PI*2);c.stroke();}else if(e.type==='build'){const q=R.pads(this.map)[e.pad];c.strokeStyle='#ffecac';c.lineWidth=4;c.beginPath();c.ellipse(q.x,q.y,35+p*55,22+p*35,0,0,Math.PI*2);c.stroke();}else if(e.type==='heal'){c.fillStyle='#bdffc6';c.font='26px Arial';c.fillText('+',e.x,e.y-30*p);}else if(e.type==='leak'){c.strokeStyle='#ff8d7a';c.lineWidth=14;c.strokeRect(7,7,986,986);}c.restore();}
}
window.BastionField=BastionField;
})();
