'use strict';
const assert=require('node:assert/strict'),S=require('../js/solitaire-core'),G=require('../js/game-'+(process.argv[2]||'klondike')),{chromium,подготовитьПодделку}=require('./браузер-робот'),base=process.env.CASUAL_BASE||'http://127.0.0.1:8137';
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:390,height:844}});await подготовитьПодделку(page);await page.addInitScript(id=>{const s=sessionStorage.getItem('card-fixture');if(s){localStorage.setItem('casual-'+id+'-v1',s);sessionStorage.removeItem('card-fixture');}},G.id);await page.goto(base+'/'+G.id+'.html');let fixture;for(let seed=1;seed<100;seed++){fixture=G.create(G.modes[0].id,seed);if(S.moves(fixture).some(a=>a.type==='move'))break;}await page.evaluate(s=>sessionStorage.setItem('card-fixture',JSON.stringify({state:s,history:[]})),fixture);await page.reload();await page.locator('#continue').click();const saved=()=>page.evaluate(id=>JSON.parse(localStorage.getItem('casual-'+id+'-v1')).state,G.id);let state=await saved(),move=S.moves(state).find(a=>a.type==='move');assert(move);const expected=structuredClone(state);S.act(expected,move);
 const from=move.from,to=move.to;if(from.area==='piles')await page.locator(`.playing-card[data-pile="${from.pile}"][data-index="${from.index}"]`).click();else if(from.area==='cells')await page.locator('.free-cells>.card-slot').nth(from.pile).click();else await page.locator('.solitaire-top>.card-slot').click();
 if(to.area==='foundations')await page.locator('.foundations>.card-slot').nth(to.pile).click();else if(to.area==='cells')await page.locator('.free-cells>.card-slot').nth(to.pile).click();else await page.locator(`.card-pile[data-pile="${to.pile}"]>button`).last().click();assert.deepEqual((await saved()).piles,expected.piles);assert.deepEqual((await saved()).foundations,expected.foundations);await page.locator('#undo').click();assert.deepEqual((await saved()).piles,state.piles);
 if(G.id!=='freecell'){await page.locator('.stock').click();assert((await saved()).stock.length<state.stock.length);await page.locator('#undo').click();assert.deepEqual((await saved()).stock,state.stock);}
 if(G.id!=='spider'){const win=G.create(G.modes[0].id,1);win.stock=[];win.waste=[{id:12,suit:0,up:true}];win.piles=win.piles.map(()=>[]);win.foundations=Array.from({length:4},(_,suit)=>Array.from({length:suit===0?12:13},(_,rank)=>({id:suit*13+rank,suit,up:true})));if(G.id==='freecell'){win.cells[0]=win.waste;win.waste=[];}assert(G.validate(win));await page.evaluate(s=>sessionStorage.setItem('card-fixture',JSON.stringify({state:s,history:[]})),win);await page.reload();await page.locator('#continue').click();await page.getByRole('button',{name:'Карту в дом',exact:true}).click();assert((await saved()).won);assert.match(await page.locator('#dialog-title').innerText(),/Отличная партия/);}
 if(G.id==='spider'){const win=G.create('1',1);win.stock=[];win.piles=Array.from({length:10},()=>[]);win.finished=Array.from({length:7},(_,set)=>Array.from({length:13},(_,i)=>({id:set*13+12-i,suit:0,up:true})));win.piles[0]=Array.from({length:12},(_,i)=>({id:103-i,suit:0,up:true}));win.piles[1]=[{id:91,suit:0,up:true}];assert(G.validate(win));await page.evaluate(s=>sessionStorage.setItem('card-fixture',JSON.stringify({state:s,history:[]})),win);await page.reload();await page.locator('#continue').click();await page.locator('.playing-card[data-pile="1"]').click();await page.locator('.playing-card[data-pile="0"]').last().click();assert((await saved()).won);assert.equal((await saved()).finished.length,8);assert.match(await page.locator('#dialog-title').innerText(),/Отличная партия/);}
 console.log(G.id+': tap-to-move, legal destination, undo, stock and victory — OK');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
