'use strict';
const assert=require('node:assert/strict'),{chromium,подготовитьПодделку,безTelegram}=require('./браузер-робот');
const id=process.argv[2]||'mines',G=require('../js/game-'+id),base=process.env.CASUAL_BASE||'http://127.0.0.1:8137';
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await подготовитьПодделку(page,{версия:'8.0',отступы:{системные:{top:24,bottom:20},содержимого:{top:56}}});await page.clock.install();await page.goto(base+'/'+id+'.html');await page.locator('.cover img').evaluate(e=>e.decode());await page.screenshot({path:`tests/снимки/${id}-лобби.png`,fullPage:true,animations:'disabled'});await page.locator('#play').click();assert(await page.locator('#playfield').isVisible());await page.keyboard.press('a');
 if(id==='mines'){await page.locator('.mine-cell').first().click();assert(await page.locator('.revealed').count()>0);await page.getByRole('button',{name:'⚑ Флажок',exact:true}).click();await page.locator('.mine-cell:not(.revealed)').first().click();assert.equal(await page.locator('.flagged').count(),1);}
 for(const [width,height]of [[320,740],[390,844],[430,932],[768,1024],[1024,768],[1440,900]]){await page.setViewportSize({width,height});await page.screenshot({path:`tests/снимки/${id}-поле-${width}.png`,fullPage:true,animations:'disabled'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert((await page.locator('.topbar').boundingBox()).y>=80);if(['mahjong','blocks','match3','wordsearch','fifteen','snake'].includes(id)){if(width<600)assert((await page.locator('#playfield').boundingBox()).width>width*.85);assert(await page.locator('.game-scroll').evaluate(e=>e.scrollHeight<=e.clientHeight+2));}}
 const saved=()=>page.evaluate(id=>JSON.parse(localStorage.getItem('casual-'+id+'-v1')),id);await page.clock.runFor(2100);await page.locator('#pause').click();const before=await page.locator('#timer').innerText();await page.clock.runFor(3000);assert.equal(await page.locator('#timer').innerText(),before);await page.locator('#resume').click();await page.locator('#help').click();assert(await page.locator('#dialog').isVisible());await page.getByRole('button',{name:'Понятно',exact:true}).click();const snapshot=await saved();await page.reload();await page.locator('#continue').click();assert.equal((await saved()).state.mode,snapshot.state.mode);if(id==='mines')assert.deepEqual((await saved()).state.flags,snapshot.state.flags);
 await page.locator('#collection').click();for(const mode of G.modes.slice(1)){await page.locator(`[data-mode="${mode.id}"]`).click();await page.locator('#play').click();await page.getByRole('button',{name:'Начать новую',exact:true}).click();assert.equal((await saved()).state.mode,mode.id);assert(await page.locator('#playfield').isVisible());await page.locator('#collection').click();}
 await page.goto(base+'/index.html',{waitUntil:'domcontentloaded'});await page.locator('[data-фильтр="головоломки"]').click();await page.locator(`[data-игра="${G.key}"]`).click();await page.waitForURL('**/'+id+'.html');assert.deepEqual(errors,[]);console.log(id+': catalogue, modes, help, pause, save/resume, six sizes and Telegram safe areas — OK');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
