'use strict';
const assert=require('node:assert/strict'),R=require('../js/nonogram-rules'),bank=require('../js/nonogram-puzzles'),{chromium,подготовитьПодделку,безTelegram}=require('./браузер-робот');
const base=process.env.NONOGRAM_BASE||'http://127.0.0.1:8137';
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()===404)missing.push(r.url());});
 await подготовитьПодделку(page,{версия:'8.0',отступы:{системные:{top:24,bottom:20},содержимого:{top:56}}});await page.clock.install();await page.addInitScript(()=>{const fixture=sessionStorage.getItem('nonogram-test');if(fixture!==null){localStorage.setItem('nonogram-game-v1',fixture);sessionStorage.removeItem('nonogram-test');}});
 await page.goto(base+'/nonogram.html');await page.locator('.cover img').evaluate(e=>e.decode());await page.screenshot({path:'tests/снимки/японский-лобби-390.png',fullPage:true,animations:'disabled'});assert.equal(await page.locator('[data-puzzle]').count(),9);await page.locator('#play').click();assert.equal(await page.locator('.pixel').count(),25);
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('nonogram-game-v1'))),cell=i=>page.locator(`.pixel[data-index="${i}"]`);
 await cell(0).click();assert.equal((await saved()).board[0],1);await cell(0).click();assert.equal((await saved()).board[0],0);await page.locator('[data-brush="cross"]').click();await cell(0).click();assert.equal((await saved()).board[0],-1);await page.locator('#undo').click();assert.equal((await saved()).board[0],0);await page.locator('#redo').click();assert.equal((await saved()).board[0],-1);
 await page.locator('[data-brush="fill"]').click();const from=await cell(5).boundingBox(),to=await cell(9).boundingBox();await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:10});await page.mouse.up();assert.deepEqual((await saved()).board.slice(5,10),[1,1,1,1,1]);await page.locator('#undo').click();assert.deepEqual((await saved()).board.slice(5,10),[0,0,0,0,0]);await page.locator('#redo').click();
 await cell(2).click({button:'right'});assert.equal((await saved()).board[2],-1);await page.locator('#check').click();assert((await saved()).checks===1);await cell(4).click();await page.locator('#check').click();assert(await cell(4).evaluate(e=>e.classList.contains('error')));await page.locator('#undo').click();
 await page.locator('#hint').click();assert.match(await page.locator('#dialog').innerText(),/Подсказка учтена/);await page.locator('#dialog .primary').click();assert.equal((await saved()).hints,1);
 await page.clock.runFor(3000);let seconds=(await saved()).seconds;assert(seconds>=2);await page.locator('#pause').click();seconds=(await saved()).seconds;await page.clock.runFor(4000);assert.equal((await saved()).seconds,seconds);assert(await page.locator('#resume').isVisible());await page.locator('#resume').click();await page.locator('#help').click();seconds=(await saved()).seconds;await page.clock.runFor(3000);assert.equal((await saved()).seconds,seconds);await page.getByRole('button',{name:'Понятно'}).click();
 const s=await saved();await page.reload();await page.locator('#continue').click();assert.deepEqual((await saved()).board,s.board);
 for(const [width,height]of [[320,740],[390,844],[430,932],[768,1024],[1024,768],[1440,900]]){await page.setViewportSize({width,height});await page.screenshot({path:`tests/снимки/японский-5-${width}.png`,fullPage:true,animations:'disabled'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert((await page.locator('.topbar').boundingBox()).y>=80);}
 // Large puzzle keeps readable cells and pinned clues when panning.
 const big=R.create(bank.find(p=>p.id==='hard-6'));await page.evaluate(s=>sessionStorage.setItem('nonogram-test',JSON.stringify(s)),big);await page.setViewportSize({width:390,height:844});await page.reload();await page.locator('#continue').click();assert.equal(await page.locator('.pixel').count(),225);assert((await cell(0).boundingBox()).width>=25);assert(await page.locator('#board-scroll').evaluate(e=>e.scrollWidth>e.clientWidth));
 await page.locator('[data-brush="pan"]').click();await cell(0).click();assert((await saved()).board.every(v=>!v));await page.locator('#board-scroll').evaluate(e=>{e.scrollTop=80;e.scrollLeft=80;});const edge=await page.locator('#board-scroll').boundingBox(),top=await page.locator('.col-clue').first().boundingBox(),left=await page.locator('.row-clue').first().boundingBox();assert(Math.abs(top.y-edge.y)<2);assert(Math.abs(left.x-edge.x)<2);await page.screenshot({path:'tests/снимки/японский-15-390.png',fullPage:true,animations:'disabled'});
 await page.locator('#zoom').click();assert.match(await page.locator('#zoom').innerText(),/200/);await page.locator('#zoom').click();assert.match(await page.locator('#zoom').innerText(),/100/);
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert(await page.locator('#resume').isVisible());await page.evaluate(()=>Object.defineProperty(document,'hidden',{configurable:true,value:false}));await page.locator('#resume').click();
 const win=R.create(bank[0]),last=win.solution.indexOf(1);win.board=win.solution.map(v=>v?1:0);win.board[last]=0;win.seconds=123;await page.evaluate(s=>sessionStorage.setItem('nonogram-test',JSON.stringify(s)),win);await page.reload();await page.locator('#continue').click();await cell(last).click();assert((await saved()).completed);assert.match(await page.locator('#dialog-title').innerText(),/Сердце/);assert.equal(await page.locator('.win-art i.on').count(),win.solution.filter(Boolean).length);await page.screenshot({path:'tests/снимки/японский-победа.png',fullPage:true,animations:'disabled'});await page.getByRole('button',{name:'К коллекции',exact:true}).click();assert(await page.locator('[data-puzzle="easy-1"]').evaluate(e=>e.classList.contains('solved')));assert.match(await page.locator('#puzzle-info').innerText(),/02:03/);
 await page.evaluate(()=>sessionStorage.setItem('nonogram-test','broken'));await page.reload();assert(await page.locator('#continue').isHidden());await page.locator('[data-level="medium"]').click();await page.locator('#play').click();assert.equal((await saved()).n,10);await page.locator('#restart').click();await page.getByRole('button',{name:'Продолжить',exact:true}).click();assert(await page.locator('#dialog').isHidden());
 await page.goto(base+'/index.html');await page.locator('[data-фильтр="головоломки"]').click();await page.locator('[data-игра="японский-кроссворд"]').click();await page.waitForURL('**/nonogram.html');
 const desktop=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});await безTelegram(desktop);await desktop.goto(base+'/nonogram.html');await desktop.locator('.cover img').evaluate(e=>e.decode());await desktop.screenshot({path:'tests/снимки/японский-лобби-1440.png',animations:'disabled'});await desktop.locator('#play').click();await desktop.locator('.pixel').first().focus();await desktop.keyboard.press('x');await desktop.keyboard.press('ArrowRight');await desktop.keyboard.press('Space');assert.deepEqual(await desktop.evaluate(()=>JSON.parse(localStorage.getItem('nonogram-game-v1')).board.slice(0,2)),[-1,1]);
 const touch=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await подготовитьПодделку(touch,{версия:'8.0',отступы:{системные:{top:24,bottom:20},содержимого:{top:56}}});await touch.addInitScript(s=>localStorage.setItem('nonogram-game-v1',JSON.stringify(s)),big);await touch.goto(base+'/nonogram.html');await touch.locator('#continue').tap();await touch.locator('[data-brush="pan"]').tap();const area=await touch.locator('#board-scroll').boundingBox(),cdp=await touch.context().newCDPSession(touch);const tx=area.x+area.width-50,ty=area.y+area.height-45;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:tx,y:ty}]});for(let k=1;k<=8;k++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:tx-k*16,y:ty-k*9}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touch.waitForTimeout(900);assert(await touch.locator('#board-scroll').evaluate(e=>e.scrollLeft>0));assert(await touch.evaluate(()=>JSON.parse(localStorage.getItem('nonogram-game-v1')).board.every(v=>v===0)));await touch.locator('#board-scroll').evaluate(e=>e.scrollTo(0,0));await touch.locator('[data-brush="fill"]').tap();await touch.waitForFunction(()=>document.querySelector('[data-brush=fill]').getAttribute('aria-pressed')==='true',{},{timeout:1500});await touch.locator('.pixel[data-index="0"]').tap();assert.equal(await touch.evaluate(()=>JSON.parse(localStorage.getItem('nonogram-game-v1')).board[0]),1);
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('Nonogram UI: catalogue, three sizes, drag strokes, undo/redo, marks, hints, pause, persistence, zoom/pinned clues, keyboard, real touch/panning and victory/collection — OK');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
