'use strict';
const assert=require('node:assert/strict'),R=require('../js/sudoku-rules'),bank=require('../js/sudoku-puzzles');
// Independent row/column/box solver, separate from the production bitmask solver.
function countSolutions(input){const b=input.slice();let total=0;function visit(){let at=-1,options=null;for(let i=0;i<81;i++)if(!b[i]){const row=Math.floor(i/9),col=i%9,ns=[];for(let n=1;n<=9;n++){let ok=true;for(let j=0;j<9;j++)if(b[row*9+j]===n||b[j*9+col]===n||b[(Math.floor(row/3)*3+Math.floor(j/3))*9+Math.floor(col/3)*3+j%3]===n){ok=false;break;}if(ok)ns.push(n);}if(!ns.length)return;if(!options||ns.length<options.length){at=i;options=ns;if(ns.length===1)break;}}if(at<0){total++;return;}for(const n of options){b[at]=n;visit();if(total>1)break;}b[at]=0;}visit();return total;}
for(const level of R.levels){assert.equal(bank[level].length,12);for(const source of bank[level]){const p=[...source].map(Number);assert.equal(countSolutions(p),1);assert.equal(R.logic(p).level,level);}for(let seed=1;seed<=100;seed++){const s=R.create(level,bank,seed);assert.equal(R.solve(s.puzzle).count,1);assert.equal(R.logic(s.puzzle).level,level);assert.equal(R.conflicts(s.solution).length,0);assert(!s.solution.includes(0));assert.deepEqual(R.restore(s),s);}}
const s=R.create('easy',bank,10),empty=s.board.findIndex(n=>!n),given=s.board.findIndex(Boolean),answer=s.solution[empty];assert(!R.enter(s,given,0));assert(!R.enter(s,-1,2));assert(!R.enter(s,empty,10));assert(R.enter(s,empty,2,true));assert.equal(s.board[empty],0);assert.equal(s.notes[empty],2);assert(R.enter(s,empty,2,true));assert.equal(s.notes[empty],0);R.undo(s);assert.equal(s.notes[empty],2);R.undo(s);assert.equal(s.notes[empty],0);
const p=R.peers[empty].find(i=>!s.board[i]);R.enter(s,p,answer,true);const before=JSON.stringify({board:s.board,notes:s.notes});R.enter(s,empty,answer);assert.equal(s.notes[p]&(1<<(answer-1)),0);R.undo(s);assert.equal(JSON.stringify({board:s.board,notes:s.notes}),before);
const wrong=answer%9+1;R.enter(s,empty,wrong);assert.equal(R.hint(s,empty).technique,'correction');assert.equal(R.hint(s,empty).value,answer);R.undo(s);const h=R.hint(s,empty);assert.equal(h.value,s.solution[h.index]);
const corrupt=JSON.parse(JSON.stringify(s));corrupt.solution=Array(81).fill(1);assert.deepEqual(R.restore(corrupt).solution,s.solution);corrupt.board[given]=0;assert.equal(R.restore(corrupt),null);assert.equal(R.restore({}),null);assert.equal(R.solve(Array(81).fill(1)).count,0);assert.equal(R.solve(Array(81).fill(0)).count,2);
for(let i=0;i<81;i++)if(!s.puzzle[i])R.enter(s,i,s.solution[i]);assert(s.completed);assert(!R.undo(s));assert(!R.enter(s,empty,0));assert(R.restore(s).completed);
console.log('Sudoku rules: 48 independently verified unique puzzles, 400 graded variations, notes, conflicts, hints, undo, save validation and completion — OK');
