'use strict';
const assert=require('node:assert/strict'),R=require('../js/sudoku-rules'),bank=require('../js/sudoku-puzzles'),{chromium,подготовитьПодделку,безTelegram}=require('./браузер-робот');
const base=process.env.SUDOKU_BASE||'http://127.0.0.1:8137';
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],missing=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(base)&&r.status()===404)missing.push(r.url());});
 await подготовитьПодделку(page,{версия:'8.0',отступы:{системные:{top:24,bottom:20},содержимого:{top:56}}});
 await page.addInitScript(()=>{const raw=sessionStorage.getItem('sudoku-test');if(raw!==null){localStorage.setItem('sudoku-game-v1',raw);sessionStorage.removeItem('sudoku-test');}});
 await page.clock.install();await page.goto(base+'/sudoku.html');await page.locator('.cover img').evaluate(e=>e.decode());await page.screenshot({path:'tests/снимки/судоку-лобби-390.png',fullPage:true,animations:'disabled'});
 await page.locator('[data-level="hard"]').click();await page.locator('#play').click();assert.equal(await page.locator('#difficulty').innerText(),'Сложный');assert.equal(await page.locator('#board button').count(),81);
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('sudoku-game-v1')));let s=await saved();const i=s.board.indexOf(0),given=s.board.findIndex(Boolean),answer=s.solution[i];
 await page.locator(`[data-index="${given}"]`).click();await page.locator('[data-number="1"]').click();assert.deepEqual((await saved()).board,s.board);
 await page.locator(`[data-index="${i}"]`).click();await page.locator('#notes').click();await page.locator('[data-number="3"]').click();assert.equal((await saved()).notes[i],4);assert.equal((await saved()).board[i],0);
 await page.locator('#undo').click();assert.equal((await saved()).notes[i],0);await page.locator('#notes').click();await page.keyboard.press(String(answer));assert.equal((await saved()).board[i],answer);await page.locator('#erase').click();assert.equal((await saved()).board[i],0);await page.locator('#undo').click();assert.equal((await saved()).board[i],answer);
 await page.clock.runFor(3000);const seconds=(await saved()).seconds;assert(seconds>=2);await page.locator('#pause').click();await page.clock.runFor(5000);assert.equal((await saved()).seconds,seconds);assert(await page.locator('#resume').isVisible());await page.locator('#resume').click();
 await page.locator('#help').click();await page.clock.runFor(5000);assert.equal((await saved()).seconds,seconds);await page.getByRole('button',{name:'Понятно',exact:true}).click();
 await page.locator('#hint').click();assert.match(await page.locator('#dialog').innerText(),/Подсказка учтена/);await page.getByRole('button',{name:/Вставить/}).click();assert.equal((await saved()).hints,1);
 s=await saved();await page.reload();await page.locator('#continue').click();assert.deepEqual((await saved()).board,s.board);assert.equal((await saved()).level,'hard');
 const j=s.board.findIndex(n=>!n);await page.locator(`[data-index="${j}"]`).click();await page.keyboard.press(String(s.solution[j]%9+1));await page.locator('#check').click();assert(await page.locator(`[data-index="${j}"]`).evaluate(e=>e.classList.contains('error')));await page.locator('#undo').click();assert.equal((await saved()).board[j],0);
 for(const [width,height]of [[320,740],[390,844],[430,932],[768,1024],[1024,768],[1440,900]]){
  await page.setViewportSize({width,height});await page.screenshot({path:`tests/снимки/судоку-поле-${width}.png`,fullPage:true,animations:'disabled'});
  const layout=await page.locator('#board').evaluate(e=>{const b=e.getBoundingClientRect(),top=document.querySelector('.topbar').getBoundingClientRect().top;return {width:b.width,height:b.height,top,overflow:document.documentElement.scrollWidth>innerWidth+1,cells:[...e.children].every(c=>{const r=c.getBoundingClientRect();return r.width>=30&&r.left>=b.left-1&&r.right<=b.right+1&&r.bottom<=b.bottom+1;})};});assert(!layout.overflow);assert(Math.abs(layout.width-layout.height)<1);assert(layout.cells);assert(layout.top>=80);
 }
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert(await page.locator('#resume').isVisible());await page.evaluate(()=>Object.defineProperty(document,'hidden',{configurable:true,value:false}));await page.locator('#resume').click();
 // Real completion route with one remaining cell, and a record saved once.
 const win=R.create('easy',bank,27),last=win.board.findIndex(n=>!n);win.board=win.solution.slice();win.board[last]=0;win.seconds=123;
 await page.evaluate(s=>sessionStorage.setItem('sudoku-test',JSON.stringify(s)),win);await page.reload();await page.locator('#continue').click();await page.locator(`[data-index="${last}"]`).click();await page.locator(`[data-number="${win.solution[last]}"]`).click();assert.match(await page.locator('#dialog-title').innerText(),/Всё на своих местах/);assert((await saved()).completed);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('sudoku-best-v1')).easy),123);
 await page.getByRole('button',{name:'Выбрать сложность',exact:true}).click();assert(await page.locator('#continue').isHidden());assert.equal(await page.locator('#record').innerText(),'02:03');
 await page.evaluate(()=>sessionStorage.setItem('sudoku-test','broken'));await page.reload();assert(await page.locator('#continue').isHidden());await page.locator('[data-level="expert"]').click();await page.locator('#play').click();assert.equal((await saved()).level,'expert');
 await page.goto(base+'/index.html');await page.locator('[data-фильтр="головоломки"]').click();await page.locator('[data-игра="судоку"]').click();await page.waitForURL('**/sudoku.html');
 const desktop=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'});await безTelegram(desktop);await desktop.goto(base+'/sudoku.html');await desktop.locator('.cover img').evaluate(e=>e.decode());await desktop.screenshot({path:'tests/снимки/судоку-лобби-1440.png',animations:'disabled'});assert(await desktop.locator('#back').isVisible());
 assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);console.log('Sudoku UI: catalogue, 4 levels, input, notes, undo, hints, timer/pause, save/resume, validation, victory/record, 6 sizes and Telegram safe areas — OK');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
