'use strict';
const assert=require('node:assert/strict');const {chromium,безTelegram}=require('./браузер-робот.js'),R=require('../js/бастион-правила.js');
function order(map){return R.pads(map).map((p,i)=>{let coverage=0;for(let d=0;d<R.geometry(map).length;d+=35){const q=R.position(map,d);if(Math.hypot(q.x-p.x,q.y-p.y)<220)coverage++;}return {i,coverage};}).sort((a,b)=>b.coverage-a.coverage).map(x=>x.i);}
(async()=>{const server=await require('./бастион-стенд.js')(),browser=await chromium.launch({headless:true});try{const p=await browser.newPage({viewport:{width:1280,height:960}});await безTelegram(p);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install();await p.goto(server.url+'/'+encodeURIComponent('бастион')+'.html');await p.waitForFunction(()=>БастионИгра.готов());await p.click('#start');const pads=order(0),cycle=['mortar','tide','ballista','mortar','ballista','tide'];let steps=0;
 while(steps++<300){let s=await p.evaluate(()=>БастионИгра.состояние());if(['won','lost'].includes(s.phase))break;
 for(const tower of s.towers){s=await p.evaluate(()=>БастионИгра.состояние());const t=s.towers.find(t=>t.pad===tower.pad);if(t.level<3&&s.towers.length>=3&&s.gold>=R.upgradeCost(t)){await p.click('[data-pad="'+t.pad+'"]');await p.click('#tower-panel [data-upgrade="'+(t.level===1?-1:t.type==='mortar'?1:0)+'"]');}}
 for(const pad of pads){s=await p.evaluate(()=>БастионИгра.состояние());if(s.towers.some(t=>t.pad===pad))continue;const type=cycle[s.towers.length%cycle.length];if(s.gold<R.TOWERS[type].cost)break;await p.click('[data-pad="'+pad+'"]');await p.click('#tower-panel [data-build="'+type+'"]');}
 s=await p.evaluate(()=>БастионИгра.состояние());if(s.phase==='build')await p.click('#launch');if(s.phase==='wave'&&s.enemies.length>=8&&s.cooldowns.tide===0)await p.click('#tide');await p.clock.runFor(2500);}
 const won=await p.evaluate(()=>БастионИгра.состояние());assert.equal(won.phase,'won','Полная партия через интерфейс: '+won.phase+' wave '+won.wave);assert.equal(await p.locator('#dialog-title').textContent(),'Маяк защищён');assert.equal(await p.locator('#next-island').count(),1);await p.screenshot({path:'tests/снимки/бастион-победа.png'});await p.click('#next-island');assert.equal((await p.evaluate(()=>БастионИгра.состояние())).map,1);assert.equal((await p.evaluate(()=>БастионИгра.состояние())).wave,0);await p.click('#pause');await p.click('#to-lobby');await p.click('#choose-map');await p.click('[data-map="0"]');await p.click('#start');await p.click('#confirm-new');await p.click('[data-pad="0"]');await p.click('#tower-panel [data-build="tide"]');
 for(let i=0;i<140;i++){const s=await p.evaluate(()=>БастионИгра.состояние());if(s.phase==='lost')break;if(s.phase==='build')await p.click('#launch');await p.clock.runFor(3500);}
 assert.equal((await p.evaluate(()=>БастионИгра.состояние())).phase,'lost');assert.equal(await p.locator('#dialog-title').textContent(),'Оборона прорвана');await p.click('#retry');assert.equal((await p.evaluate(()=>БастионИгра.состояние())).wave,0);assert.deepEqual(errors,[]);console.log('Полная победа за '+Math.round(won.time)+' секунд боя, переход на следующий остров, полное поражение и повтор — через настоящие кнопки, без подмены правил.');
 }finally{await browser.close();await server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
