'use strict';
const assert=require('node:assert/strict');
const path=require('node:path');
const R=require(process.argv[2]?path.resolve(process.argv[2]):'../js/бастион-правила.js');
function run(name,fn){fn();console.log('✓ '+name);}
function enemy(type='raider',d=300,hp=100){return {id:1,type,d,hp,maxHp:hp,slow:0,slowPower:0,wet:0,burn:0,burnDamage:0,broken:0,heal:2};}
run('Покупка, двойное нажатие, запрет кредита и незаконной башни',()=>{const s=R.create();assert(R.build(s,0,'ballista'));const gold=s.gold;assert(!R.build(s,0,'ballista'));assert.equal(s.gold,gold);assert(!R.build(s,1,'storm'));assert(!R.build(s,-1,'ballista'));s.gold=0;assert(!R.upgrade(s,0));assert.equal(s.towers[0].level,1);});
run('Улучшения, развилки, возврат и защита от размножения золота',()=>{const s=R.create();R.build(s,0,'mortar');s.gold=1000;assert(R.upgrade(s,0));assert(!R.upgrade(s,0));assert(R.upgrade(s,0,1));assert(!R.upgrade(s,0,0));const g=s.gold,refund=R.sellValue(s,s.towers[0]);assert(R.sell(s,0));assert.equal(s.gold,g+refund);assert(!R.sell(s,0));assert.equal(s.gold,g+refund);const b=R.create();R.build(b,0,'ballista');R.sell(b,0);assert.equal(b.gold,290);R.build(b,0,'ballista');R.startWave(b);assert.equal(R.sellValue(b,b.towers[0]),49);});
run('Бой без обороны заканчивается поражением, без повторного старта волн',()=>{const s=R.create();for(let n=0;n<20000&&s.phase!=='lost';n++){if(s.phase==='build'){assert(R.startWave(s));assert(!R.startWave(s));}R.tick(s,.1);}assert.equal(s.phase,'lost');const raw=R.snapshot(s);R.tick(s,.1);assert.equal(R.snapshot(s),raw);assert(!R.build(s,0,'ballista'));assert(R.restore(raw));});
run('Удар маяка: область, броня, награда один раз, перезарядка',()=>{const s=R.create();R.startWave(s);s.queue=[];s.enemies=[enemy('crab',300,100)];s.nextId=2;const p=R.position(0,300),g=s.gold;assert(R.cast(s,'meteor',p));assert.equal(s.enemies[0].hp,0);assert.equal(s.gold,g+14);assert(!R.cast(s,'meteor',p));R.tick(s,.1);assert.equal(s.phase,'build');assert.equal(s.kills,1);assert(!R.cast(s,'meteor',{x:NaN,y:3}));});
run('Прилив действительно замедляет; пауза подготовки не двигает время',()=>{const s=R.create();const raw=R.snapshot(s);R.tick(s,.1);assert.equal(R.snapshot(s),raw);R.startWave(s);s.queue=[];s.enemies=[enemy()];s.nextId=2;R.cast(s,'tide');const d=s.enemies[0].d;R.tick(s,.1);assert(Math.abs(s.enemies[0].d-d-1.365)<.001);});
run('Последняя волна ждёт всех врагов',()=>{const s=R.create();s.wave=7;R.startWave(s);s.queue=[];s.enemies=[enemy()];s.nextId=2;R.tick(s,.1);assert.equal(s.phase,'wave');R.cast(s,'meteor',R.position(0,s.enemies[0].d));R.tick(s,.1);assert.equal(s.phase,'won');assert.equal(R.stars(s),3);assert(!R.startWave(s));});
run('Сохранение посреди волны восстанавливает тот же бой',()=>{const s=R.create(2);R.build(s,0,'ballista');R.build(s,1,'mortar');R.startWave(s);for(let i=0;i<200;i++)R.tick(s);const restored=R.restore(R.snapshot(s));assert(restored);for(let i=0;i<500;i++){R.tick(s);R.tick(restored);}assert.equal(R.snapshot(s),R.snapshot(restored));});
run('Повреждённые сохранения безопасно отклоняются',()=>{assert.equal(R.restore('{oops'),null);for(const mutate of [s=>s.gold=-1,s=>s.map=999,s=>s.phase='other',s=>s.queue=['toString'],s=>s.cooldowns=null,s=>s.wave=.5,s=>s.towers=[{pad:0,type:'__proto__'}],s=>s.enemies=[enemy('constructor')]]){const s=R.create();mutate(s);assert.equal(R.restore(s),null);}const s=R.create();R.build(s,0,'ballista');s.towers[0].spent=999;assert.equal(R.restore(s),null);});
run('Звёзды и рекорды не дублируются, карты открываются по очереди',()=>{const p=R.profile();const s=R.create();s.phase='won';s.wave=8;s.time=200;assert(R.record(p,s));assert.equal(R.unlocked(p),1);assert(!R.record(p,s));assert.equal(R.mapStars(p,0),3);const before=JSON.stringify(p);s.hp=5;s.time=100;assert(!R.record(p,s));assert.equal(JSON.stringify(p),before);assert.equal(R.profile('{broken').preparation,'none');});
function coverage(map,p){let n=0;const len=R.geometry(map).length;for(let d=0;d<len;d+=35){const q=R.position(map,d);if(Math.hypot(q.x-p.x,q.y-p.y)<220)n++;}return n;}
function defend(s,variant=0){const ps=R.pads(s.map),order=ps.map((p,i)=>({i,n:coverage(s.map,p)})).sort((a,b)=>b.n-a.n);const cycle=variant?['ballista','mortar','ballista','tide','mortar','ballista']:['mortar','tide','ballista','mortar','ballista','tide'];for(const t of s.towers){if(t.level<3&&s.gold>=R.upgradeCost(t)&&s.towers.length>=3)R.upgrade(s,t.pad,t.level===2?(t.type==='mortar'?1:0):null);}for(const o of order){if(s.towers.some(t=>t.pad===o.i))continue;const type=cycle[s.towers.length%cycle.length];if(!R.build(s,o.i,type))break;}}
function simulate(map,diff,variant){const s=R.create(map,diff);let n=0;while(!['won','lost'].includes(s.phase)&&n++<35000){defend(s,variant);if(s.phase==='build')R.startWave(s);if(s.enemies.length>=8&&s.cooldowns.tide===0)R.cast(s,'tide');if(s.enemies.length>=7&&s.cooldowns.meteor===0){const e=s.enemies.find(e=>e.type==='boss')||s.enemies[Math.floor(s.enemies.length/2)];R.cast(s,'meteor',R.position(map,e.d,e.route));}R.tick(s,.1);if(n%100===0){assert(s.gold>=0);assert(R.restore(R.snapshot(s)),'Не восстановился бой: '+map+' '+diff);}}return s;}
run('Все 12 островов проходимы на трёх сложностях двумя составами без постоянной подготовки',()=>{let count=0;for(let map=0;map<12;map++)for(const diff of ['easy','normal','hard'])for(let variant=0;variant<2;variant++){const s=simulate(map,diff,variant);assert.equal(s.phase,'won',`Карта ${map+1}, ${diff}, состав ${variant}: ${s.phase}, волна ${s.wave}, здоровье ${s.hp}`);count++;}console.log('  '+count+' полных партий');});
if(require.main===module)console.log('Правила и кампания: проверки пройдены.');
module.exports={simulate,defend};
