'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {chromium,безTelegram,подготовитьПодделку}=require('./браузер-робот.js');
const R=require('../игры/бастион/бастион-правила.js');
const BASE=process.argv[2];
async function main(){const server=BASE?null:await require('./бастион-стенд.js')(),base=BASE||server.url,browser=await chromium.launch({headless:true});const errors=[];try{
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});const page=await context.newPage();await безTelegram(page);page.on('pageerror',e=>errors.push(e.message));
 const url=base+'/'+encodeURIComponent('бастион')+'.html';await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.БастионИгра?.готов(),{timeout:30000});assert.equal(await page.locator('#mission-name').textContent(),'Тихая гавань');await page.locator('#choose-map').click();assert.equal(await page.locator('[data-map]').count(),12);assert.equal(await page.locator('[data-map="1"]').isDisabled(),true);await page.locator('#close-dialog').click();
 await page.locator('#start').click();assert.equal(await page.locator('#launch').isDisabled(),true);await page.locator('[data-pad="1"]').click();assert(await page.locator('#build-dialog').isVisible());await page.locator('#tower-panel-mobile [data-build="mortar"]').click();assert.equal(await page.locator('#build-dialog').isVisible(),false);assert.equal((await page.evaluate(()=>БастионИгра.состояние())).gold,190);
 await page.locator('[data-pad="3"]').click();await page.locator('#tower-panel-mobile [data-build="ballista"]').click();await page.locator('[data-pad="4"]').click();await page.locator('#tower-panel-mobile [data-build="tide"]').click();await page.locator('#launch').click();await page.waitForFunction(()=>БастионИгра.состояние().time>.3);await page.locator('#pause').click();const frozen=await page.evaluate(()=>БастионИгра.состояние().time);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>БастионИгра.состояние().time),frozen);await page.locator('#resume').click();
 await page.locator('[data-pad="3"]').click();const buildTime=await page.evaluate(()=>БастионИгра.состояние().time);await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>БастионИгра.состояние().time),buildTime);await page.locator('#close-build').click();await page.locator('#meteor').click();assert(await page.locator('#field-wrap').evaluate(e=>e.classList.contains('aiming')));await page.locator('#field').click({position:{x:80,y:75}});assert((await page.evaluate(()=>БастионИгра.состояние())).cooldowns.meteor>27);await page.locator('#tide').click();assert((await page.evaluate(()=>БастионИгра.состояние())).cooldowns.tide>33);
 await page.locator('#pause').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('bastion_save_v1')));await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>БастионИгра.готов());await page.locator('#continue').click();assert.equal(await page.locator('#pause-cover').isVisible(),true);const restored=await page.evaluate(()=>БастионИгра.состояние());assert.equal(restored.time,saved.time);assert.deepEqual(restored.towers,saved.towers);await page.locator('#resume').click();
 for(const [width,height] of [[320,740],[390,844],[820,1180],[844,390],[1440,1000]]){await page.setViewportSize({width,height});await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Горизонтальная прокрутка '+width);const boxes=await page.evaluate(()=>({field:document.querySelector('#field').getBoundingClientRect().toJSON(),panel:document.querySelector('.command').getBoundingClientRect().toJSON()}));if(width<500)assert(Math.abs(boxes.field.width-width)<2,'Поле не на всю ширину');assert(boxes.field.bottom<=boxes.panel.top||boxes.field.right<=boxes.panel.left,'Панель перекрывает поле');await page.screenshot({path:'tests/снимки/бастион-проверка-'+width+'.png',fullPage:true});}
 await page.locator('#pause').click();await page.locator('#to-lobby').click();await page.locator('#arsenal').click();assert.equal(await page.locator('[data-tower]').count(),6);await page.locator('[data-tower="mortar"]').click();assert.equal(await page.locator('.branches article').count(),2);await page.locator('#close-dialog').click();await page.locator('#settings').click();await page.locator('#sound-setting').uncheck();await page.locator('#motion-setting').uncheck();await page.locator('#close-dialog').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('bastion_profile_v1')).sound),false);
 await page.locator('#start').click();assert.equal(await page.locator('#confirm-new').count(),1);await page.locator('#close-dialog').click();assert.equal((await page.evaluate(()=>БастионИгра.состояние())).wave,1);
 // Завершённая правилами партия: награда восстанавливается после закрытия страницы.
 const won=R.create();won.wave=8;won.phase='won';won.time=240;await page.evaluate(s=>localStorage.setItem('bastion_save_v1',s),R.snapshot(won));await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>БастионИгра.готов());assert.equal(await page.locator('#total-stars').textContent(),'★ 3 / 36');await page.reload({waitUntil:'domcontentloaded'});assert.equal(await page.locator('#total-stars').textContent(),'★ 3 / 36');await page.locator('#choose-map').click();assert.equal(await page.locator('[data-map="1"]').isDisabled(),false);await page.locator('[data-map="1"]').click();assert.equal(await page.locator('#mission-name').textContent(),'Каменная коса');await page.locator('#records').click();assert.equal(await page.locator('.record-row').count(),1);await page.locator('#close-dialog').click();await page.locator('#arsenal').click();await page.locator('[data-preparation="supply"]').click();await page.locator('#close-dialog').click();await page.locator('#start').click();assert.equal((await page.evaluate(()=>БастионИгра.состояние())).gold,330);
 // Прерывание видимостью и защита от другой вкладки.
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});assert(await page.locator('#pause-cover').isVisible());await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});});await page.locator('#resume').click();const tab=await page.context().newPage();await безTelegram(tab);await tab.goto(url,{waitUntil:'domcontentloaded'});await tab.waitForFunction(()=>БастионИгра.готов());await tab.locator('#continue').click();await page.waitForFunction(()=>!document.querySelector('#pause-cover').hidden);await tab.close();
 // Telegram: системная «Назад», безопасные отступы, фото владельца.
 const tg=await browser.newPage({viewport:{width:390,height:844}});await подготовитьПодделку(tg,{версия:'8.0',стрелка:true});tg.on('pageerror',e=>errors.push(e.message));await tg.goto(url,{waitUntil:'domcontentloaded'});await tg.waitForFunction(()=>БастионИгра.готов());assert.equal(await tg.locator('#back').isVisible(),false);await tg.locator('#start').click();assert.equal(await tg.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await tg.close();
 assert.deepEqual(errors,[]);console.log('Интерфейс: покупки, способности, модальные окна, пауза, сохранение, 5 размеров, награды, подготовка, две вкладки и Telegram-подделка — пройдены.');
 }finally{await browser.close();if(server)await server.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});
