"use strict";
const assert=require('node:assert/strict'),fs=require('node:fs'),P=require('../js/катан-правила'),B=require('../js/катан-бот'),{chromium,безTelegram}=require('./браузер-робот');
(async()=>{const b=await chromium.launch();try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await безTelegram(p);await p.route(url=>decodeURIComponent(url.pathname).startsWith('/фото/'),r=>r.fulfill({contentType:'image/webp',body:fs.readFileSync('img/катан/ресурсы-v2.webp')}));await p.goto(process.env.CATAN_TEST_URL||'http://127.0.0.1:8137/катан.html');
 const g=P.создать(3,42,false,3);while(g.phase.startsWith('setup'))P.действие(g,g.turn,B.ход(P.вид(g,g.turn)));g.phase='discard';g.turn=1;g.discard=[5,0,0];g.players[0].resources=[4,2,1,1,2];
 await p.evaluate(g=>{window.uiGame=g;window.uiVersion=0;window.pushUI=()=>{const view=КатанПравила.вид(uiGame,0);view.names=['Вы','Друг','Бот 2'];ИграПоСети.показатьВид({код:'ui-test',версия:++uiVersion,катан:view,портреты:[{этоЯ:true,фото:'a'.repeat(24)},{фото:'b'.repeat(24)},{этоБот:true}],застолом:[{номер:1},{номер:2},{номер:3,этоБот:true}]});};Сеть.отправитьХод=async a=>{КатанПравила.действие(uiGame,0,a.move);pushUI();return {принято:true};};pushUI();},g);
 await p.waitForFunction(()=>document.querySelector('.кат-игрок[data-player="1"] img')?.naturalWidth>0);assert.equal(await p.locator('.кат-игрок[data-player="1"] .кат-аватар').evaluate(e=>getComputedStyle(e).backgroundImage),'none');assert.equal(await p.locator('.кат-игрок[data-player="2"] img').count(),0);
 await p.locator('#кат-главное').click();assert(await p.getByRole('button',{name:'Сбросить 5 карт',exact:true}).isDisabled());for(let i=0;i<4;i++)await p.locator('[data-select-resource="0"]').click();assert(await p.locator('[data-select-resource="0"]').isDisabled());await p.locator('[data-select-resource="1"]').click();assert(!(await p.getByRole('button',{name:'Сбросить 5 карт',exact:true}).isDisabled()));await p.locator('[data-remove-resource="0"]').click();assert(await p.getByRole('button',{name:'Сбросить 5 карт',exact:true}).isDisabled());await p.locator('[data-select-resource="4"]').click();
 for(const [width,height] of [[320,740],[390,844],[820,1180],[1440,900]]){await p.setViewportSize({width,height});assert(await p.locator('#кат-диалог').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.screenshot({path:`tests/снимки/катан-сброс-${width}.png`,fullPage:true});}await p.getByRole('button',{name:'Сбросить 5 карт',exact:true}).click();assert.deepEqual(await p.evaluate(()=>uiGame.players[0].resources),[1,1,1,1,1]);
 await p.evaluate(()=>{uiGame.phase='robber';uiGame.turn=0;pushUI();});const legal=await p.evaluate(()=>КатанПравила.вид(uiGame,0).legal.robber);assert.equal(await p.locator('.кат-разбойник-доступный-контур').count(),legal.length);assert(!(await p.locator('#кат-поле .кат-заблокирован').getAttribute('role')));const target=legal[0];await p.locator('#кат-поле [data-hex="'+target+'"]').click();assert(await p.locator('.кат-разбойник-выбран').count());assert(await p.evaluate(()=>{const svg=document.getElementById('кат-поле'),r=svg.querySelector('.кат-разбойник:not(.кат-разбойник-превью)');return [...svg.querySelectorAll('.кат-путь,.кат-постройка')].every(e=>Boolean(e.compareDocumentPosition(r)&Node.DOCUMENT_POSITION_FOLLOWING));}));await p.setViewportSize({width:390,height:844});await p.screenshot({path:'tests/снимки/катан-рыцарь-подсветка.png',fullPage:true});
 for(const card of ['knight','roads','plenty','monopoly']){await p.evaluate(card=>{uiGame.phase='main';uiGame.turn=1;uiGame.playedDev=false;uiGame.round=20;uiGame.players[1].dev=[{type:card,bought:0}];const action={type:'dev',card,resources:[1,0,0,0,0],resource:0};if(card==='plenty')action.resources=[2,0,0,0,0];КатанПравила.действие(uiGame,1,action);pushUI();},card);await p.locator('#кат-диалог[open][data-kind=played-development]').waitFor();assert.match(await p.locator('#кат-диалог').innerText(),/Друг играет карту/);assert.equal(await p.locator('.кат-новая-карта').getAttribute('data-card'),card);await p.screenshot({path:`tests/снимки/катан-сыграна-${card}.png`});await p.getByRole('button',{name:'Понятно',exact:true}).click();await p.evaluate(()=>pushUI());assert(!(await p.locator('#кат-диалог[open][data-kind=played-development]').count()));}
 await p.evaluate(()=>{uiGame.phase='main';uiGame.turn=0;uiGame.players[0].resources=[8,0,0,0,0];КатанПравила.действие(uiGame,0,{type:'bank',give:0,want:1});pushUI();});await p.locator('#кат-обмен-выполнен').waitFor();assert.match(await p.locator('#кат-обмен-выполнен').innerText(),/Обмен выполнен[\s\S]*Отдали: Дерево[\s\S]*Получили: Глина/);
 await p.evaluate(()=>{uiGame.players[1].resources=[0,2,0,0,0];КатанПравила.действие(uiGame,0,{type:'offer',to:1,give:[1,0,0,0,0],want:[0,1,0,0,0],confirmation:true});КатанПравила.действие(uiGame,1,{type:'agree',offer:uiGame.offer.id});КатанПравила.действие(uiGame,0,{type:'confirmTrade',offer:uiGame.offer.id,partner:1});pushUI();});assert.match(await p.locator('#кат-обмен-выполнен').innerText(),/Отдали: Дерево × 1[\s\S]*Получили: Глина × 1/);
 await p.evaluate(()=>{uiGame.phase='main';uiGame.turn=0;uiGame.playedDev=false;uiGame.players[0].dev=[{type:'plenty',bought:0}];uiGame.players[0].resources=[3,2,1,4,0];uiGame.bank=[1,19,19,19,0];pushUI();});await p.locator('#кат-карты').click();await p.locator('.кат-карта-развития').filter({hasText:'Изобилие'}).click();assert.deepEqual(await p.locator('#кат-диалог .кат-торговля-ресурсы strong').allTextContents(),['3','2','1','4','0']);assert(!/19|доступно|банк/i.test(await p.locator('#кат-диалог').innerText()));assert(await p.locator('[data-select-resource=\"4\"]').isDisabled());await p.locator('[data-select-resource=\"0\"]').click();assert(await p.locator('[data-select-resource=\"0\"]').isDisabled());await p.locator('[data-select-resource=\"1\"]').click();await p.screenshot({path:'tests/снимки/катан-изобилие-рука.png'});await p.getByRole('button',{name:'Получить карты',exact:true}).click();assert.deepEqual(await p.evaluate(()=>uiGame.players[0].resources),[4,3,1,4,0]);
 assert.deepEqual(errors,[]);console.log('Card discard, exact counts, four sizes, robber targets/layer, real opponent photo and four public development cards — OK');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
