'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
process.env.ДАННЫЕ_ИГРЫ=path.join(os.tmpdir(),'catan-resource-search-'+process.pid);
const server=require('../server/сервер').создатьСервер(),B=require('../js/катан-бот'),{chromium,безTelegram}=require('./браузер-робот');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch();let players=[];try{
 const req=async(route,body)=>{const r=await fetch(base+'/'+encodeURIComponent(route),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,200);return r.json();};
 const room=await req('создать',{игра:'катан',имя:'Участник 0',мест:3});players.push({код:room.код,пропуск:room.пропуск});for(let i=1;i<3;i++){const p=await req('войти',{код:room.код,имя:'Участник '+i});players.push({код:room.код,пропуск:p.пропуск});}assert((await req('ход',{...players[0],действие:'начать'})).принято);
 const states=async()=>Promise.all(players.map(p=>req('состояние',p))),send=(i,move)=>req('ход',{...players[i],действие:'катан',move});let fixture;
 for(let n=0;n<1200&&!fixture;n++){const s=await states(),v=s.map(s=>(s.состояние||s).катан),a=v[0].turn;if(v[0].phase==='main'&&!v[0].offer){const others=[0,1,2].filter(i=>i!==a);outer:for(let give=0;give<5;give++)for(let want=0;want<5;want++)if(give!==want&&v[a].hand[give]&&others.every(i=>v[i].hand[want])){fixture={a,b:others[0],c:others[1],give,want,views:v};break outer;}}if(fixture)break;const who=v[0].offer?v[0].offer.from:v[0].actor,action=v[0].offer?{type:'cancelOffer',offer:v[0].offer.id}:B.ход(v[who],'сложный');assert((await send(who,action)).принято);}
 assert(fixture,'No legal trade fixture reached');const {a,b,c,give,want,views}=fixture,pages=[];const refresh=async()=>{const s=await states();for(const [i,p]of pages)await p.evaluate(s=>ИграПоСети.показатьВид(s.состояние||s),s[i]);};
 for(const i of [a,b,c]){const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'});await безTelegram(p);await p.goto(process.env.CATAN_TEST_URL||'http://127.0.0.1:8137/катан.html');await p.exposeFunction('sendUi',async action=>{const reply=await send(i,action.move);await refresh();return reply;});await p.evaluate(()=>Сеть.отправитьХод=window.sendUi);pages.push([i,p]);}await refresh();const A=pages[0][1],C=pages[1][1],D=pages[2][1];
 await A.locator('#кат-обмен').click();await A.getByRole('button',{name:'С игроками',exact:true}).click();await A.locator(`[data-trade-side=want][data-resource="${want}"]`).tap();await A.getByRole('button',{name:'Искать ресурс',exact:true}).click();await C.locator('#кат-диалог[data-kind=offer][open]').waitFor();
 await D.locator('#кат-диалог[data-kind=offer][open]').waitFor();const id=(await states())[a].катан?.offer?.id||((await states())[a].состояние.катан.offer.id);
 for(const p of [C,D]){assert.match(await p.locator('#кат-диалог').innerText(),/ищет/);await p.getByRole('button',{name:'Предложить свой вариант',exact:true}).click();assert.equal(await p.locator(`[data-basket=give] [data-resource="${want}"]`).getAttribute('data-count'),'1');await p.locator(`[data-trade-side=want][data-resource="${give}"]`).click();await p.getByRole('button',{name:'Отправить свой вариант',exact:true}).click();await p.locator('#кат-диалог').waitFor({state:'hidden'});}
 assert.deepEqual((await states()).map(s=>(s.состояние||s).катан.hand),views.map(v=>v.hand));assert.equal(await A.locator('[data-partner]').count(),2);assert(await A.locator('[data-confirm-trade]').isDisabled());assert.equal(await A.locator('.кат-торговля-история').count(),0);
 await A.locator(`[data-partner="${c}"]`).click();await A.screenshot({path:'tests/снимки/катан-поиск-ресурса-варианты.png'});await A.locator('[data-confirm-trade]').click();await A.locator('#кат-диалог').waitFor({state:'hidden'});
 const final=(await states()).map(s=>(s.состояние||s).катан);assert.equal(final[a].offer,null);assert.deepEqual(final[b].hand,views[b].hand,'First responder must not receive the trade');assert.equal(final[a].hand[give],views[a].hand[give]-1);assert.equal(final[a].hand[want],views[a].hand[want]+1);assert.equal(final[c].hand[give],views[c].hand[give]+1);assert.equal(final[c].hand[want],views[c].hand[want]-1);assert.equal((await send(a,{type:'confirmTrade',offer:id,partner:b})).принято,false);
 for(const [,p]of pages)assert(!(await p.locator('#кат-диалог').isVisible()));console.log('Catan HTTP + 3 browsers: wanted-resource request, two independent priced quotes, author chooses second, exact transfers, dialogs closed, no history, no double transfer — OK');
 for(const p of players)await req('выйти',p);
 }finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
