'use strict';
const assert=require('node:assert/strict'),{chromium,безTelegram}=require('./браузер-робот');
const server=require('../server/сервер').создатьСервер();
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,b=await chromium.launch();
 const req=async(path,body)=>{const r=await fetch(base+'/'+encodeURIComponent(path),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,200);return r.json();};
 try{for(const points of [10,12,15]){const p=await b.newPage({viewport:{width:390,height:844}});await безTelegram(p);await p.route('https://catan-test.invalid/**',async route=>{const u=new URL(route.request().url());const response=await route.fetch({url:base+u.pathname+u.search,headers:{...route.request().headers(),origin:base}});await route.fulfill({response,headers:{...response.headers(),'access-control-allow-origin':new URL(p.url()).origin}});});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.CATAN_TEST_URL||'http://127.0.0.1:8137/катан.html')+'?сервер='+encodeURIComponent('https://catan-test.invalid'));
 await p.locator('#лобби-найти-игру').click();await p.locator('#открытые-столы-создать').click();await p.locator('#кат-цель-онлайн').getByRole('radio',{name:points+' ПО',exact:true}).click();
 assert.equal(await p.locator('#кат-стол-онлайн').count(),0);assert.equal(await p.locator('#кат-цель-онлайн').getByRole('radio',{name:points+' ПО',exact:true}).getAttribute('aria-checked'),'true');
 await p.reload();await p.locator('#лобби-найти-игру').click();await p.locator('#открытые-столы-создать').click();assert.equal(await p.locator('#кат-цель-онлайн').getByRole('radio',{name:points+' ПО',exact:true}).getAttribute('aria-checked'),'true');
 await p.locator('#кат-число-онлайн').getByRole('radio',{name:'Трое',exact:true}).click();if(points===12)await p.screenshot({path:'tests/снимки/катан-онлайн-выбор-по.png',fullPage:true});
 const reply=p.waitForResponse(r=>decodeURIComponent(new URL(r.url()).pathname)==='/создать'&&r.request().method()==='POST');await p.locator('#кнопка-создать-игру').click();const response=await reply;assert.equal(response.request().postDataJSON().катанНастройки.targetPoints,points);const room=await response.json(),players=[{код:room.код,пропуск:room.пропуск}];assert(room.код,JSON.stringify({status:response.status(),error:room.ошибка||room.error}));

 await p.locator('#комната').waitFor();await p.waitForFunction(points=>document.getElementById('комната-правила').textContent.includes('до '+points+' ПО'),points);await p.evaluate(()=>{const m=document.getElementById('сообщение-приглашения');m.textContent='Друг получил ссылку — он нажмёт её и сразу сядет за ваш стол.';m.classList.remove('скрыт');});
 for(const [width,height]of [[320,640],[390,844],[820,1180],[1440,900]]){await p.setViewportSize({width,height});for(const scroll of [0,300,10000]){await p.locator('#экран-комнаты').evaluate((e,y)=>e.scrollTop=y,scroll);const boxes=await p.evaluate(()=>['код-комнаты','кнопка-копировать-код','комната-начать','кнопка-комната-отмена'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return {id,x:r.x,y:r.y,right:r.right,bottom:r.bottom};}));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert(!(a.x<b.right-1&&b.x<a.right-1&&a.y<b.bottom-1&&b.y<a.bottom-1),a.id+' overlaps '+b.id);}}}if(points===12)await p.screenshot({path:'tests/снимки/катан-комната-без-перекрытий.png'});
 for(let i=1;i<3;i++){const x=await req('войти',{код:room.код,имя:'Проверка '+i});players.push({код:room.код,пропуск:x.пропуск});}assert((await req('ход',{...players[0],действие:'начать'})).принято);
 for(const player of players){const s=await req('состояние',player),v=s.состояние||s;assert.equal(v.катан.options.targetPoints,points);}
 for(const player of players)await req('выйти',player);assert.deepEqual(errors,[]);await p.close();console.log('Online CATAN '+points+' VP: UI selection, saved preference, creation payload and three server views — OK');}
 }finally{await b.close();server.closeAllConnections();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
