'use strict';
const assert=require('node:assert/strict'),P=require('../js/катан-правила'),B=require('../js/катан-бот'),{chromium,безTelegram}=require('./браузер-робот');
(async()=>{const browser=await chromium.launch();try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await безTelegram(page);await page.clock.install();await page.goto('http://127.0.0.1:8137/катан.html');await page.clock.pauseAt(new Date(await page.evaluate(()=>Date.now()+100)));
 let g;for(let seed=1;seed<100;seed++){g=P.создать(3,seed,false,3);while(g.phase.startsWith('setup'))P.действие(g,g.turn,B.ход(P.вид(g,g.turn)));g.turn=0;g.phase='roll';const trial=JSON.parse(JSON.stringify(g));P.действие(trial,0,{type:'roll'});if(trial.log.at(-1).gains?.some(a=>P.сумма(a)))break;}
 await page.evaluate(g=>{window.testGame=g;window.testVersion=0;window.testSeat=0;window.testPush=()=>{const view=КатанПравила.вид(testGame,testSeat);view.names=['Вы','Бот 1','Бот 2'];ИграПоСети.показатьВид({код:'test-ui-only',версия:++testVersion,сыграноПартий:0,катан:view,застолом:[{номер:1},{номер:2},{номер:3}]});};Сеть.отправитьХод=async a=>{КатанПравила.действие(testGame,testSeat,a.move);testPush();return {принято:true};};testPush();},g);
 assert.equal(await page.locator('#кат-поле .кат-значок-земли').count(),18);const variants=await page.locator('#кат-поле .кат-гекс').evaluateAll(es=>es.filter(e=>e.dataset.resource!=='5').map(e=>e.dataset.resource+'-'+e.dataset.variant));assert.equal(new Set(variants).size,18);
 assert(await page.locator('#кат-поле image[href*="разбойник-варианты"]').count());assert.equal(await page.locator('#кат-поле .кат-номер').first().evaluate(e=>getComputedStyle(e).fontSize),'29px');
 const before=await page.locator('#кат-ресурсы strong').allTextContents();await page.locator('#кат-главное').click();assert.deepEqual(await page.locator('#кат-ресурсы strong').allTextContents(),before,'Счётчики обновились раньше кубиков');
 await page.clock.runFor(2790);assert.equal(await page.locator('.кат-летящий-ресурс').count(),0);await page.clock.runFor(20);assert(await page.locator('.кат-летящий-ресурс').count());assert(await page.locator('#кат-бросок').isHidden());assert.deepEqual(await page.locator('#кат-ресурсы strong').allTextContents(),before);await page.screenshot({path:'tests/снимки/катан-выдача-ресурсов.png'});await page.clock.runFor(2500);
 const hand=await page.evaluate(()=>testGame.players[0].resources);assert.deepEqual((await page.locator('#кат-ресурсы strong').allTextContents()).map(Number),hand);assert.equal(await page.locator('#кат-кубики').getAttribute('data-player'),'0');
 await page.locator('#кат-фильтр').click();assert.equal(await page.getByRole('button',{name:'Дерево',exact:true}).count(),0);await page.getByRole('button',{name:'Оранжевый',exact:true}).click();assert(await page.locator('.кат-игрок[data-player="0"]').evaluate(e=>e.classList.contains('цвет-3')));assert.equal(new Set(await page.locator('.кат-игрок').evaluateAll(es=>es.map(e=>getComputedStyle(e).getPropertyValue('--цвет')))).size,3);await page.getByRole('button',{name:'Готово',exact:true}).click();
 await page.evaluate(()=>{testGame.phase='main';testGame.turn=0;testGame.players[0].resources=[3,2,2,2,2];testGame.players[1].resources=[3,3,3,3,3];testPush();});await page.locator('#кат-обмен').click();assert(!/В банке \d/.test(await page.locator('#кат-диалог').innerText()));await page.getByRole('button',{name:'С игроками',exact:true}).click();await page.getByRole('button',{name:'Увеличить Отдаю: Дерево',exact:true}).click();assert(await page.getByRole('spinbutton',{name:'Получаю: Дерево',exact:true}).isDisabled());assert(await page.getByRole('button',{name:'Увеличить Получаю: Дерево',exact:true}).isDisabled());await page.getByRole('button',{name:'Увеличить Получаю: Глина',exact:true}).click();await page.getByRole('button',{name:'Предложить обмен',exact:true}).click();assert.match(await page.locator('#кат-диалог').innerText(),/ожидаем ответа/);await page.getByRole('button',{name:'Отменить предложение',exact:true}).click();assert.match(await page.locator('#кат-диалог').innerText(),/отменено/);await page.getByRole('button',{name:'Готово',exact:true}).click();
 await page.evaluate(()=>{КатанПравила.действие(testGame,1,{type:'offer',to:0,give:[0,1,0,0,0],want:[1,0,0,0,0]});testPush();});await page.locator('#кат-предложение button').click();await page.getByRole('button',{name:'Предложить свой вариант',exact:true}).click();assert.equal(await page.getByRole('spinbutton',{name:'Отдаю: Дерево',exact:true}).inputValue(),'1');await page.getByRole('button',{name:'Отправить встречное предложение',exact:true}).click();assert.equal(await page.evaluate(()=>testGame.offer.from),0);await page.getByRole('button',{name:'Отменить предложение',exact:true}).click();await page.getByRole('button',{name:'Готово',exact:true}).click();
 await page.evaluate(()=>{testGame.phase='steal';testGame.turn=0;const vertex=testGame.buildings.findIndex(b=>b?.owner===1);testGame.robber=КатанПравила.Г.vertices[vertex].hexes[0];testGame.players[1].resources=[1,0,0,0,0];КатанПравила.действие(testGame,0,{type:'steal',victim:1});testPush();});assert.match(await page.locator('#кат-диалог').innerText(),/Вы получили ресурс/);assert.equal(await page.locator('.кат-добыча').getAttribute('data-resource'),'0');await page.getByRole('button',{name:'В мою руку',exact:true}).click();
 await page.locator('#кат-журнал-кнопка').click();assert(await page.locator('.кат-журнал.цвет-3').count());await page.locator('#кат-закрыть').click();
 await page.evaluate(()=>{Сеть.послатьЭмоцию=async(n,target)=>{const state={код:'test-ui-only',версия:++testVersion,катан:КатанПравила.вид(testGame,0),знакВнимания:{номер:n,порядковый:testVersion,этоЯ:true,от:0,кому:target-1}};ИграПоСети.показатьВид(state);return {принято:true};};});await page.locator('#кат-общение').click();await page.getByRole('button',{name:'🙂',exact:true}).click();assert(await page.locator('.знак-внимания').count());await page.clock.runFor(2100);await page.locator('#кат-общение').click();await page.getByRole('button',{name:'Кинуть',exact:true}).click();assert(await page.locator('#ряд-бросков img').count());await page.locator('#кнопка-эмоции-назад').click();
 for(const [width,height]of [[320,740],[390,844],[1024,768],[1440,900],[1920,1080]]){await page.setViewportSize({width,height});await page.clock.runFor(50);const layout=await page.evaluate(()=>{const ids=['кат-фильтр','кат-журнал-кнопка','кат-общение'];return {overflow:document.documentElement.scrollWidth>innerWidth+1,buttons:ids.map(id=>{const e=document.getElementById(id),r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})};});assert(!layout.overflow);assert(layout.buttons.every(Boolean),'Панель перекрыта на '+width);await page.screenshot({path:'tests/снимки/катан-итог-'+width+'.png'});}
 await page.evaluate(()=>{testGame=КатанПравила.создать(3,1,false,3);testGame.turn=0;КатанПравила.действие(testGame,0,{type:'settlement',vertex:КатанПравила.поселения(testGame,0,true)[0]});testPush();});await page.locator('#кат-поле [data-edge][role=button]').first().click();
 for(const [width,height]of [[320,740],[390,844],[1440,900]]){await page.setViewportSize({width,height});const fit=await page.locator('#кат-главное').evaluate(e=>{const r=e.getBoundingClientRect(),range=document.createRange();range.selectNodeContents(e);const t=range.getBoundingClientRect();return t.top>=r.top&&t.bottom<=r.bottom&&t.left>=r.left&&t.right<=r.right;});assert(fit,'Текст дороги выходит из кнопки на '+width);}
 assert.deepEqual(errors,[]);console.log('Катан UI: варианты ресурсов, разбойник, выдача после кубиков, палитра, торговля/контрпредложение, добыча, журнал, общение и 5 размеров экрана — OK');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
