'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),os=require('node:os');
process.env.ДАННЫЕ_ИГРЫ=path.join(os.tmpdir(),'catan-touch-trade-'+process.pid);
const server=require('../server/сервер').создатьСервер(),B=require('../js/катан-бот'),{chromium,безTelegram}=require('./браузер-робот');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch();let players=[];try{
 const req=async(route,body)=>{const r=await fetch(base+'/'+encodeURIComponent(route),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,200);return r.json();};
 const room=await req('создать',{игра:'катан',имя:'Участник 0',мест:3});players.push({код:room.код,пропуск:room.пропуск});for(let i=1;i<3;i++){const p=await req('войти',{код:room.код,имя:'Участник '+i});players.push({код:room.код,пропуск:p.пропуск});}assert((await req('ход',{...players[0],действие:'начать'})).принято);
 const states=async()=>Promise.all(players.map(p=>req('состояние',p))),send=(i,move)=>req('ход',{...players[i],действие:'катан',move});let fixture;
 for(let n=0;n<1200&&!fixture;n++){const s=await states(),v=s.map(s=>(s.состояние||s).катан),a=v[0].turn;if(v[0].phase==='main'&&!v[0].offer){outer:for(let b=0;b<3;b++)if(b!==a)for(let give=0;give<5;give++)for(let want=0;want<5;want++)if(give!==want&&v[a].hand[give]&&v[b].hand[want]){fixture={a,b,give,want,views:v};break outer;}}if(fixture)break;const who=v[0].offer?v[0].offer.from:v[0].actor,action=v[0].offer?{type:'cancelOffer',offer:v[0].offer.id}:B.ход(v[who],'сложный');assert((await send(who,action)).принято);}
 assert(fixture,'No legal trade fixture reached');const {a,b,give,want,views}=fixture,pages=[];const refresh=async()=>{const s=await states();for(const [i,p]of pages)await p.evaluate(s=>ИграПоСети.показатьВид(s.состояние||s),s[i]);};
 for(const i of [a,b]){const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,reducedMotion:'reduce'});await безTelegram(p);await p.goto(process.env.CATAN_TEST_URL||'http://127.0.0.1:8137/катан.html');await p.exposeFunction('sendUi',async action=>{const reply=await send(i,action.move);await refresh();return reply;});await p.evaluate(()=>Сеть.отправитьХод=window.sendUi);pages.push([i,p]);}await refresh();const A=pages[0][1],C=pages[1][1];
 await A.locator('#кат-обмен').click();await A.getByRole('button',{name:'С игроками',exact:true}).click();await A.getByRole('combobox',{name:'Кому предложить обмен'}).selectOption(String(b));await A.locator(`[data-trade-side=give][data-resource="${give}"]`).tap();await A.locator(`[data-trade-side=want][data-resource="${want}"]`).tap();await A.getByRole('button',{name:'Предложить обмен',exact:true}).click();await C.locator('#кат-диалог[data-kind=offer][open]').waitFor();
 await C.getByRole('button',{name:'Предложить свой вариант',exact:true}).click();await C.getByRole('button',{name:'Отправить встречное предложение',exact:true}).click();await A.getByRole('button',{name:'Согласиться на обмен',exact:true}).waitFor();const offered=(await states()).map(s=>(s.состояние||s).катан),id=offered[a].offer.id;await A.getByRole('button',{name:'Согласиться на обмен',exact:true}).click();
 await A.locator('#кат-диалог').waitFor({state:'hidden'});assert.deepEqual((await states()).map(s=>(s.состояние||s).катан.hand),views.map(v=>v.hand));await C.locator(`[data-partner="${a}"]`).click();await C.locator('[data-confirm-trade]').click();
 const final=(await states()).map(s=>(s.состояние||s).катан);for(const i of [a,b])assert.equal(final[i].offer,null);assert.equal(final[a].hand[give],views[a].hand[give]-1);assert.equal(final[a].hand[want],views[a].hand[want]+1);assert.equal(final[b].hand[give],views[b].hand[give]+1);assert.equal(final[b].hand[want],views[b].hand[want]-1);for(const [,p]of pages){await p.locator('#кат-диалог').waitFor({state:'hidden'});}assert.equal((await send(a,{type:'accept',offer:id})).принято,false);console.log('Catan HTTP + 2 browsers: real hands, offer popup, counteroffer, agreement, author confirmation, both inventories and closed dialogs, repeated acceptance rejected — OK');
 for(const p of players)await req('выйти',p);
 }finally{await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
