'use strict';
const assert=require('node:assert/strict'),P=require('../js/катан-правила'),B=require('../js/катан-бот'),{chromium,подготовитьПодделку}=require('./браузер-робот');
const url=process.env.CATAN_TEST_URL||'http://127.0.0.1:8137/катан.html';
(async()=>{const browser=await chromium.launch();try{
 const p=await browser.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await подготовитьПодделку(p,{версия:'8.0',отступы:{системные:{top:24,bottom:24},содержимого:{top:56}}});await p.goto(url);
 const g=P.создать(3,1,false,3,{targetPoints:12});while(g.phase.startsWith('setup'))P.действие(g,g.turn,B.ход(P.вид(g,g.turn)));g.phase='main';g.turn=0;g.players.forEach(player=>player.resources=[6,6,6,6,6]);
 await p.evaluate(g=>{window.touchGame=g;window.touchVersion=0;window.touchSeat=0;window.touchPush=()=>{const v=КатанПравила.вид(touchGame,touchSeat);v.names=['Вы','Анна','Игорь'];ИграПоСети.показатьВид({код:'touch-test',версия:++touchVersion,сыграноПартий:0,катан:v,застолом:[{номер:1},{номер:2},{номер:3}]});};Сеть.отправитьХод=async a=>{КатанПравила.действие(touchGame,touchSeat,a.move);touchPush();return {принято:true};};touchPush();},g);
 await p.locator('#кат-поле image').evaluateAll(async es=>Promise.all([...new Set(es.map(e=>e.getAttribute('href')))].map(async src=>{const im=new Image();im.src=src;await im.decode();})));
 assert.equal(await p.locator('#экран-игры h1').count(),0);assert.match(await p.locator('#кат-раунд').innerText(),/до 12 ПО/);assert.equal(await p.locator('.кат-значок-земли,.кат-название-земли').count(),0);assert.equal(await p.locator('#кат-поле .кат-номер').count(),18);
 await p.locator('#кат-обмен').click();await p.getByRole('button',{name:'С игроками',exact:true}).click();assert.equal(await p.locator('#кат-диалог input[type=number]').count(),0);
 await p.locator('[data-trade-side=give][data-resource="0"]').tap();await p.locator('[data-trade-side=give][data-resource="0"]').tap();assert(await p.locator('[data-trade-side=want][data-resource="0"]').isDisabled());await p.locator('[data-trade-side=want][data-resource="1"]').tap();assert.equal(await p.locator('[data-basket=give] [data-count]').getAttribute('data-count'),'2');await p.locator('[data-basket=give] button').click();assert.equal(await p.locator('[data-basket=give] [data-count]').getAttribute('data-count'),'1');
 await p.screenshot({path:'tests/снимки/катан-touch-торговля.png',fullPage:true});await p.getByRole('button',{name:'Предложить обмен',exact:true}).click();assert.equal(await p.locator('.кат-сделка .кат-ресурс-карта').count(),2);assert.match(await p.locator('#кат-диалог').innerText(),/ожидаем ответа/);await p.getByRole('button',{name:'Отменить предложение',exact:true}).click();await p.getByRole('button',{name:'Готово',exact:true}).click();
 // Incoming offer opens without pressing its banner; repeat snapshots don't reopen it after dismissal.
 await p.evaluate(()=>{КатанПравила.действие(touchGame,1,{type:'offer',to:0,give:[0,1,0,0,0],want:[1,0,0,0,0]});touchPush();});await p.locator('#кат-диалог[open][data-kind=offer]').waitFor();assert.match(await p.locator('#кат-диалог').innerText(),/Анна предлагает/);await p.screenshot({path:'tests/снимки/катан-touch-предложение.png',fullPage:true});await p.getByRole('button',{name:'Свернуть',exact:true}).click();await p.evaluate(()=>touchPush());assert(!(await p.locator('#кат-диалог').isVisible()));await p.locator('#кат-предложение button').click();await p.getByRole('button',{name:'Предложить свой вариант',exact:true}).click();assert.equal(await p.locator('[data-basket=give] [data-resource="0"]').getAttribute('data-count'),'1');await p.locator('[data-trade-side=give][data-resource="0"]').click();await p.getByRole('button',{name:'Отправить встречное предложение',exact:true}).click();assert.equal(await p.evaluate(()=>touchGame.offer.give[0]),2);
 await p.evaluate(()=>{КатанПравила.действие(touchGame,1,{type:'accept',offer:touchGame.offer.id});touchPush();});assert.match(await p.locator('#кат-диалог').innerText(),/Обмен состоялся/);assert.match(await p.locator('.кат-торговля-история').innerText(),/Анна/);assert.equal(await p.locator('.кат-торговля-история [data-count="2"]').count(),1);await p.getByRole('button',{name:'Готово',exact:true}).click();
 // A counteroffer stays on screen but cannot be submitted after its original offer closes.
 await p.evaluate(()=>{КатанПравила.действие(touchGame,1,{type:'offer',to:0,give:[0,1,0,0,0],want:[1,0,0,0,0]});touchPush();});await p.locator('#кат-диалог[data-kind=offer][open]').waitFor();await p.getByRole('button',{name:'Предложить свой вариант',exact:true}).click();await p.evaluate(()=>{КатанПравила.действие(touchGame,0,{type:'cancelOffer',offer:touchGame.offer.id});touchPush();});assert(await p.getByRole('button',{name:'Отправить встречное предложение',exact:true}).isDisabled());assert.match(await p.locator('#кат-диалог').innerText(),/уже изменилось или закрыто/);await p.locator('#кат-закрыть').click();
 // Offers do not replace another open dialog, but open when it is dismissed.
 await p.locator('#кат-журнал-кнопка').click();await p.evaluate(()=>{КатанПравила.действие(touchGame,1,{type:'offer',to:0,give:[0,1,0,0,0],want:[1,0,0,0,0]});touchPush();});assert.equal(await p.locator('#кат-диалог').getAttribute('data-kind'),'log');await p.locator('#кат-закрыть').click();await p.locator('#кат-диалог[data-kind=offer][open]').waitFor();await p.getByRole('button',{name:'Отказаться',exact:true}).click();assert.match(await p.locator('#кат-диалог').innerText(),/отклонено/);await p.getByRole('button',{name:'Готово',exact:true}).click();
 // Choose the robber destination, see its preview, confirm, watch movement and choose a victim.
 const destination=await p.evaluate(()=>{touchGame.phase='robber';touchGame.turn=0;const h=КатанПравила.Г.hexes.find(h=>h.id!==touchGame.robber&&new Set(h.vertices.map(i=>touchGame.buildings[i]?.owner).filter(i=>i>0)).size===2);if(!h)throw Error('Need a natural two-victim hex');touchPush();return h.id;});
 const previous=await p.evaluate(()=>touchGame.robber);await p.locator(`#кат-поле [data-hex="${destination}"]`).click();assert.equal(await p.evaluate(()=>touchGame.robber),previous);assert(await p.locator('.кат-разбойник-превью').count());assert(await p.locator('.кат-под-угрозой').count());await p.screenshot({path:'tests/снимки/катан-touch-разбойник-выбор.png',fullPage:true});await p.getByRole('button',{name:'Переместить сюда',exact:true}).click();assert.equal(await p.evaluate(()=>touchGame.robber),destination);assert(await p.locator('.кат-разбойник-переезжает').count());assert(await p.locator('#кат-главное').isDisabled());await p.locator('#кат-диалог[data-kind=victim][open]').waitFor();assert.equal(await p.locator('.кат-жертва').count(),2);await p.locator('.кат-жертва').first().click();await p.locator('#кат-диалог[data-kind=loot][open]').waitFor();await p.getByRole('button',{name:'В мою руку',exact:true}).click();
 // A single victim is stolen from automatically, but loot waits for movement; empty hexes do not open a victim dialog.
 for(const count of [1,0]){const dest=await p.evaluate(count=>{touchGame.phase='robber';touchGame.returnPhase='main';touchGame.turn=0;const h=КатанПравила.Г.hexes.find(h=>h.id!==touchGame.robber&&new Set(h.vertices.map(i=>touchGame.buildings[i]?.owner).filter(i=>i>0)).size===count);if(!h)throw Error('Missing victim-count fixture');touchPush();return h.id;},count);await p.locator(`#кат-поле [data-hex="${dest}"]`).click();await p.getByRole('button',{name:'Переместить сюда',exact:true}).click();assert(!(await p.locator('#кат-диалог').isVisible()),'Loot must not interrupt movement');if(count){await p.locator('#кат-диалог[data-kind=loot][open]').waitFor();await p.getByRole('button',{name:'В мою руку',exact:true}).click();}else{await p.locator('.кат-разбойник-переезжает').waitFor({state:'detached'});assert(!(await p.locator('#кат-диалог').isVisible()));}}
 for(const [width,height] of [[320,740],[390,844],[768,1024],[1440,900]]){await p.setViewportSize({width,height});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await p.evaluate(()=>document.getElementById('экран-игры').scrollTop=0);await p.screenshot({path:`tests/снимки/катан-touch-поле-${width}.png`,fullPage:true});await p.locator('#кат-обмен').click();await p.getByRole('button',{name:'С игроками',exact:true}).click();assert(await p.locator('#кат-диалог').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await p.locator('#кат-закрыть').click();}
 assert.deepEqual(errors,[]);console.log('Catan touch: no sticky title, VP target, clean hexes, card-based trades, incoming popup, counteroffer, completed trade cards, robber preview/animation/victim/loot, four sizes — OK');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
