"use strict";
const assert=require('node:assert/strict'),P=require('../js/катан-правила'),B=require('../js/катан-бот'),{chromium,безTelegram}=require('./браузер-робот');
(async()=>{const b=await chromium.launch();try{const p=await b.newPage({viewport:{width:390,height:844}});await безTelegram(p);await p.goto(process.env.CATAN_TEST_URL||'http://127.0.0.1:8137/катан.html');const g=P.создать(3,42,false,3,{targetPoints:15});while(g.phase.startsWith('setup'))P.действие(g,g.turn,B.ход(P.вид(g,g.turn)));g.options.targetPoints=15;g.phase='main';g.turn=0;g.round=20;g.players[0].dev=[{type:'vp',bought:0},{type:'vp',bought:0},{type:'knight',bought:0}];g.players[0].knights=2;for(const x of g.buildings)if(x?.owner===0)x.level=2;for(let i=0;i<3;i++){const id=P.поселения(g,0,true)[0];assert(Number.isInteger(id));g.buildings[id]={owner:0,level:1};}P.итог(g);assert.equal(P.вид(g,0).players[0].score,9);assert.equal(P.вид(g,1).players[0].score,7);assert.equal(P.вид(g,1).players[0].victoryCards,null);
 await p.evaluate(g=>{window.scoreGame=g;window.scoreVersion=0;window.scoreMe=0;window.pushScore=()=>ИграПоСети.показатьВид({код:'score-test-'+scoreMe,версия:++scoreVersion,катан:КатанПравила.вид(scoreGame,scoreMe)});pushScore();},g);
 const score=p.locator('.кат-игрок[data-player="0"]>strong');assert.equal(await score.innerText(),'7 +2');
 for(const [width,height] of [[320,740],[390,844],[820,1180],[1440,900]]){await p.setViewportSize({width,height});const fits=await score.evaluate(e=>{const a=e.getBoundingClientRect(),b=e.parentElement.getBoundingClientRect();return a.right<=b.right&&a.left>=b.left;});assert(fits);await p.screenshot({path:`tests/снимки/катан-очки-${width}.png`,fullPage:true});}
 await p.evaluate(()=>{КатанПравила.действие(scoreGame,0,{type:'dev',card:'knight'});pushScore();});await p.locator('#кат-диалог[data-kind=award][open]').waitFor();assert.match(await p.locator('#кат-диалог').innerText(),/Ваш бонус: \+2 ПО[\s\S]*Самая большая армия/);assert.equal(await p.locator('.кат-игрок[data-player="0"] [data-stat=knights] .кат-бонус-очки').innerText(),'+2');await p.getByRole('button',{name:'Понятно',exact:true}).click();await p.evaluate(()=>pushScore());assert(!(await p.locator('#кат-диалог[data-kind=award][open]').count()));
 await p.evaluate(()=>{const G=КатанПравила.Г;scoreGame.roads.fill(-1);function path(at,used){if(used.length===5)return used;for(const id of G.vertices[at].edges){if(used.includes(id))continue;const e=G.edges[id],next=e.a===at?e.b:e.a;if(scoreGame.buildings[next]&&scoreGame.buildings[next].owner!==0)continue;const found=path(next,[...used,id]);if(found)return found;}return null;}const edges=G.vertices.map(v=>path(v.id,[])).find(Boolean);for(const id of edges)scoreGame.roads[id]=0;scoreGame.phase='main';scoreGame.turn=0;КатанПравила.действие(scoreGame,0,{type:'end'});pushScore();});await p.locator('#кат-диалог[data-kind=award][open]').waitFor();assert.match(await p.locator('#кат-диалог').innerText(),/Самая длинная дорога/);assert.equal(await p.locator('.кат-игрок[data-player="0"] [data-stat=road] .кат-бонус-очки').innerText(),'+2');await p.getByRole('button',{name:'Понятно',exact:true}).click();await p.evaluate(()=>{scoreMe=1;pushScore();});assert.equal(await p.locator('.кат-игрок[data-player="0"] [data-hidden-points]').count(),0);assert.equal(await p.locator('.кат-игрок[data-player="0"]>strong[data-hidden-points]').count(),0);console.log('Own 7 +2, hidden opponent VP, four sizes, army and road awards, no repeated notification — OK');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
