'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),{chromium,подготовитьПодделку}=require('./браузер-робот');
const avatar=fs.readFileSync('img/катан/ресурсы-v2.webp');
(async()=>{const browser=await chromium.launch();try{
 for(const file of ['index','деберц','катан','монополия','домино','морской-бой','шахматы','шашки','нарды']){
  const page=await browser.newPage();await подготовитьПодделку(page);await page.addInitScript(()=>{Telegram.WebApp.initDataUnsafe.user.photo_url='https://avatar.test/own.webp';});await page.route('https://avatar.test/own.webp',r=>r.fulfill({contentType:'image/webp',body:avatar}));await page.goto('http://127.0.0.1:8137/'+file+'.html');await page.waitForFunction(()=>document.querySelector('.тг-аватар img')?.complete||document.querySelector('img.тг-аватар')?.complete);assert(await page.locator('.тг-аватар').count(),file);const bad=await page.locator('.тг-аватар img,img.тг-аватар').evaluateAll(es=>es.some(e=>!e.naturalWidth||e.src!=='https://avatar.test/own.webp'||getComputedStyle(e).filter!=='none'));assert(!bad,file);await page.close();
 }
 const page=await browser.newPage();await подготовитьПодделку(page,{подпись:'fake-init-for-mocked-route'});let calls=0;
 await page.route('**/'+encodeURIComponent('мой-аватар'),r=>{calls++;return r.fulfill({json:{ок:true,фото:'a'.repeat(24)}});});await page.route('**/'+encodeURIComponent('фото')+'/*',r=>r.fulfill({contentType:'image/webp',body:avatar}));await page.goto('http://127.0.0.1:8137/катан.html?server=http://127.0.0.1:8137');await page.waitForFunction(()=>document.querySelector('#кат-аватар img')?.src.includes('/'+encodeURIComponent('фото')+'/'));assert.equal(calls,1);await page.screenshot({path:'tests/снимки/катан-аватар-лобби.png'});await page.locator('#кат-боты').click();await page.waitForFunction(()=>document.querySelector('#кат-стол-ботов [data-my-avatar] img')?.complete);await page.screenshot({path:'tests/снимки/катан-морской-стол.png'});await page.close();console.log('Аватар UI: девять игр, загрузка Telegram фото и серверный резерв, фото на кресле и в лобби — OK');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
