'use strict';
const A=require('node:assert/strict'),P=require('../игры/покер/покер-правила'),{chromium,безTelegram}=require('./браузер-робот');
(async()=>{const b=await chromium.launch();try{const p=await b.newPage();await безTelegram(p);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.POKER_TEST_URL||'http://127.0.0.1:8137/покер.html',{waitUntil:'domcontentloaded'});
const g=P.create(6,79);g.phase='river';g.board=[9,23,37,48,10];g.players[0].hole=[49,50];const v=P.view(g,0);let version=0;
for(const [width,height]of [[320,740],[390,844],[844,390],[1440,900]]){await p.setViewportSize({width,height});await p.evaluate(({v,version})=>ИграПоСети.показатьВид({код:'face-test',версия:version,покер:v}),{v,version:++version});await p.locator('#pk-hand .face').first().waitFor();await p.locator('#pk-hand .face img').first().evaluate(i=>i.decode());await p.waitForTimeout(500);
for(const card of await p.locator('#pk-hand .face,#pk-board .face').all()){const info=await card.evaluate(c=>{const r=c.getBoundingClientRect(),a=c.querySelector('.pk-face-art').getBoundingClientRect(),img=c.querySelector('img');return {ratio:a.height/r.height,width:a.width/r.width,opacity:getComputedStyle(img).opacity,loaded:img.complete&&img.naturalWidth>0,rank:c.querySelector('.pk-card-rank').textContent,suit:c.querySelector('.pk-card-suit').textContent};});A(info.ratio>.83&&info.width>.66,'Рисунок занимает основную площадь карты');A.equal(info.opacity,'1');A(info.loaded);A(info.rank&&info.suit);}
A(await p.locator('#экран-игры').evaluate(e=>e.scrollWidth<=e.clientWidth+1));if(width===390||width===1440)await p.screenshot({path:`tests/снимки/покер-фигуры-${width}.png`,fullPage:true});}
// Все 12 файлов должны существовать и декодироваться, независимо от раздачи.
for(const r of ['валет','дама','король'])for(const suit of ['трефы','бубны','черви','пики'])A(await p.evaluate(async src=>{const i=new Image();i.src=src;await i.decode();return i.naturalWidth>0;},`img/дурак/${r}-${suit}.jpg`));
A.deepEqual(errors,[]);console.log('Покер: крупные J/Q/K, читаемые индексы, 12 изображений, 4 размера экрана — OK');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
