'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {создать}=require('../server/популярность');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'catalog-stats-')),file=path.join(dir,'data.json');
const stats=создать(file),start=Date.now(),event=(n,seconds)=>({сеанс:'session-123',номер:n,секунд:seconds});
assert(stats.учесть('123','катан',event(0,0),start));
assert(stats.учесть('123','катан',event(1,30),start+30000));
assert(!stats.учесть('123','катан',event(1,30),start+31000),'duplicate must not count');
assert(stats.учесть('123','монополия',event(0,30),start+30000));
assert.equal(stats.сводка(start+30000).find(r=>r.game==='монополия').seconds,0,'parallel tabs cannot add time');
assert(stats.учесть('123','катан',event(2,0),start+600000));
assert.equal(stats.сводка(start+600000).find(r=>r.game==='катан').seconds,30,'hidden time does not count');
assert.equal(stats.сводка(start+600000).find(r=>r.game==='катан').launches,1,'reloads/resumes do not inflate visits');
stats.учесть('123','катан',event(3,0),start+2400000);
assert.equal(stats.сводка(start+2400000)[0].launches,2);
assert(!stats.учесть('123','unknown',event(0,0),start));
assert(!stats.учесть('123','катан',event(5,999999),start));
assert(stats.учесть('456','2048',event(0,0),start+2400000));
assert.equal(stats.сводка(start+2400000).find(r=>r.game==='2048').launches,1);
assert(stats.учесть('789','судоку',event(0,0),start+2400000));
assert.equal(stats.сводка(start+2400000).find(r=>r.game==='судоку').launches,1);
stats.дописать();assert.deepEqual(создать(file).сводка(start+2400000),stats.сводка(start+2400000));
assert(stats.сводка(start+32*86400000).every(r=>r.seconds===0&&r.launches===0));
fs.rmSync(dir,{recursive:true});
console.log('Popularity: deduplication, visible time, multi-tab cap, persistence and 30-day window OK');
