'use strict';
const A=require('node:assert/strict'),P=require('../игры/покер/покер-правила'),{chromium,безTelegram}=require('./браузер-робот');
(async()=>{const b=await chromium.launch();try{const p=await b.newPage();await безTelegram(p);const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.POKER_TEST_URL||'http://127.0.0.1:8137/покер.html');await p.locator('#pk-bots').click();await p.locator('#pk-count').selectOption('6');await p.locator('#pk-start').click();await p.waitForTimeout(600);
const g=P.create(6,79);while(g.turn!==0)P.action(g,g.turn,{type:'call'});const v=P.view(g,0);
await p.evaluate(v=>ИграПоСети.показатьВид({код:'test-poker',версия:1,покер:v}),v);
for(const [width,height]of [[320,740],[390,844],[820,1180],[844,390],[1024,768],[1440,900]]){await p.setViewportSize({width,height});await p.waitForTimeout(450);const table=await p.locator('#pk-table').boundingBox();if(width<=390)A.equal(Math.round(table.width),width);const overflow=await p.locator('#экран-игры').evaluate(e=>e.scrollWidth>e.clientWidth+1);A(!overflow,'Горизонтальная прокрутка '+width);
const boxes=await p.evaluate(()=>['pk-hand','pk-board','pk-self-info'].map(id=>{const r=document.getElementById(id).getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,id};}));for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],c=boxes[j];A(!(a.x<c.right-1&&c.x<a.right-1&&a.y<c.bottom-1&&c.y<a.bottom-1),a.id+' перекрывает '+c.id+' '+width);}
await p.locator('#pk-actions').getByRole('button',{name:'Повысить',exact:true}).click();await p.locator('#pk-presets').getByRole('button',{name:'Ва-банк',exact:true}).click();A.equal(Number(await p.locator('#pk-range').inputValue()),v.legal.max);A.match(await p.locator('#pk-raise-confirm').innerText(),/Ва-банк/);await p.screenshot({path:`tests/снимки/покер-${width}.png`,fullPage:true});await p.locator('#pk-actions').getByRole('button',{name:'Повысить',exact:true}).click();}
A.deepEqual(errors,[]);console.log('Покер: 6 игроков, телефон 320/390, планшет 820, компьютер 1440, ширина стола, карты и ставки — OK');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
