'use strict';
const A=require('node:assert/strict'),{chromium,безTelegram}=require('./браузер-робот'),server=require('../server/сервер').создатьСервер();
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch(),pages=[],errors=[];
const req=async(path,body)=>{const r=await fetch(base+'/'+encodeURIComponent(path),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});A.equal(r.status,200);return r.json();};
const getView=async key=>{const r=await req('состояние',key);return r.состояние||r;};
try{
 for(const viewport of [{width:390,height:844},{width:1440,height:900}]){const p=await browser.newPage({viewport});pages.push(p);await безTelegram(p);p.on('pageerror',e=>errors.push(e.message));await p.route('https://poker-audit.invalid/**',async route=>{try{const u=new URL(route.request().url()),response=await route.fetch({url:base+u.pathname+u.search,headers:{...route.request().headers(),origin:base}});await route.fulfill({response,headers:{...response.headers(),'access-control-allow-origin':new URL(p.url()).origin}});}catch{await route.abort().catch(()=>{});}});await p.goto('http://127.0.0.1:8137/покер.html?сервер='+encodeURIComponent('https://poker-audit.invalid'));}
 console.log('Открыты два браузера');const [host,guest]=pages;await host.locator('#pk-friends').click();await host.locator('#pk-count-online').getByRole('button',{name:'2',exact:true}).click();const created=host.waitForResponse(r=>decodeURIComponent(new URL(r.url()).pathname)==='/создать'&&r.request().method()==='POST');await host.locator('#кнопка-создать-игру').click();const room=await (await created).json(),keys=[{код:room.код,пропуск:room.пропуск}];
 await guest.locator('#pk-friends').click();await guest.locator('#кнопка-войти-по-коду').click();await guest.locator('#поле-кода').fill(room.код);const entered=guest.waitForResponse(r=>decodeURIComponent(new URL(r.url()).pathname)==='/войти'&&r.request().method()==='POST');await guest.locator('#кнопка-войти').click();const joined=await (await entered).json();keys.push({код:room.код,пропуск:joined.пропуск});
 console.log('Друг вошёл по коду');await host.locator('#комната-начать').click();for(const p of pages)await p.locator('#экран-игры.экран--виден').waitFor();
 let count=0;
 while(count++<100){const state=await getView(keys[0]),v=state.покер;if(v.phase==='finished')break;const who=v.turn,p=pages[who],own=(await getView(keys[who])).покер;
  const played=p.waitForResponse(r=>decodeURIComponent(new URL(r.url()).pathname)==='/ход'&&r.request().postDataJSON()?.действие==='покер');
  if(own.legal.next){await p.getByRole('button',{name:'Раздать карты',exact:true}).click();await played;continue;}
  await p.waitForFunction(()=>document.getElementById('pk-status').textContent.includes('Ваш ход'));
  if(own.legal.raise){const raise=p.locator('#pk-actions').getByRole('button',{name:own.legal.max<own.legal.min?'Ва-банк':'Повысить',exact:true});await raise.click();if(own.legal.max>=own.legal.min){await p.locator('#pk-presets').getByRole('button',{name:'Ва-банк',exact:true}).click();await p.locator('#pk-raise-confirm').click();}}
  else await p.locator('#pk-actions').getByRole('button',{name:own.legal.check?'Чек':/^Уравнять /}).click();await played;
 }
 console.log('Турнир завершён',count);A(count<100);for(const p of pages){await p.getByRole('button',{name:'Реванш',exact:true}).waitFor();A(await p.locator('#pk-showdown').isVisible());}
 await host.getByRole('button',{name:'Реванш',exact:true}).click();await host.getByRole('button',{name:'Вы готовы к реваншу',exact:true}).waitFor();A(await host.getByRole('button',{name:'Вы готовы к реваншу',exact:true}).isDisabled());await guest.getByRole('button',{name:'Реванш',exact:true}).click();
 for(const p of pages)await p.waitForFunction(()=>document.getElementById('pk-round').textContent.startsWith('Раздача 1'));
 console.log('Реванш начат');const hand=await host.locator('#pk-hand [data-card]').evaluateAll(es=>es.map(e=>e.dataset.card));await host.reload();await host.locator('#кнопка-вернуться-в-игру').click();await host.locator('#экран-игры.экран--виден').waitFor();A.deepEqual(await host.locator('#pk-hand [data-card]').evaluateAll(es=>es.map(e=>e.dataset.card)),hand);A.equal(await host.locator('.pk-mini-hand .back').count(),2);
 await host.locator('#pk-help').click();await host.getByRole('button',{name:'Покинуть стол',exact:true}).click();await host.getByRole('button',{name:'Покинуть',exact:true}).click();A(await host.locator('#экран-лобби').isVisible());await guest.locator('#pk-status').getByText('Партия отменена',{exact:true}).waitFor();A.equal((await getView(keys[1])).покер.phase,'finished');A.equal(await guest.getByRole('button',{name:'Реванш',exact:true}).count(),0);A(await guest.locator('#pk-actions').getByRole('button',{name:'В лобби',exact:true}).isVisible());await req('выйти',keys[1]);
 A.deepEqual(errors,[]);console.log('Два независимых браузера: создание, вход по коду, ва-банк кнопками, итог, согласованный реванш, возврат после перезагрузки, выход соперника — OK');
 for(const p of pages)await p.unrouteAll({behavior:'ignoreErrors'});
}finally{for(const p of pages){await p.screenshot({path:'tests/снимки/покер-два-браузера-'+pages.indexOf(p)+'.png',fullPage:true}).catch(()=>{});await p.unrouteAll({behavior:'ignoreErrors'});}await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
