(function(){'use strict';
 const P=window.ПокерПравила,B=window.ПокерБот,$=id=>document.getElementById(id),KEY='poker-match-v1';
 let game=null,v=null,network=null,online=false,timer=null,busy=false,lastVersion=-1,raiseOpen=false,sound=true,audio=null,record=null,lastEvent=-1;
 let prefs={n:4,level:'обычный'},parked=false;
 function syncParked(){document.body.classList.toggle('pk-network-parked',parked);$('pk-online-resume').classList.toggle('скрыт',!parked||!network);}
 function leaveOnline(){window.Сеть?.покинутьПартию();online=false;network=null;parked=false;syncParked();}
 function chooseLocal(next){if(!network){next();return;}const body=modal('Покинуть онлайн-стол?');body.append(el('p','Чтобы перейти к ботам, нужно выйти из онлайн-партии. В игре с несколькими участниками ваше место займёт бот.'),btn('Выйти и продолжить',()=>{leaveOnline();close();next();},'pk-gold'),btn('Остаться за столом',()=>{close();parked=false;online=true;v=network.покер;show('экран-игры');render();}));}
 const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
 const num=n=>Number(n).toLocaleString('ru-RU');
 const name=i=>i===v?.me?'Вы':v?.names?.[i]||`Бот ${i}`;
 const btn=(text,fn,cls='')=>{const b=el('button',text,'pk-button '+cls);b.onclick=fn;return b;};
 const phases={preflop:'Первые ставки',flop:'Флоп · три общие карты',turn:'Тёрн · четвёртая карта',river:'Ривер · последняя карта',between:'Раздача завершена',finished:'Партия завершена'};
 function show(id){if(id==='экран-меню')id='экран-лобби';document.querySelectorAll('.экран').forEach(e=>e.classList.toggle('экран--виден',e.id===id));clearTimeout(timer);window.Телеграм?.показатьСтрелку(back);$('pk-resume').classList.toggle('скрыт',!game||game.phase==='finished');syncParked();}
 function modal(title){$('pk-dialog-title').textContent=title;$('pk-dialog-body').replaceChildren();if(!$('pk-dialog').open)$('pk-dialog').showModal();return $('pk-dialog-body');}
 function close(){$('pk-dialog').close();schedule();}
 function back(){if($('pk-dialog').open){close();return;}if($('экран-игры').classList.contains('экран--виден')){const body=modal('Вернуться в лобби?');body.append(el('p',online?'Партия онлайн продолжается. По истечении времени сервер сделает чек или пас.':'Партия с ботами сохранится. Вы сможете продолжить с этого места.'),btn('В лобби',()=>{parked=online;close();show('экран-лобби');}),btn('Остаться за столом',close,'pk-gold'));}else if($('экран-лобби').classList.contains('экран--виден'))location.href='index.html';else show('экран-лобби');}
 function beep(){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),gain=audio.createGain();o.type='sine';o.frequency.setValueAtTime(740,audio.currentTime);o.frequency.exponentialRampToValueAtTime(390,audio.currentTime+.08);gain.gain.setValueAtTime(.045,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.1);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+.11);}catch{}}
 function save(){try{localStorage.setItem('poker-prefs-v1',JSON.stringify({...prefs,sound}));if(record)localStorage.setItem(KEY,JSON.stringify(record));}catch{$('pk-error').textContent='Не удалось сохранить партию на устройстве.';}}
 function fresh(){prefs.n=Number($('pk-count').value);prefs.level=$('pk-level').value;const seed=crypto.getRandomValues(new Uint32Array(1))[0];game=P.create(prefs.n,seed);record={version:1,rules:2,n:prefs.n,seed,actions:[]};online=false;parked=false;lastVersion=-1;lastEvent=-1;save();show('экран-игры');render();}
 function card(c,winning=false){
   const e=el('div',undefined,'pk-card'+(c===null?' back':c===undefined?' empty':P.suit(c)===1||P.suit(c)===2?' red':''));
   if(c==null){e.setAttribute('aria-label',c===null?'Закрытая карта':'Карта ещё не открыта');return e;}
   const r=P.rank(c),s=P.suit(c),rank=r<11?String(r):['J','Q','K','A'][r-11],suit=['♣','♦','♥','♠'][s];e.dataset.card=c;e.setAttribute('aria-label',rank+' '+['треф','бубен','червей','пик'][s]);
   e.append(el('span',rank,'pk-card-rank'),el('span',suit,'pk-card-suit'),el('span',rank+suit,'pk-card-corner'));
   if(r>=11&&r<=13){e.classList.add('face');const img=el('img');img.src='img/дурак/'+['валет','дама','король'][r-11]+'-'+['трефы','бубны','черви','пики'][s]+'.jpg';img.alt='';const art=el('span',undefined,'pk-face-art');art.append(img);e.append(art);}
   if(winning)e.classList.add('winning');return e;
 }
 function avatar(i){const e=el('span',undefined,'pk-avatar');const person=online?(network?.портреты?.[i]||{этоЯ:i===v.me,этоБот:!!v.bots?.[i]}):{этоЯ:i===0,этоБот:i!==0};if(person.этоБот){e.classList.add('pk-bot-avatar');e.style.setProperty('--px',(i%3)*50+'%');e.style.setProperty('--py',Math.floor(i/3)*100+'%');e.title='Бот';}window.МойАватар?.игрок(e,person);return e;}
 function resultText(){if(!v.result)return '';const winners=[...new Set(v.result.pots.filter(p=>!p.refund).flatMap(p=>p.winners))];return winners.map(i=>`${name(i)} забирает ${num(v.result.wins[i]-v.result.pots.filter(p=>p.refund&&p.winners.includes(i)).reduce((sum,p)=>sum+p.amount,0))}${v.result.hands[i]?' · '+v.result.hands[i].label:''}`).join(' / ');}
 function render(){
   if(!online)v=P.view(game,0);if(!v)return;const changed=lastVersion!==v.version;if(changed){lastVersion=v.version;raiseOpen=false;beep();}
   $('pk-round').textContent=`Раздача ${v.hand} · Блайнды ${num(v.bb/2)} / ${num(v.bb)}`;
   $('pk-pot-label').textContent=v.result?'Разыграно':'Банк';$('pk-pot').textContent=num(v.result?v.result.pots.filter(p=>!p.refund).reduce((s,p)=>s+p.amount,0):v.pot);$('pk-pot').classList.toggle('pk-bet-flight',changed);
   const winning=v.result?.hands?.flatMap((h,i)=>v.result.wins[i]>0?h?.cards||[]:[])||[];
   const board=$('pk-board');for(let j=0;j<5;j++){const c=v.board[j],existing=board.children[j];if(existing?.dataset.card===String(c)&&c!==undefined){existing.classList.toggle('winning',winning.includes(c));continue;}const node=card(c,winning.includes(c));if(existing)existing.replaceWith(node);else board.append(node);}
   $('pk-street').textContent=phases[v.phase];$('pk-result').textContent=resultText();$('pk-showdown').classList.toggle('скрыт',!v.result);$('pk-hand').classList.toggle('folded',v.players[v.me].folded);
   const seats=$('pk-seats');seats.replaceChildren();const rivals=v.players.map((p,i)=>i).filter(i=>i!==v.me);const positions={1:[3],2:[2,4],3:[2,3,4],4:[1,2,4,5],5:[1,2,3,4,5]}[rivals.length];
   rivals.forEach((i,j)=>{const p=v.players[i],seat=el('div',undefined,'pk-seat'+(i===v.turn?' active':'')+(p.folded?' folded':'')+(p.out?' out':''));seat.dataset.player=i;seat.dataset.pos=positions[j];seat.append(avatar(i));const title=el('b',name(i),'pk-seat-name');if(i===v.button)title.append(el('span','D','pk-dealer'));if(v.bots?.[i]&&!/^Бот(?:\s|$)/u.test(name(i)))title.append(el('small',' · бот'));seat.append(title,el('span',num(p.stack),'pk-stack'),el('span',p.out?'Выбыл':i===v.turn&&!v.result?'Думает…':p.action||'В игре','pk-seat-action'));const mini=el('div',undefined,'pk-mini-hand');p.hole.forEach(c=>mini.append(card(c)));seat.append(mini);if(p.bet)seat.append(el('div','● '+num(p.bet),'pk-seat-bet'));seats.append(seat);});
   const own=v.players[v.me],hand=$('pk-hand');if(Array.from(hand.children,e=>Number(e.dataset.card)).join(',')!==own.hole.join(',')){hand.replaceChildren(...own.hole.map(c=>card(c,winning.includes(c))));}else for(const e of hand.children)e.classList.toggle('winning',winning.includes(Number(e.dataset.card)));
   const self=$('pk-self-info');self.replaceChildren(avatar(v.me));const info=el('span',undefined,'pk-self-info');info.append(el('small',`Вы${v.button===v.me?' · дилер':''}${own.bet?' · ставка '+num(own.bet):''}`),el('b',num(own.stack)));self.append(info);self.parentElement.classList.toggle('active',v.turn===v.me);
   $('pk-combination').textContent=own.out?'Вы выбыли из турнира':v.board.length>=3?P.evaluate([...own.hole,...v.board]).label:'Ваши две закрытые карты';
   actions();$('pk-raise-confirm').disabled=busy||!v.legal.raise;$('pk-range').disabled=busy||!v.legal.raise;if(busy)document.querySelectorAll('#pk-actions button,#pk-raise button,#pk-raise input').forEach(b=>b.disabled=true);if(changed)animateChips();schedule();
 }
 function animateChips(){
   const e=v.events.at(-1);if(!e||e.id===lastEvent)return;lastEvent=e.id;if(!['call','raise'].includes(e.type)||!e.amount||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
   const table=$('pk-table'),from=e.player===v.me?$('pk-self-info'):table.querySelector('[data-player="'+e.player+'"]'),to=$('pk-pot');if(!from)return;
   const a=from.getBoundingClientRect(),b=to.getBoundingClientRect(),r=table.getBoundingClientRect(),chip=el('img',undefined,'pk-flying-chips');chip.src='img/покер/фишки-v1.webp';chip.alt='';chip.style.setProperty('--from-x',(a.x+a.width/2-r.x)+'px');chip.style.setProperty('--from-y',(a.y+a.height/2-r.y)+'px');chip.style.setProperty('--to-x',(b.x+b.width/2-r.x)+'px');chip.style.setProperty('--to-y',(b.y+b.height/2-r.y)+'px');table.append(chip);setTimeout(()=>chip.remove(),800);
 }
 function actions(){const l=v.legal,body=$('pk-actions');body.replaceChildren();$('pk-raise').classList.toggle('скрыт',!raiseOpen||!l.raise);
   const status=$('pk-status');status.replaceChildren();
   if(v.phase==='finished'){status.append(el('b',v.winner<0?'Партия отменена':v.winner===v.me?'Стол ваш. Победа!':`${name(v.winner)} выигрывает партию`));if(v.interrupted){status.append(el('small',v.winner<0?'Соперник покинул стол. Победитель не назначен.':'Соперник покинул стол. Партия завершена.'));body.append(btn('В лобби',()=>{leaveOnline();show('экран-лобби');},'pk-gold pk-wide'));return;}const again=btn(online?(network?.яХочуЕщё?'Вы готовы к реваншу':'Реванш'):'Ещё партия',()=>online?rematch():fresh(),'pk-gold pk-wide');again.disabled=busy||!!(online&&network?.яХочуЕщё);body.append(again);if(online&&network?.яХочуЕщё)status.append(el('small','Ждём согласия остальных игроков.'));else if(online&&(network?.соперникХочетЕщё||network?.застолом?.some(p=>p.хочетЕщё&&!p.этоЯ&&!p.этоБот)))status.append(el('small','Соперник предлагает реванш.'));finishRecord();return;}
   if(v.players[v.me].out){status.append(el('b','Вы выбыли из турнира'),el('small','Можно наблюдать за оставшимися игроками или выйти в лобби.'));body.append(btn('В лобби',()=>{parked=online;show('экран-лобби');},'pk-wide'));if(!online){body.append(btn('Новая партия',fresh,'pk-gold pk-wide'));finishRecord();}return;}
   if(v.phase==='between'){status.append(el('b','Следующая раздача'));if(l.next)body.append(btn('Раздать карты',()=>act({type:'next'}),'pk-gold pk-wide'));else status.append(el('small',online?'Новая раздача начнётся автоматически':`Раздаёт ${name(v.turn)}`));return;}
   if(v.turn!==v.me){status.append(el('b',`${name(v.turn)} думает…`),el('small',v.players[v.me].folded?'Вы спасовали. Следите за раздачей.':'Ваши карты остаются закрытыми.'));return;}
   status.append(el('b','Ваш ход'),el('small',l.toCall?`Уравнять ${num(l.call)} · Банк ${num(v.pot)}`:'Можно сделать чек — без ставки'));
   if(online){const clock=el('span','','pk-countdown');clock.id='pk-countdown';status.append(clock);updateClock();}
   body.append(btn('Пас',()=>act({type:'fold'}),'pk-fold'),btn(l.check?'Чек':`Уравнять ${num(l.call)}`,()=>act({type:l.check?'check':'call'})));
   const raise=btn(l.max<l.min?'Ва-банк':'Повысить',()=>{if(l.max<l.min){act({type:'allin'});return;}raiseOpen=!raiseOpen;actions();},'pk-gold');raise.disabled=!l.raise||busy;body.append(raise);
   if(raiseOpen&&l.raise){const range=$('pk-range');range.min=Math.min(l.min,l.max);range.max=l.max;range.value=Math.min(l.max,Math.max(l.min,Number(range.value)));updateRaise();const presets=$('pk-presets');presets.replaceChildren();for(const [label,to]of [['Мин.',l.min],['½ банка',v.currentBet+Math.round((v.pot+l.call)/2)],['Банк',v.currentBet+v.pot+l.call],['Ва-банк',l.max]]){const b=el('button',label);b.onclick=()=>{range.value=Math.min(l.max,Math.max(l.min,to));updateRaise();};presets.append(b);}}
 }
 function updateRaise(){$('pk-raise-value').textContent=num($('pk-range').value);$('pk-raise-confirm').textContent=Number($('pk-range').value)===v.legal.max?'Ва-банк · '+num(v.legal.max):'Повысить до '+num($('pk-range').value);}
 async function act(move,player=v?.me){if(busy)return;busy=true;$('pk-error').textContent='';document.querySelectorAll('#pk-actions button,#pk-raise button,#pk-raise input').forEach(b=>b.disabled=true);try{if(online){const r=await window.Сеть.отправитьХод({действие:'покер',move:{...move,version:v.version}});if(!r?.принято)throw Error(r?.причина||'Нет связи. Повторите действие.');}else{P.action(game,player,move);record.actions.push({player,move});save();}raiseOpen=false;}catch(e){$('pk-error').textContent=e.message;}finally{busy=false;if(!parked&&$('экран-игры').classList.contains('экран--виден'))render();}}
 function schedule(){clearTimeout(timer);if(!v||!$('экран-игры').classList.contains('экран--виден')||$('pk-dialog').open||online||v.phase==='finished')return;if(v.turn!==0){timer=setTimeout(()=>{const i=game.turn;act(B.move(P.view(game,i),prefs.level),i);},v.phase==='between'?4000:1700+Math.random()*800);}}
 function finishRecord(){if(online||!record||record.recorded)return;record.recorded=true;try{const history=JSON.parse(localStorage.getItem('poker-results-v1')||'[]');history.unshift({at:new Date().toISOString(),won:v.winner===0,hands:v.hand,players:v.players.length,level:prefs.level});localStorage.setItem('poker-results-v1',JSON.stringify(history.slice(0,30)));save();}catch{}}
 function rules(){const body=modal('Две карты. Лучшие пять.');body.append(el('p','У вас две закрытые карты. На столе открываются пять общих. Соберите лучшую комбинацию из любых пяти карт — или заставьте соперников спасовать.'),el('p','Чек — пропустить без ставки. Уравнять — добавить до ставки соперника. Повысить — увеличить общую ставку. Пас — выйти из этой раздачи. Ва-банк — поставить все оставшиеся фишки.'));
   const examples=['A · J · 9 · 7 · 3','A · A · 9 · 7 · 3','A · A · 9 · 9 · 3','A · A · A · 7 · 3','5 · 6 · 7 · 8 · 9','Пять карт одной масти','Тройка и пара','Четыре одинаковых достоинства','Пять подряд одной масти'];for(let i=8;i>=0;i--){const row=el('div',undefined,'pk-combo-row');row.append(el('b',P.LABELS[i]),el('span',examples[i]));body.append(row);}body.append(el('p','Одинаковые комбинации сравниваются по старшим картам. При точном равенстве банк делится. Когда фишек для уравнивания не хватает, создаётся отдельный банк.'),btn('Понятно',close,'pk-gold'));}
 function menu(){const body=modal('За вашим столом');if(online)body.append(btn('Покинуть стол',()=>{const b=modal('Покинуть стол?');b.append(el('p','В партии с несколькими участниками за вас доиграет бот. Уход после начала игры может засчитываться как поражение.'),btn('Покинуть',()=>{leaveOnline();close();show('экран-лобби');}),btn('Остаться',close,'pk-gold'));}));body.append(btn('Как играть',rules),btn('Мои результаты',()=>{const b=modal('Мои партии с ботами');let h=[];try{h=JSON.parse(localStorage.getItem('poker-results-v1')||'[]');}catch{}if(!h.length)b.append(el('p','Здесь появятся завершённые партии.'));h.forEach(x=>b.append(el('p',`${new Date(x.at).toLocaleDateString('ru-RU')} · ${x.won?'Победа':'Поражение'} · ${x.hands} раздач · ${x.players} игроков`)));}),btn('В лобби',()=>{close();back();}));}
 async function rematch(){if(busy)return;busy=true;$('pk-error').textContent='';render();try{const reply=await window.Сеть.отправитьХод({действие:'ещё'});if(!reply?.принято)throw Error(reply?.причина||'Не удалось предложить реванш. Попробуйте ещё раз.');}catch(e){$('pk-error').textContent=e.message;}finally{busy=false;if(!parked)render();}}
 function showdown(){if(!v.result)return;const body=modal('Итоги раздачи');body.append(el('p',resultText()));const common=el('div',undefined,'pk-showdown-cards');v.board.forEach(c=>common.append(card(c)));body.append(common);v.result.pots.forEach((p,i)=>body.append(el('p',p.refund?'Возврат неуравненной ставки: '+name(p.winners[0])+' · '+num(p.amount):'Банк '+(i+1)+': '+num(p.amount)+' → '+p.winners.map(name).join(', '))));v.players.forEach((p,i)=>{if(!p.hole.length||p.hole.some(c=>c===null))return;const row=el('div',undefined,'pk-showdown-row');row.append(el('b',name(i)+(p.folded?' · пас':'')),el('small',v.result.hands[i]?.label||'Карты не раскрывались'));const hand=el('div',undefined,'pk-showdown-cards');p.hole.forEach(c=>hand.append(card(c,v.result.hands[i]?.cards.includes(c))));row.append(hand);body.append(row);});body.append(btn('Понятно',close,'pk-gold'));}
 $('pk-showdown').onclick=showdown;
 function updateClock(){const clock=$('pk-countdown');if(clock&&network?.покер?.deadline)clock.textContent=' · '+Math.max(0,Math.ceil((network.покер.deadline-Date.now())/1000))+' с';}
 $('pk-range').oninput=updateRaise;$('pk-raise-confirm').onclick=()=>act({type:'raise',to:Number($('pk-range').value)});$('pk-close').onclick=close;$('pk-dialog').addEventListener('close',schedule);
 document.querySelectorAll('[data-back]').forEach(b=>b.onclick=back);document.querySelectorAll('[data-rules]').forEach(b=>b.onclick=rules);
 $('pk-bots').onclick=()=>chooseLocal(()=>show('pk-setup'));$('pk-friends').onclick=()=>{$('pk-public').checked=false;show('экран-друга');};$('pk-start').onclick=()=>{if(game&&game.phase!=='finished'){const b=modal('Новая партия?');b.append(el('p','Текущая партия с ботами будет заменена.'),btn('Начать новую',()=>{close();fresh();},'pk-gold'),btn('Продолжить текущую',()=>{close();online=false;show('экран-игры');render();}));}else fresh();};
 $('pk-resume').onclick=()=>chooseLocal(()=>{online=false;lastVersion=-1;show('экран-игры');render();});$('pk-online-resume').onclick=()=>{parked=false;online=true;v=network.покер;show('экран-игры');render();};$('pk-profile').onclick=()=>window.ЭкранПрофиля.открыть('покер');$('pk-help').onclick=menu;
 $('pk-log').onclick=()=>{const b=modal('Ход раздачи');const verbs={deal:'Новая раздача',street:'Общие карты открыты',result:'Итог раздачи',fold:'пас',check:'чек',call:'уравнял',raise:'повысил'};v.events.filter(e=>e.hand===v.hand).forEach(e=>b.append(el('p',`${e.player>=0?name(e.player)+': ':''}${verbs[e.type]||e.type}${e.amount?' · '+num(e.amount):''}`)));if(v.result)b.append(el('p',resultText()));};
 $('pk-sound').onclick=()=>{sound=!sound;$('pk-sound').textContent='Звук '+(sound?'вкл':'выкл');$('pk-sound').setAttribute('aria-pressed',String(sound));save();};
 for(let n=2;n<=6;n++){const b=el('button',String(n));b.setAttribute('aria-pressed',String(n===4));b.onclick=()=>{$('покер-мест-друга').value=n;$('pk-count-online').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));};$('pk-count-online').append(b);}
 $('кнопка-комната-назад').onclick=()=>$('кнопка-комната-отмена').click();$('кнопка-комната-ещё').onclick=menu;
 $('экран-лобби').insertBefore($('кнопка-вернуться-в-игру'),$('pk-resume'));
 const nav=document.querySelector('.нижние-вкладки');if(window.НижниеВкладки){nav.innerHTML=window.НижниеВкладки.вкладкиНабора('лобби-деберц').map((x,i)=>window.НижниеВкладки.кнопкаHTML({...x,id:'pk-nav-'+i})).join('');$('pk-nav-0').onclick=()=>location.href='index.html';$('pk-nav-1').onclick=()=>window.ЭкранРейтинга.открыть('покер');$('pk-nav-2').onclick=()=>window.ЭкранПрофиля.открыть('покер');}
 window.ИграПоСети={начать(){online=true;parked=false;clearTimeout(timer);},показатьВид(state){if(!state.покер)return;if(network?.код===state.код&&state.версия<network.версия)return;if(network?.код!==state.код||network?.сыграноПартий!==state.сыграноПартий)lastVersion=-1;network=state;online=true;v=state.покер;if(!parked){show('экран-игры');render();}else syncParked();},показатьСвязь(text){$('строка-связи').textContent=text||'';$('строка-связи').classList.toggle('скрыт',!text);},экран:show,вМеню(){online=false;network=null;parked=false;show('экран-лобби');},идёт:()=>online};
 try{const saved=JSON.parse(localStorage.getItem('poker-prefs-v1')||'null');if(saved){if([2,3,4,5,6].includes(saved.n))prefs.n=saved.n;if(['лёгкий','обычный','сложный'].includes(saved.level))prefs.level=saved.level;sound=saved.sound!==false;}$('pk-count').value=prefs.n;$('pk-level').value=prefs.level;const r=JSON.parse(localStorage.getItem(KEY)||'null');if(r?.version===1&&Array.isArray(r.actions)&&r.actions.length<50000){const restored=P.create(r.n,r.seed,false,r.rules||1);r.actions.forEach(a=>P.action(restored,a.player,a.move));P.assert(restored);game=restored;record=r;}}catch{$('pk-lobby-error').textContent='Сохранённую партию не удалось восстановить. Можно начать новую.';}
 $('pk-sound').textContent='Звук '+(sound?'вкл':'выкл');$('pk-sound').setAttribute('aria-pressed',String(sound));
 window.МойАватар?.игрок(document.querySelector('#pk-profile .pk-avatar'),{этоЯ:true});
 window.addEventListener('load',()=>{$('pk-name').textContent=window.Телеграм?.имяИгрока?.()||'Вы';window.Телеграм?.отперетьПоворот?.();window.Телеграм?.кнопкаНастроек?.(menu);});setInterval(updateClock,500);show('экран-лобби');
})();
