'use strict';
(()=>{
 const G=window.CasualGame,U=window.CasualCore,$=id=>document.getElementById(id),KEY='casual-'+G.id+'-v1',BEST=KEY+'-best';
 const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true;}catch{return false;}};
 let saved=read(KEY,null),state=null,history=[],mode=G.modes[0].id,playing=false,presenting=false,paused=false,active=true,view={},lastTick=performance.now(),lastAction=performance.now(),best=read(BEST,{});
 if(!best||typeof best!=='object'||Array.isArray(best))best={};
 try{if(saved?.state&&G.validate(saved.state)){state=saved.state;for(const k of ['score','moves','seconds','aids'])if(!Number.isFinite(state[k])||state[k]<0)state[k]=0;history=Array.isArray(saved.history)?saved.history.filter(G.validate).slice(-80):[];mode=state.mode;}}catch{state=null;}
 /* Рейтинг по лучшему счёту (план Э4.7). Партия игры со счётом берёт билет на старте и сдаёт итог ОДИН раз:
    ручка обнуляется при сдаче, поэтому повторный вызов end() (он бывает у игр с анимацией) в сеть не уходит.
    Ключ игры и режимы — только из общее/js/игры-реестр.js (запись со «счёт» и страницей этой игры). Игры там нет,
    режим не рейтинговый (сюжетные уровни трёх в ряд), нет Telegram или общее/js/сеть.js — тихо ничего, как раньше.
    Счёт с подсказками не сдаём — то же правило, что у личного рекорда «без помощи». */
 let ticket=null;
 function ratedGame(){if(G.record!=='score')return null;try{return window.ИгрыРеестр?.все?.().find(g=>g.страница===G.id+'.html'&&g.счёт)||null;}catch{return null;}}
 function takeTicket(){const game=ratedGame();if(!game||!state||!window.ОчкиРейтинга?.взятьБилетСчёта||!game.счёт.режимы.some(m=>m.ключ===state.mode))return;try{ticket=window.ОчкиРейтинга.взятьБилетСчёта(game.ключ,state.mode);}catch{ticket=null;}}
 function submitScore(){const handle=ticket;ticket=null;if(!handle||!state||state.aids||!(state.score>0))return;try{window.ОчкиРейтинга.сдатьСчёт(handle,{счёт:Math.floor(state.score)});}catch{}}
 const time=n=>{n=Math.floor(n);return (n>=3600?Math.floor(n/3600)+':':'')+String(Math.floor(n/60)%(n>=3600?60:100000)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');};
 function save(){if(state&&!write(KEY,{state,history}))$('save-status').textContent='Сохранение недоступно. Не закрывайте страницу до конца партии.';}
 function message(s){$('message').textContent=s;}
 function lobby(){document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('continue').hidden=!state||state.won||state.lost;$('continue').textContent=state?'Продолжить · '+time(state.seconds):'Продолжить';G.onLobby?.(mode);const value=best[mode];$('record').textContent=Number.isFinite(value)?G.record==='time'?time(value):Math.floor(value).toLocaleString('ru-RU'):'—';}
 function close(){$('dialog').close();lastTick=performance.now();lastAction=performance.now();}
 function modal(title){$('dialog').classList.remove('studio-result');$('dialog-body').replaceChildren();const h=document.createElement('h2');h.id='dialog-title';h.textContent=title;$('dialog-body').append(h);if(!$('dialog').open)$('dialog').showModal();return $('dialog-body');}
 function text(body,value){const p=document.createElement('p');p.textContent=value;body.append(p);}
 function button(body,label,fn,style='primary'){const b=document.createElement('button');b.className=style;b.textContent=label;b.onclick=fn;body.append(b);return b;}
 function canPlay(){return playing&&!presenting&&!paused&&active&&!document.hidden&&!$('dialog').open&&!state.won&&!state.lost;}
 function render(){if(!state)return;view.cancelPointer?.();$('playfield').replaceChildren();$('game-tools').replaceChildren();$('metric-label').textContent='СЧЁТ';$('metric').textContent=state.score;$('timer').textContent=time(state.seconds);$('difficulty').textContent=G.modes.find(m=>m.id===state.mode)?.label||'';$('undo').hidden=!G.undo;$('undo').disabled=!history.length||state.won;
  const api={board:$('playfield'),view,send,message,redraw:render,modal,text,button,close,cell:(label,fn)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=fn;return b;},tool:(label,fn,on=false)=>{const b=document.createElement('button');b.textContent=label;b.classList.toggle('active',on);b.onclick=()=>{if(canPlay())fn();};$('game-tools').append(b);return b;},status:(label,value)=>{$('metric-label').textContent=label;$('metric').textContent=value;},aid:()=>{state.aids++;save();}};G.draw(state,api);window.CasualStudio?.update(G,state);$('window').classList.toggle('won',state.won);
 }
 /* «Похвастаться» (план штаб/план-похвастаться-ярлык.md, О4) и счёт партий для ярлыка на рабочий стол.
    Кнопка — только при победе в игре «на время», внутри Telegram и если на странице есть общее/js/похвастаться.js
    (у скрытых блоков, трёх в ряд и змейки его нет — кнопки там не будет). Имя игры — из window.ИграСтраницы
    (то же слово, что в общее/js/игры-реестр.js); секунды — целые, сервер другое не примет.
    Партию в ярлык отмечаем один раз на состояние: end() у игр с анимацией зовут дважды. */
 const inTelegram=()=>{try{return Boolean(window.Telegram?.WebApp?.initData);}catch{return false;}};
 let counted=null;
 function countGame(){if(counted===state)return;counted=state;try{window.Ярлык?.партияСыграна?.(window.ИграСтраницы);}catch{}}
 function boastButton(body){const seconds=Math.floor(state.seconds);if(!state.won||G.record!=='time'||!window.ИграСтраницы||!(seconds>0)||!inTelegram()||typeof window.Сеть?.похвастаться!=='function')return;
  const b=button(body,'Похвастаться',()=>{if(b.disabled)return;b.disabled=true;b.textContent='Готовим…';let done=false;const finish=r=>{if(done)return;done=true;b.textContent=!r?'Не вышло':r.отправлено===true?'Отправлено':r.способ==='буфер'?'Ссылка скопирована':r.способ==='чат'?'Выбираем чат…':'Похвастаться';b.disabled=false;};
   try{Promise.resolve(window.Сеть.похвастаться({игра:window.ИграСтраницы,исход:'победа',мера:'секунд',значение:seconds})).then(finish,()=>finish(null));}catch{finish(null);}setTimeout(()=>finish(null),6000);},'secondary');}
 function end(show=true){submitScore();countGame();G.onFinish?.(state);const won=state.won,record=G.record==='time'?Math.floor(state.seconds):state.score,old=best[state.mode];if((won||G.record==='score')&&!state.aids&&(!Number.isFinite(old)||(G.record==='time'?record<old:record>old))){best[state.mode]=record;write(BEST,best);}if(!show)return;const body=modal(won?'Отличная партия!':G.lossTitle||'Партия завершена');const icon=document.createElement('div');icon.className='result-art';icon.textContent=won?'✦':'◈';body.append(icon);if(window.CasualStudio){$('dialog').classList.add('studio-result');icon.innerHTML=CasualStudio.medal(won); }text(body,`${G.title} · ${time(state.seconds)} · ходов: ${state.moves}${G.record==='score'?' · очки: '+state.score:''}.`);if(!won&&G.lossText)text(body,G.lossText);G.result?.(state,{body,text,button,startMode:id=>{mode=id;close();start(true);}});boastButton(body);if(!won&&G.undo&&history.length)button(body,'Отменить последний ход',()=>{close();undoLast();});button(body,'Сыграть ещё',()=>{close();start(true);});button(body,'К выбору режима',()=>{close();back();},'secondary');}
 function send(action){if(!canPlay())return false;const before=G.undo||G.animate||window.CasualStudio?U.clone(state):null,rects=capturePieces();if(!G.act(state,action))return false;if(before&&G.undo){delete before.frames;history.push(before);if(history.length>80)history.shift();}state.moves++;save();window.CasualStudio?.feedback(G,before,state,action);if(action.type!=='tick')window.Телеграм?.отклик?.('карта');if(G.animate&&!matchMedia('(prefers-reduced-motion: reduce)').matches){presenting=true;$('playfield').dataset.busy='true';$('playfield').inert=true;$('playfield').setAttribute('aria-busy','true');$('undo').disabled=true;$('new').disabled=true;if(state.won||state.lost)end(false);const current=state;Promise.resolve().then(()=>G.animate(before,current,$('playfield'))).catch(()=>{}).finally(()=>{presenting=false;delete $('playfield').dataset.busy;$('playfield').inert=paused;$('playfield').removeAttribute('aria-busy');$('new').disabled=false;if(state===current){render();if(state.won||state.lost)end(playing);}});}else{render();movePieces(rects);if(state.won||state.lost)end();}return true;}
 function capturePieces(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return [];return [...$('playfield').querySelectorAll('[data-card],[data-tile]')].map(el=>({id:el.dataset.card!=null?'card:'+el.dataset.card:'tile:'+el.dataset.tile,rect:el.getBoundingClientRect(),back:el.classList.contains('back-card'),ghost:el.dataset.tile!=null?el.cloneNode(true):null}));}
 function movePieces(previous){const current=new Map([...$('playfield').querySelectorAll('[data-card],[data-tile]')].map(el=>[el.dataset.card!=null?'card:'+el.dataset.card:'tile:'+el.dataset.tile,el]));for(const old of previous){const el=current.get(old.id);if(el){const r=el.getBoundingClientRect(),dx=old.rect.x-r.x,dy=old.rect.y-r.y;if(Math.abs(dx)+Math.abs(dy)>2)el.animate([{translate:dx+'px '+dy+'px'},{translate:'0 0'}],{duration:220,easing:'cubic-bezier(.2,.8,.2,1)'});else if(old.back&&!el.classList.contains('back-card'))el.animate([{transform:'perspective(600px) rotateY(75deg)',opacity:.4},{transform:'perspective(600px) rotateY(0)',opacity:1}],{duration:220});}else if(old.ghost){const ghost=old.ghost,r=old.rect,target=$('metric').getBoundingClientRect();ghost.classList.remove('selected-item','hint-cell');Object.assign(ghost.style,{position:'fixed',left:r.x+'px',top:r.y+'px',width:r.width+'px',height:r.height+'px',zIndex:'1000',pointerEvents:'none',margin:'0'});document.querySelector('.casual-app').append(ghost);ghost.animate([{translate:'0 0',opacity:1,scale:1},{translate:(target.x-r.x)+'px '+(target.y-r.y)+'px',opacity:0,scale:.2}],{duration:400,easing:'ease-in',fill:'forwards'}).finished.then(()=>ghost.remove(),()=>ghost.remove());}}}

 function screens(on){view.cancelPointer?.();view.swipeStart=null;playing=on;for(const [id,v]of [['экран-лобби',!on],['экран-игры',on]]){$(id).hidden=!v;$(id).classList.toggle('экран--виден',v);}window.scrollTo(0,0);lastTick=lastAction=performance.now();}
 function pause(value){if(value){view.cancelPointer?.();view.swipeStart=null;}paused=value;$('resume').hidden=!paused||!playing;$('playfield').inert=paused||presenting;$('playfield').setAttribute('aria-hidden',String(paused));$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Продолжить':'Пауза');lastTick=lastAction=performance.now();}
 function start(fresh=false){view.cancelPointer?.();if(fresh||!state||state.won||state.lost){submitScore();state=G.create(mode,crypto.getRandomValues(new Uint32Array(1))[0]);history=[];}mode=state.mode;if(!ticket&&!state.won&&!state.lost)takeTicket();G.resume?.(state);view={};screens(true);pause(false);render();save();message((typeof G.startMessage==='function'?G.startMessage(state):G.startMessage)||'Выберите действие. Правила — под знаком «?».');if(state.won||state.lost)end();}
 function back(){if($('dialog').open){close();return;}if(playing){submitScore();save();screens(false);lobby();}else location.href='index.html';}
 function launch(){if(state&&!state.won&&!state.lost){const body=modal('Начать новую партию?');text(body,'Текущая партия будет заменена. Личные рекорды сохранятся.');button(body,'Начать новую',()=>{close();start(true);});button(body,'Продолжить текущую',()=>{close();start();},'secondary');}else start(true);}
 const playLabel=$('play').innerHTML;
 async function warmup(){if(!window.CasualStudio?.prepare)return;const play=$('play'),resume=$('continue');play.disabled=resume.disabled=true;play.setAttribute('aria-busy','true');play.textContent='Готовим стол…';try{await CasualStudio.prepare(G.id);play.innerHTML=playLabel;play.onclick=launch;resume.disabled=false;}catch{play.textContent='Повторить загрузку стола';play.onclick=warmup;}finally{play.disabled=false;play.removeAttribute('aria-busy');}}
 $('play').onclick=launch;$('continue').onclick=()=>start();$('back').onclick=e=>{e.preventDefault();back();};$('collection').onclick=back;$('new').onclick=launch;$('pause').onclick=()=>pause(!paused);$('resume').onclick=()=>pause(false);$('close-dialog').onclick=close;
 function undoLast(){if(!G.undo||!playing||presenting||paused||!active||document.hidden||$('dialog').open||state.won||!history.length)return;const seconds=state.seconds,aids=state.aids;view.cancelPointer?.();state=history.pop();state.seconds=seconds;state.aids=Math.max(state.aids,aids);view={};save();render();message('Последний ход отменён');}
 $('undo').onclick=undoLast;
 $('help').onclick=()=>{const body=modal('Как играть: '+G.title);G.help.forEach(p=>text(body,p));text(body,'Партия и рекорды сохраняются на этом устройстве. Время на паузе и в свёрнутом приложении не считается.');button(body,'Понятно',close);};
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;lobby();});
 document.addEventListener('keydown',e=>{if(!canPlay())return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$('undo').click();return;}if(typeof G.handleKey==='function'&&!e.ctrlKey&&!e.metaKey&&!e.altKey){const action=G.handleKey(state,e.key);if(action){e.preventDefault();send(action);}}});
 setInterval(()=>{const now=performance.now(),delta=(now-lastTick)/1000;lastTick=now;if(!canPlay())return;if(delta<2)state.seconds+=delta;$('timer').textContent=time(state.seconds);if(G.interval&&now-lastAction>=G.interval(state)){lastAction=now;send({type:'tick'});}else if(Math.floor(state.seconds)%3===0)save();},100);
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){pause(true);save();}});window.addEventListener('pagehide',save);
 let bound=null;function telegram(){window.Телеграм?.показатьСтрелку(back);window.Телеграм?.цветОкна('#0c1919');const tg=window.Telegram?.WebApp;if(tg&&bound!==tg){bound=tg;tg.onEvent?.('deactivated',()=>{active=false;if(playing)pause(true);save();});tg.onEvent?.('activated',()=>{active=true;lastTick=lastAction=performance.now();});}}telegram();window.addEventListener('load',telegram);lobby();warmup();
})();
