'use strict';
(function(r,f){if(typeof module==='object'&&module.exports)module.exports=f(require('./match3-engine'));else r.CasualGame=f(r.Match3Engine);})(globalThis,E=>{
 const {modes,create,resume,act,validate,matches,swaps,adjacent,names,specialNames}=E;
 const symbols=['◆','●','✦','▲','⬟','■'];
 function decorate(cell,s,i){cell.querySelectorAll('.bonus-mark,.ice-layer').forEach(e=>e.remove());cell.dataset.special=s.special?.[i]||0;cell.dataset.ice=s.ice?.[i]||0;if(s.special?.[i]){const mark=document.createElement('span');mark.className='bonus-mark bonus-'+s.special[i];mark.textContent=['','↔','↕','✹','✦'][s.special[i]];mark.setAttribute('aria-hidden','true');cell.append(mark);}if(s.ice?.[i]){const ice=document.createElement('span');ice.className='ice-layer ice-'+s.ice[i];ice.setAttribute('aria-hidden','true');ice.textContent=s.ice[i]===2?'❄':'◇';cell.append(ice);}}
 function drawGoals(s,board){const panel=document.createElement('section');panel.className='collection-goals';panel.setAttribute('aria-label','Цели уровня');for(const g of E.objectives(s)){const item=document.createElement('div');item.className='collection-goal'+(g.current>=g.target?' complete':'');const icon=document.createElement('span');icon.className=g.type==='color'?'goal-gem gem gem-'+g.color:'goal-icon';icon.textContent=g.type==='ice'?'❄':g.type==='score'?'✦':'';const text=document.createElement('span');text.innerHTML=`<small>${g.type==='color'?names[g.color]:g.type==='ice'?'Слои льда':'Очки'}</small><b>${Math.min(g.current,g.target)} / ${g.target} ${g.current>=g.target?'✓':''}</b>`;item.append(icon,text);panel.append(item);}board.append(panel);}
 async function animate(before,after,board){const grid=board.querySelector('.jewel-grid');if(!grid)return;const wait=ms=>new Promise(r=>setTimeout(r,ms));const paint=frame=>{[...grid.children].forEach((cell,i)=>{cell.firstElementChild.className='gem gem-'+frame.grid[i];decorate(cell,frame,i);});};for(const frame of after.frames||[]){if(frame.kind==='swap'){const a=grid.children[frame.a],b=grid.children[frame.b],ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();await Promise.all([[a,br.x-ar.x,br.y-ar.y],[b,ar.x-br.x,ar.y-br.y]].map(([cell,x,y])=>cell.animate([{translate:'0 0'},{translate:`${x}px ${y}px`}],{duration:170,easing:'ease-in-out'}).finished));paint(frame);}else if(frame.kind==='clear'){paint(frame);for(const i of frame.hit){const cell=grid.children[i];cell.firstElementChild.style.animationDelay='0ms';if(frame.removed.includes(i))cell.firstElementChild.classList.add('is-clearing');if(frame.ice[i])cell.querySelector('.ice-layer')?.classList.add('ice-crack');if(frame.activated.includes(i))cell.classList.add('bonus-firing');}const rects=frame.hit.map(i=>grid.children[i].getBoundingClientRect());if(window.CasualStudio&&rects.length){CasualStudio.sound('gem');const label=frame.born.length?specialNames[frame.born[0].type]:'+'+frame.removed.length*50*frame.cascade+(frame.cascade>1?' · ×'+frame.cascade:'');CasualStudio.burst(rects.reduce((n,r)=>n+r.x+r.width/2,0)/rects.length,rects.reduce((n,r)=>n+r.y+r.height/2,0)/rects.length,label);}await wait(frame.activated.length?400:280);grid.querySelectorAll('.bonus-firing').forEach(e=>e.classList.remove('bonus-firing'));}else{paint(frame);const h=grid.children[8].getBoundingClientRect().y-grid.children[0].getBoundingClientRect().y;await Promise.all([...grid.children].map((cell,i)=>{const offset=frame.offsets?.[i]??-1;if(!offset)return Promise.resolve();return Promise.all([cell.firstElementChild,cell.querySelector('.bonus-mark')].filter(Boolean).map(el=>el.animate([{translate:`0 ${offset*h}px`,opacity:.3},{translate:'0 0',opacity:1}],{duration:280,easing:'cubic-bezier(.25,.5,.5,1)'}).finished));}));}}}
 function draw(s,api){api.board.className='game-board match-board';drawGoals(s,api.board);const grid=document.createElement('div');grid.className='square-grid jewel-grid';const animate=false;api.view.lastMove=s.moves;for(let i=0;i<64;i++){const b=api.cell('',()=>{if(performance.now()<(api.view.suppressUntil||0))return;const selected=api.view.selected;if(selected===i){api.view.selected=null;api.redraw();return;}if(selected!=null&&adjacent(selected,i)){api.view.selected=null;api.view.hint=null;if(!api.send({type:'swap',a:selected,b:i})){api.message('Нужен ряд из трёх одинаковых камней. Ход не потрачен.');api.redraw();}else api.message(`Каскадов: ${s.cascade}${s.reshuffled?' · Поле обновлено: прежних ходов не осталось.':''}`);return;}api.view.selected=i;api.redraw();});b.className='jewel-cell'+(api.view.selected===i?' selected-item':'')+(api.view.hint?.includes(i)?' hint-cell':'');b.dataset.cell=i;b.setAttribute('aria-label',(specialNames[s.special?.[i]]||names[s.grid[i]])+(s.ice?.[i]?' · лёд '+s.ice[i]:'')+`, строка ${Math.floor(i/8)+1}, столбец ${i%8+1}`);const gem=document.createElement('span');gem.className='gem gem-'+s.grid[i]+(animate&&s.changed?.includes(i)?' gem-fall':'');gem.textContent=symbols[s.grid[i]];gem.style.animationDelay=Math.floor(i/8)*25+'ms';b.append(gem);decorate(b,s,i);grid.append(b);}api.board.append(grid);let down=null;grid.onpointerdown=e=>{const b=e.target.closest('[data-cell]');if(e.button===0&&b)down={i:Number(b.dataset.cell),x:e.clientX,y:e.clientY};};grid.onpointerup=e=>{if(!down)return;const d=down;down=null;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.max(Math.abs(dx),Math.abs(dy))<16)return;const b=d.i+(Math.abs(dx)>Math.abs(dy)?dx>0?1:-1:dy>0?8:-8);api.view.suppressUntil=performance.now()+400;api.view.selected=null;if(!api.send({type:'swap',a:d.i,b})){api.redraw();api.message('Нужен ряд из трёх. Ход не потрачен.');}};grid.onpointercancel=()=>down=null;api.view.cancelPointer=()=>down=null;api.tool('✦ Подсказка',()=>{const a=swaps(s)[0];if(a){api.aid();api.view.hint=[a.a,a.b];api.redraw();api.message('Поменяйте местами два выделенных камня.');}});}

 return {...E,scripts:['match3-levels','match3-engine'],afterScripts:['match3-campaign'],styles:['игры/match3/style-match3.css'],lobbyModes:E.classics,id:'match3',key:'три-в-ряд',title:'Три в ряд',tag:'ЮВЕЛИРНАЯ КОЛЛЕКЦИЯ',subtitle:'Камни с характером.\nУровни с историей.',draw,animate,undo:true,record:'score',
 startMessage:'Собирайте цели над полем. Четыре в ряд — молния, пять — радуга. Бонусы можно соединять.',
 lossText:'Ходы закончились. Можно отменить последний ход или пройти уровень ещё раз.',
 help:['Меняйте соседние камни местами. Обычный обмен должен собрать три одинаковых камня. Ошибочный обмен не расходует ход.',
 'Четыре в горизонтальном ряду создают горизонтальную молнию, в вертикальном — вертикальную. Молния очищает всю свою линию, когда участвует в совпадении или попадает под другой бонус.',
 'Пять и более в ряд создают радугу. Поменяйте её с любым камнем: исчезнут все камни его цвета. Если радуга попала под взрыв, она соберёт цвет своего исходного камня.',
 'Совпадение Т или Г создаёт взрыв: он очищает квадрат 3 × 3. Бонус остаётся в одной из клеток совпадения и падает вместе с камнями.',
 'Два бонуса можно поменять местами без совпадения: сработают оба. Два взрыва очищают области 5 × 5. Радуга с бонусом превращает выбранный цвет в такие бонусы и запускает их. Две радуги очищают всё поле.',
 'Лёд остаётся на клетках, пока камни движутся. Совпадение или бонус снимает один слой за волну. Прочный лёд требует двух попаданий. Цель со снежинкой считает слои, а не клетки.',
 'Выполните ВСЕ цели до конца ходов. Камень, превратившийся в бонус, засчитается в коллекцию только после сбора. Каскады не тратят дополнительные ходы. Если ходов на поле нет, оно перемешивается бесплатно, лёд и бонусы сохраняются.',
 'Уровни доступны в любом порядке. За завершение — одна звезда, за остаток не менее 15% ходов — две, не менее 30% — три. Звёзды и партия сохраняются на этом устройстве. Подсказки не мешают проходить уровни, но отключают личный рекорд очков.']};
});
