(function(){'use strict';
const R=window.Bastion,$=id=>document.getElementById(id),KEY='bastion_save_v1',PROFILE='bastion_profile_v1',LEASE='bastion_owner_v1';
const session=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);let storageOK=true;
function read(key){try{return localStorage.getItem(key);}catch(_){storageOK=false;return null;}}
function write(key,value){try{localStorage.setItem(key,value);return true;}catch(_){storageOK=false;storageWarning();return false;}}
function storageWarning(){if(storageOK)return;$('storage-warning').hidden=false;$('storage-warning').textContent='Браузер не разрешил сохранение. Можно играть, но после закрытия эта партия и результаты могут потеряться.';}
let profile=R.profile(read(PROFILE)),state=R.restore(read(KEY)),selectedMap=R.unlocked(profile),difficulty='normal',selected=-1,playing=false,paused=false,speed=1,aim=false,ready=false,noticeTimer=0,dialogWasPaused=false,dialogMode='',leaseLost=false,resultDelay=0;
const compact=()=>matchMedia('(max-width:999px) and (orientation:portrait), (max-height:600px) and (max-width:1000px)').matches;
function closeBuild(){if($('build-dialog').open)$('build-dialog').close();renderPanel();refresh();}
const field=new window.BastionField($('field'));field.motion=profile.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches;
function persistProfile(){write(PROFILE,JSON.stringify(profile));}
function acquire(){write(LEASE,session);leaseLost=false;}
function save(){if(state&&(!storageOK||read(LEASE)===session))write(KEY,R.snapshot(state));}
function notify(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,3300);}
function sound(kind,tower){if(profile.sound)audioScene.play(kind,tower);}

let guideHidden=read('bastion_guide_hidden')==='1';
function track(event,data={}){try{const items=JSON.parse(read('bastion_events_v1')||'[]');items.push({event,at:Date.now(),run:state?.runId||session,map:state?.map,...data});write('bastion_events_v1',JSON.stringify(items.slice(-300)));}catch(_){}}
const audioScene=new BastionSound();field.onImpact=tower=>sound('impact',tower);
const asset=k=>'img/бастион/'+k+'-v1.webp';
const timeLabel=t=>Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');
function totalStars(){return R.MAPS.reduce((n,m)=>n+R.mapStars(profile,m.id),0);}
function renderRoute(){const unlock=R.unlocked(profile),start=Math.floor(selectedMap/4)*4;$('island-route').innerHTML=R.MAPS.slice(start,start+4).map(m=>'<button class="island-node '+(m.id===selectedMap?'current':'')+'" data-island="'+m.id+'" aria-label="'+m.name+'" '+(m.id>unlock?'disabled':'')+'>'+(m.id+1)+'</button>').join('');$('island-route').querySelectorAll('[data-island]').forEach(b=>b.onclick=()=>{selectedMap=+b.dataset.island;renderLobby();});}
function renderLobby(){renderRoute();selectedMap=Math.min(selectedMap,R.unlocked(profile));const m=R.MAPS[selectedMap];$('region').textContent=m.region.toUpperCase()+' · ОСТРОВ '+(m.id+1);$('mission-name').textContent=m.name;$('mission-tip').textContent=m.tip;$('total-stars').textContent='★ '+totalStars()+' / 36';$('continue').hidden=!state||['won','lost'].includes(state.phase);if(state)$('continue').textContent='Продолжить · '+R.MAPS[state.map].name+' · волна '+state.wave;$('player-name').textContent=window.Телеграм?.имяИгрока?.()||'Хранитель маяка';document.querySelectorAll('[data-difficulty]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.difficulty===difficulty));}
function showLobby(){resultDelay=0;if($('build-dialog').open)$('build-dialog').close();save();playing=false;paused=true;audioScene.setActive(false);aim=false;field.aim=false;$('game').hidden=true;$('lobby').hidden=false;document.body.classList.remove('in-battle');renderLobby();window.scrollTo(0,0);}
function padButtons(){const holder=$('pads');holder.replaceChildren();R.pads(state.map).forEach((p,i)=>{const b=document.createElement('button');b.className='pad';const screen=field.screenPoint(p);b.style.setProperty('--x',screen.x*100);b.style.setProperty('--y',screen.y*100);b.dataset.pad=i;b.setAttribute('aria-label','Площадка '+(i+1)+': построить башню');b.onclick=()=>{if(paused)return;selected=i;field.selected=i;aim=false;field.aim=false;$('field-wrap').classList.remove('aiming');if(compact())$('build-dialog').showModal();renderPanel();refresh();};holder.append(b);});}
let mapRequest=0;
async function prepareScene(){const request=++mapRequest,map=state.map;ready=false;$('loading').hidden=false;$('loading').textContent='Подготавливаем остров…';refresh();const loaded=await assetLoad;if(!loaded){$('loading').hidden=false;$('loading').innerHTML='<p class="asset-error">Не удалось загрузить изображения острова.</p><button id="retry-assets" class="primary">Повторить загрузку</button>';$('retry-assets').onclick=()=>location.reload();return;}const ok=await field.ensureMap(map);if(request!==mapRequest||state.map!==map)return;ready=ok;$('loading').hidden=ok;if(!ok){$('loading').innerHTML='<p class="asset-error">Остров не загрузился. Партия сохранена.</p><button id="retry-scene" class="primary">Повторить загрузку</button>';$('retry-scene').onclick=prepareScene;}refresh();}
function enter(resume=false){if(resume)track('td_resume',{wave:state.wave});resultDelay=0;playing=true;paused=resume;speed=1;selected=-1;field.selected=-1;field.effects=[];field.seenCombos=new Set();field.map=-1;aim=false;field.aim=false;acquire();$('lobby').hidden=true;$('game').hidden=false;document.body.classList.add('in-battle');$('battle-title').textContent=R.MAPS[state.map].name;$('battle-region').textContent=R.MAPS[state.map].region.toUpperCase()+' · '+R.DIFFICULTIES[state.difficulty].name;$('field-wrap').classList.remove('aiming');document.querySelector('.field-column').style.setProperty('--island-scene','url("'+new URL(BastionField.scene(state.map),document.baseURI).href+'")');prepareScene();padButtons();renderPanel();refresh();save();window.scrollTo(0,0);}
function startNew(draft=null){closeDialog(false);state=R.create(selectedMap,difficulty,R.unlocked(profile)>0?profile.preparation:'none');state.runId=session+'-'+Date.now().toString(36);if(Array.isArray(draft)){for(const t of draft)R.build(state,t.pad,t.type);state.events=[];}track('td_run_start',{draft:Array.isArray(draft)});enter();notify('Защитите маяк. Сначала постройте башни, затем запустите волну.');}
function requestNew(){if(state&&['build','wave'].includes(state.phase)){openDialog('Новая оборона','<p>Текущая партия на острове «'+R.MAPS[state.map].name+'» будет заменена. Результаты пройденных островов сохранятся.</p><button id="confirm-new" class="primary">Начать заново</button><button id="keep-run" class="secondary">Вернуться к текущей партии</button>','confirm');$('confirm-new').onclick=startNew;$('keep-run').onclick=()=>{closeDialog(false);enter(true);};}else startNew();}
function refresh(){document.body.classList.toggle('reduced-motion',!field.motion);audioScene.setActive(playing&&!paused&&profile.sound&&!document.hidden);if(!state||!playing)return;$('health').textContent=state.hp+' / '+state.maxHp;$('gold').textContent=state.gold;$('wave').textContent=state.wave+' / 8';$('speed').textContent='×'+speed;$('speed').setAttribute('aria-label','Скорость ×'+speed+'. Нажмите для переключения.');$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Продолжить':'Пауза');$('pause-cover').hidden=!paused||$('dialog').open;$('pads').inert=paused||!ready;R.pads(state.map).forEach((p,i)=>{const b=$('pads').children[i],screen=field.screenPoint(p);if(b){b.style.setProperty('--x',screen.x*100);b.style.setProperty('--y',screen.y*100);}});
 const inWave=state.phase==='wave',finished=['won','lost'].includes(state.phase);$('launch').disabled=inWave||paused||!ready||finished||state.towers.length===0;$('launch').textContent=inWave?'Волна '+state.wave+' · осталось '+(state.queue.length+state.enemies.filter(e=>e.hp>0).length):finished?'Оборона завершена':'Начать волну '+(state.wave+1)+' →';$('phase-text').textContent=paused?'Пауза':inWave?'Противники идут к маяку':finished?'Оборона завершена':state.wave?'Волна отражена · подготовьте оборону':'Подготовка обороны';
 const coaching=!guideHidden&&(state.wave<2||aim);$('coach').hidden=!coaching;document.querySelectorAll('.pad').forEach(b=>b.classList.toggle('guide',coaching&&state.towers.length===0&&+b.dataset.pad===1));
 $('wave-brief').classList.toggle('during-wave',inWave);$('wave-brief').innerHTML='<b class="brief-title">'+R.briefing(state).name+'</b><span>'+R.briefing(state).tip+'</span>';
 $('tutorial').textContent=aim?'Нажмите на врага или участок дороги, куда направить удар. Повторное нажатие на «Удар маяка» отменит выбор.':leaseLost?'Партия открыта в другой вкладке. Нажмите «Продолжить», чтобы играть здесь.':state.wave===0&&!state.towers.length?'Нажмите на площадку с «+» и выберите башню. До первой волны продажа возвращает всё золото.':state.wave===0?'Сочетайте баллисту с мортирой и приливом. Когда будете готовы — начните волну.':inWave?'Нажмите на башню, чтобы улучшить её. Удар маяка поражает область; прилив замедляет всех.':'Есть время усилить оборону. Посмотрите состав следующей волны перед запуском.';
 for(const kind of ['meteor','tide']){$(kind).disabled=!inWave||paused||!ready||state.cooldowns[kind]>0;$(kind+'-status').textContent=state.cooldowns[kind]>0?Math.ceil(state.cooldowns[kind])+' с':kind==='meteor'?(aim?'Нажмите на поле':'Выберите цель'):'Замедлить всех';}$('meteor').classList.toggle('selected',aim);$('deselect').hidden=selected<0&&!aim;
 document.querySelectorAll('[data-cost]').forEach(b=>{b.disabled=paused||finished||state.gold<Number(b.dataset.cost);const missing=Number(b.dataset.cost)-state.gold;let label=b.querySelector('.shortfall');if(missing>0){if(!label){label=document.createElement('small');label.className='shortfall';b.append(label);}label.textContent='Нужно ещё '+missing+' золота';}else label?.remove();});document.querySelectorAll('[data-sell]').forEach(b=>b.disabled=paused||finished);
 const counts=inWave?state.queue.concat(state.enemies.filter(e=>e.hp>0).map(e=>e.type)).reduce((a,k)=>(a[k]=(a[k]||0)+1,a),{}):finished?{}:R.preview(state);const signature=JSON.stringify(counts);if($('preview').dataset.signature!==signature){$('preview').dataset.signature=signature;$('preview').innerHTML=Object.entries(counts).map(([k,n])=>'<button class="enemy-chip" data-enemy-info="'+k+'" aria-label="'+R.ENEMIES[k].name+': '+n+'. Подробнее"><img src="img/бастион/'+k+'-portrait-v5.webp" alt=""><span class="enemy-name">'+R.ENEMIES[k].name+'</span><b>×'+n+'</b></button>').join('')||'<span class="enemy-chip">Маяк защищён</span>';$('preview').querySelectorAll('[data-enemy-info]').forEach(b=>b.onclick=()=>enemyInfo(b.dataset.enemyInfo));}$('preview-label').textContent=inWave?'В ЭТОЙ ВОЛНЕ':'СЛЕДУЮЩАЯ ВОЛНА';
 for(const b of $('pads').children){const t=state.towers.find(t=>t.pad===+b.dataset.pad);b.setAttribute('aria-label',t?R.TOWERS[t.type].name+', уровень '+t.level+'. Площадка '+(+b.dataset.pad+1):'Площадка '+(+b.dataset.pad+1)+': построить башню');b.setAttribute('aria-pressed',+b.dataset.pad===selected);}
}
function processEvents(){for(const e of state.events){field.event(e);if(['build','wave','won','lost'].includes(e.type)){sound(e.type);const tower=e.type==='build'?state.towers.find(t=>t.pad===e.pad):null;track('td_'+(tower?.level>1?'upgrade':e.type),{wave:state.wave,gold:state.gold,hp:state.hp,difficulty:state.difficulty,...(tower?{tower:tower.type,level:tower.level,branch:tower.branch}:{}),...(['won','lost'].includes(e.type)?{seconds:state.time,stars:R.stars(state),leaks:state.metrics?.leaks||{}}:{})});}else if(e.type==='shot')sound('shot',e.tower);if(e.type==='combo'&&!field.seenCombos?.has(e.kind)){field.seenCombos||=new Set();field.seenCombos.add(e.kind);notify(e.kind==='water'?'Вода + молния: урон усилен на 50%':'Осадный удар: броня снята на 4 секунды');}if(e.type==='boss-shield')notify('Щит адмирала · 3 секунды. Дождитесь спада для удара маяка.');if(e.type==='clear'){track('td_wave_clear',{wave:state.wave,hp:state.hp,gold:state.gold});notify('Волна '+e.wave+' отражена · +'+(25+e.wave*4)+' золота');save();}if(e.type==='won'||e.type==='lost'){if(e.type==='won'){R.record(profile,state);persistProfile();}save();if(e.type==='won'&&field.motion)resultDelay=.65;else result();}}state.events=[];}
function act(fn){if(paused||!ready)return false;const ok=fn();if(!ok){notify('Действие сейчас недоступно');return false;}processEvents();renderPanel();refresh();save();window.Телеграм?.отклик?.('выбор');return true;}
function renderPanel(){if(!state)return;const selectedTower=state.towers.find(t=>t.pad===selected);const compactPanel=$('compact-selection');compactPanel.hidden=!selectedTower;if(selectedTower){const info=R.TOWERS[selectedTower.type];compactPanel.innerHTML='<img src="'+asset(selectedTower.type)+'" alt=""><div><b>'+info.name+'</b><small>Уровень '+['','I','II','III'][selectedTower.level]+' · '+(selectedTower.level<3?'улучшение '+R.upgradeCost(selectedTower)+' ◉':info.branches[selectedTower.branch][0])+'</small></div><button id="open-selected">'+(selectedTower.level<3?'Улучшить ↗':'Подробнее ↗')+'</button>';$('open-selected').onclick=()=>{if(paused)return;$('build-dialog').showModal();renderPanel();refresh();};}const panel=$('build-dialog').open?$('tower-panel-mobile'):$('tower-panel'),t=state.towers.find(t=>t.pad===selected);if(selected<0){panel.innerHTML='<h2>Ваша оборона</h2><p>Выберите площадку на острове. Башни атакуют автоматически — ваша задача найти правильное сочетание.</p><div class="tower-choices">'+R.available(state.map).map(k=>'<button class="tower-choice" data-info="'+k+'"><img src="'+asset(k)+'" alt=""><b>'+R.TOWERS[k].name+'</b><small>'+R.TOWERS[k].cost+' ◉</small></button>').join('')+'</div>';panel.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>towerInfo(b.dataset.info));return;}
 if(!t){panel.innerHTML='<h2>Площадка '+(selected+1)+'</h2><p>Выберите башню · стоимость будет списана сразу</p><div class="tower-choices">'+R.available(state.map).map(k=>'<button class="tower-choice" data-build="'+k+'" data-cost="'+R.TOWERS[k].cost+'"><img src="'+asset(k)+'" alt=""><b>'+R.TOWERS[k].name+'</b><small>'+R.TOWERS[k].cost+' ◉</small></button>').join('')+'</div>';panel.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>{if(act(()=>R.build(state,selected,b.dataset.build)))closeBuild();});return;}
 const d=R.TOWERS[t.type],st=R.stats(t,state),cost=R.upgradeCost(t);panel.innerHTML='<div class="panel-intro"><img src="'+asset(t.type)+'" alt=""><div><span class="eyebrow">УРОВЕНЬ '+['','I','II','III'][t.level]+'</span><h2>'+d.name+'</h2></div></div><p>'+d.tip+'</p><div class="stats"><div><b>'+Math.round(st.damage)+'</b><small>урон</small></div><div><b>'+st.rate.toFixed(1)+' с</b><small>перезарядка</small></div><div><b>'+Math.round(st.range)+'</b><small>дальность</small></div></div>'+(t.level===1?'<button class="upgrade-button" data-upgrade="-1" data-cost="'+cost+'">Улучшить до II · '+cost+' ◉<small>'+(t.type==='signal'?'Радиус поддержки +12':'Урон '+Math.round(st.damage)+' → '+Math.round(R.stats({...t,level:2},state).damage)+' · дальность '+Math.round(st.range)+' → '+Math.round(R.stats({...t,level:2},state).range))+'</small></button>':t.level===2?d.branches.map((b,i)=>'<button class="upgrade-button" data-upgrade="'+i+'" data-cost="'+cost+'">'+b[0]+' · '+cost+' ◉<small>'+b[1]+'</small></button>').join(''):'<p>✦ '+d.branches[t.branch][0]+'<br>'+d.branches[t.branch][1]+'</p>')+'<button class="sell-button" data-sell>Продать · вернуть '+R.sellValue(state,t)+' ◉</button>';
 if(t.type!=='signal'){panel.insertAdjacentHTML('beforeend','<fieldset class="priority-control"><legend>Выбор цели</legend>'+[['first','Первый'],['strong','Сильный'],['armor','Броня']].map(([k,n])=>'<button data-priority="'+k+'" aria-pressed="'+((t.priority||'first')===k)+'">'+n+'</button>').join('')+'</fieldset>');panel.querySelectorAll('[data-priority]').forEach(b=>b.onclick=()=>{if(R.priority(state,t.pad,b.dataset.priority)){track('td_priority',{priority:b.dataset.priority});renderPanel();save();}});}
 panel.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{if(act(()=>R.upgrade(state,selected,+b.dataset.upgrade<0?null:+b.dataset.upgrade))){closeBuild();}});panel.querySelector('[data-sell]').onclick=()=>{const pad=selected;closeBuild();openDialog('Продать башню?','<p>'+d.name+' освободит площадку. Вы получите '+R.sellValue(state,t)+' золота.</p><button id="confirm-sell" class="primary">Продать</button>','sell');$('confirm-sell').onclick=()=>{closeDialog();act(()=>R.sell(state,pad));};};
}
function pause(value){if(!value&&leaseLost){const latest=R.restore(read(KEY));if(latest){state=latest;enter(true);if(['won','lost'].includes(state.phase)){result();return;}}}if($('build-dialog').open)$('build-dialog').close();paused=value;aim=false;field.aim=false;$('field-wrap').classList.remove('aiming');if(!paused){acquire();sound('tap');}else save();refresh();}
function openDialog(title,content,mode='help'){if($('build-dialog').open)$('build-dialog').close();dialogWasPaused=paused;if(playing)paused=true;dialogMode=mode;$('dialog').dataset.mode=mode;$('dialog-content').innerHTML='<h2 id="dialog-title">'+title+'</h2>'+content;if(!$('dialog').open)$('dialog').showModal();refresh();}
function closeDialog(resume=true){if(!$('dialog').open)return;const wasResult=dialogMode==='result';$('dialog').close();if(wasResult&&resume){dialogMode='';selectedMap=R.unlocked(profile);showLobby();return;}if(resume)paused=dialogMode==='result'?true:dialogWasPaused;dialogMode='';refresh();}
function help(){openDialog('Как защитить маяк','<ol><li>Нажмите «+» на острове и постройте башню. До первой волны можно продать её за полную стоимость.</li><li>Посмотрите состав волны и нажмите «Начать волну». Башни стреляют сами.</li><li>Нажмите на построенную башню для улучшения. После II уровня выберите одну из двух специализаций.</li><li>Баллиста ловит быстрых, мортира разбивает группы, прилив замедляет. Мокрые враги получают усиленный урон молнией.</li><li>«Удар маяка» затем касание поля — урон по области. «Прилив» — замедление всех врагов. Способности бесплатны и перезаряжаются во время боя.</li><li>Переживите 8 волн. Победа даёт 1 звезду; 75% здоровья — 2; целый маяк — 3. Следующий остров открывается после любой победы.</li></ol><p>Сохранение и результаты хранятся на этом устройстве. При сворачивании бой останавливается. Онлайн-кооператив в этой версии отсутствует.</p>');}
function maps(){const unlock=R.unlocked(profile);openDialog('Острова архипелага','<p>12 островов · 3 региона · '+totalStars()+' из 36 звёзд</p>'+[0,4,8].map(start=>'<h3 class="region-heading">'+R.MAPS[start].region+'</h3><div class="region-route">'+R.MAPS.slice(start,start+4).map(m=>'<button class="map-card '+(m.id===selectedMap?'selected':'')+'" data-map="'+m.id+'" '+(m.id>unlock?'disabled':'')+'><img src="img/бастион/island-'+String(m.id+1).padStart(2,'0')+'-thumb-v6.webp" alt="" decoding="async"><b>'+String(m.id+1).padStart(2,'0')+'</b><span>'+m.name+'</span><small>'+(m.id>unlock?'Сначала остров '+m.id:'★'.repeat(R.mapStars(profile,m.id))+'☆'.repeat(3-R.mapStars(profile,m.id)))+'</small></button>').join('')+'</div>').join(''),'maps');document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{selectedMap=+b.dataset.map;track('td_map_select',{map:selectedMap});closeDialog();renderLobby();});}
function enemyInfo(k){const desc={raider:'Обычный налётчик без брони. Опасен большой группой; мортира поражает несколько целей.',runner:'Быстрый разведчик без брони. Баллиста и замедление помогают остановить его на повороте.',crab:'Броня поглощает 50% обычного урона. Пробитие тяжёлой баллисты, огонь и осадный удар обходят защиту.',shield:'Броня поглощает 30% обычного урона. Потеря маяка при прорыве — 2 здоровья.',healer:'Каждые 2 секунды восстанавливает 4,5% здоровья ближайших союзников. Удар по области поражает его вместе с группой.',boss:'Прорыв отнимает 8 здоровья. Адмирал останавливается и поднимает молот. Золотое кольцо предупреждает о щите: 3 секунды он поглощает половину урона. Дождитесь спада перед ударом маяка.'};openDialog(R.ENEMIES[k].name,'<img class="enemy-detail" src="img/бастион/'+k+'-portrait-v5.webp" alt=""><p>'+desc[k]+'</p>','enemy');}
function towerInfo(k){const d=R.TOWERS[k],unlocked=R.unlocked(profile)>=d.unlock;openDialog(d.name,'<img class="tower-detail-hero" src="'+asset(k)+'" alt="'+d.name+'"><p>'+d.tip+'</p><p>Постройка: '+d.cost+' золота. '+(unlocked?'Доступна на островах начиная с №'+(d.unlock+1)+'.':'Откроется на острове №'+(d.unlock+1)+'.')+'</p><div class="branches">'+d.branches.map(b=>'<article><h3>'+b[0]+'</h3><p>'+b[1]+'</p></article>').join('')+'</div><p>Специализация выбирается в бою после улучшения башни до II уровня. При смене острова оборона строится заново.</p>','tower');}
function arsenal(chosen='mortar'){
 const unlocked=R.unlocked(profile),d=R.TOWERS[chosen];
 openDialog('Мастерская','<p class="workshop-subtitle">Выберите свой стиль обороны</p><span class="workshop-mode">Башни и специализации · покупаются за золото внутри боя</span><div class="workshop-hero '+chosen+'"><img src="'+asset(chosen)+'" alt="'+d.name+'"></div><div class="workshop-title">'+d.name+'</div><p class="workshop-description">'+d.tip+'</p><div class="arsenal-grid">'+Object.entries(R.TOWERS).map(([k,t])=>'<button class="arsenal-card" data-tower="'+k+'" aria-pressed="'+(chosen===k)+'"><img src="'+asset(k)+'" alt=""><b>'+t.name+'</b></button>').join('')+'</div><div class="branches">'+d.branches.map((b,i)=>'<article><img src="img/бастион/'+(chosen==='mortar'?(i?'branch-cluster-v3':'branch-siege-v3'):chosen+'-branch-'+i+'-v5')+'.webp" alt=""><h3>'+b[0]+'</h3><p>'+b[1]+'</p></article>').join('')+'</div><p class="workshop-footnote">'+(d.unlock<=unlocked?'Специализации доступны в бою после II уровня':'Откроется на острове '+(d.unlock+1))+'</p><div class="workshop-preparation"><h3>Подготовка к следующему бою</h3><div class="preparation">'+[['none','Чистая тактика','Без преимущества'],['hull','Прочность маяка','24 здоровья'],['supply','Запас припасов','+40 золота'],['optics','Морская оптика','Дальность +10%']].map(([k,n,t])=>'<button data-preparation="'+k+'" aria-pressed="'+(profile.preparation===k)+'" '+(!unlocked&&k!=='none'?'disabled':'')+'>'+n+'<small>'+t+'</small></button>').join('')+'</div><p class="workshop-footnote">'+(unlocked?'Выбор бесплатный · действует со следующей партии':'Откроется после первой победы')+'</p></div>','arsenal');
 $('dialog').dataset.preview=chosen;
 document.querySelectorAll('[data-tower]').forEach(b=>b.onclick=()=>arsenal(b.dataset.tower));
 document.querySelectorAll('[data-preparation]').forEach(b=>b.onclick=()=>{profile.preparation=b.dataset.preparation;persistProfile();document.querySelectorAll('[data-preparation]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.preparation===profile.preparation));notify('Подготовка выбрана для следующей партии');});
}
function records(){const list=Object.entries(profile.records).sort(([a],[b])=>+a.split(':')[0]-+b.split(':')[0]);openDialog('Мои результаты',list.length?'<p>Лучший результат каждого острова и сложности. При равных звёздах сохраняется меньшее время боя.</p>'+list.map(([k,r])=>{const [map,diff]=k.split(':');return '<div class="record-row"><span>'+R.MAPS[+map].name+'<br><small>'+R.DIFFICULTIES[diff].name+'</small></span><span>'+'★'.repeat(r.stars)+' · '+timeLabel(r.time)+'</span></div>';}).join(''):'<p>Здесь появятся результаты завершённых победой оборон. Начните с Тихой гавани.</p>','records');}
function settings(){openDialog('Настройки','<label class="settings-row">Звуки боя<input id="sound-setting" type="checkbox" '+(profile.sound?'checked':'')+'></label><label class="settings-row">Эффекты и движение<input id="motion-setting" type="checkbox" '+(profile.motion?'checked':'')+'></label><p>Настройки сохраняются на этом устройстве. Отключение эффектов не меняет правила и результат боя.</p>','settings');$('sound-setting').onchange=e=>{profile.sound=e.target.checked;audioScene.setActive(profile.sound&&playing&&!paused);persistProfile();if(profile.sound)sound('build');};$('motion-setting').onchange=e=>{profile.motion=e.target.checked;field.motion=profile.motion;field.effects=[];persistProfile();};}
function battleReason(){const m=state.metrics;if(!m)return 'Для этой сохранённой партии подробности прорывов не записаны.';const leaks=Object.entries(m.leaks).sort((a,b)=>b[1]*R.ENEMIES[b[0]].leak-a[1]*R.ENEMIES[a[0]].leak);if(!leaks.length)return 'Ни один противник не добрался до маяка.';const [type,count]=leaks[0];return 'Прорвались: '+R.ENEMIES[type].name+' ×'+count+'. '+R.Campaign.advice[type];}
function rewardCard(){if(state.phase!=='won')return '';const next=Object.entries(R.TOWERS).find(([,t])=>t.unlock===state.map+1);if(next)return '<div class="unlock-card"><img src="'+asset(next[0])+'" alt=""><div><b>Открыто: '+next[1].name+'</b><small>'+next[1].tip+'</small></div></div>';if(state.map===0)return '<div class="unlock-card"><div><b>Открыта подготовка</b><small>В мастерской можно бесплатно выбрать прочность маяка, припасы или дальность для следующего боя.</small></div></div>';return '';}
function result(){const won=state.phase==='won',st=R.stars(state);openDialog(won?'Маяк защищён':'Оборона прорвана','<div class="result"><div class="stars">'+(won?'★'.repeat(st)+'☆'.repeat(3-st):'◇')+'</div><p>'+R.MAPS[state.map].name+' · '+R.DIFFICULTIES[state.difficulty].name+'</p><div class="result-stats"><div><b>'+state.hp+'/'+state.maxHp+'</b><small>здоровье маяка</small></div><div><b>'+state.kills+'</b><small>врагов остановлено</small></div><div><b>'+timeLabel(state.time)+'</b><small>время боя</small></div></div><p>'+(won?(state.map===11?'Архипелаг защищён. Попробуйте другую сложность или улучшите звёзды.':'Следующий остров открыт. Попробуйте новый маршрут и новые сочетания.'):battleReason())+'</p>'+rewardCard()+(state.draft?.length?'<button id="retry-draft" class="secondary">Повторить с начальной расстановкой</button>':'')+(won&&state.map<11?'<button id="next-island" class="primary">Следующий остров →</button>':'')+'<button id="retry" class="'+(won&&state.map<11?'secondary':'primary')+'">Повторить остров</button><button id="result-lobby" class="secondary">В крепость</button></div>','result');$('next-island')?.addEventListener('click',()=>{selectedMap=state.map+1;difficulty=state.difficulty;startNew();});$('retry-draft')?.addEventListener('click',()=>{const draft=state.draft;selectedMap=state.map;difficulty=state.difficulty;track('td_retry_draft');startNew(draft);});$('retry').onclick=()=>{selectedMap=state.map;difficulty=state.difficulty;startNew();};$('result-lobby').onclick=()=>{closeDialog(false);selectedMap=R.unlocked(profile);showLobby();};}
function back(){if($('build-dialog').open){closeBuild();return;}if($('dialog').open){closeDialog();return;}if(playing){if(['won','lost'].includes(state.phase)){showLobby();return;}pause(true);}else location.href='index.html';}
let telegramEventsBound=false;
function initTelegram(){if(!telegramEventsBound&&window.Telegram?.WebApp?.onEvent){telegramEventsBound=true;window.Telegram.WebApp.onEvent('deactivated',()=>{if(playing)pause(true);});}const t=window.Телеграм;t?.отперетьПоворот?.();t?.цветОкна?.('#092629');if(t?.показатьСтрелку?.(back))$('back').hidden=true;if(t?.кнопкаНастроек?.(settings))$('settings').hidden=true;renderLobby();}
 $('back').onclick=back;$('settings').onclick=settings;$('start').onclick=requestNew;$('continue').onclick=()=>{closeDialog(false);state=R.restore(read(KEY))||state;if(state&&['build','wave'].includes(state.phase))enter(true);else{renderLobby();notify('Сохранённая партия уже завершена');}};
 $('help').onclick=help;$('game-help').onclick=help;$('arsenal').onclick=()=>arsenal();$('campaign').onclick=help;$('records').onclick=records;$('choose-map').onclick=maps;document.querySelectorAll('[data-difficulty]').forEach(b=>b.onclick=()=>{difficulty=b.dataset.difficulty;renderLobby();});
 $('skip-guide').onclick=()=>{guideHidden=true;write('bastion_guide_hidden','1');refresh();};$('pause-settings').onclick=settings;
 $('close-build').onclick=closeBuild;$('build-dialog').addEventListener('cancel',e=>{e.preventDefault();closeBuild();});
 $('close-dialog').onclick=()=>closeDialog();$('dialog').addEventListener('cancel',e=>{e.preventDefault();closeDialog();});$('pause').onclick=()=>pause(!paused);$('resume').onclick=()=>pause(false);$('to-lobby').onclick=showLobby;$('speed').onclick=()=>{speed=speed===1?2:1;refresh();};
 $('launch').onclick=()=>{if(state.wave===0)state.draft=state.towers.map(t=>({pad:t.pad,type:t.type}));act(()=>R.startWave(state));};$('deselect').onclick=()=>{selected=-1;field.selected=-1;aim=false;field.aim=false;$('field-wrap').classList.remove('aiming');renderPanel();refresh();};$('meteor').onclick=()=>{if(paused||!ready||state.phase!=='wave'||state.cooldowns.meteor>0)return;aim=!aim;field.aim=aim;$('field-wrap').classList.toggle('aiming',aim);if(aim)$('field-wrap').scrollIntoView({block:'center',behavior:'smooth'});refresh();};$('tide').onclick=()=>act(()=>R.cast(state,'tide'));
 $('field').addEventListener('click',e=>{if(!aim||paused)return;const box=$('field').getBoundingClientRect(),p=field.worldPoint((e.clientX-box.left)/box.width,(e.clientY-box.top)/box.height);if(act(()=>R.cast(state,'meteor',p))){aim=false;field.aim=false;$('field-wrap').classList.remove('aiming');refresh();}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){pause(true);save();}});window.addEventListener('pagehide',()=>{if(playing)save();});window.addEventListener('storage',e=>{if(e.key===LEASE&&e.newValue!==session&&playing){leaseLost=true;paused=true;refresh();notify('Партия продолжена в другой вкладке');}});
 document.addEventListener('keydown',e=>{if(e.code==='Space'&&playing&&!$('dialog').open&&e.target===document.body){e.preventDefault();pause(!paused);}if(e.key==='Escape'&&aim){aim=false;field.aim=false;$('field-wrap').classList.remove('aiming');refresh();}});
 let last=performance.now(),accumulator=0,uiClock=0,saveClock=0;function frame(now){const dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;if(playing&&state){if(!paused&&ready&&!$('dialog').open&&!$('build-dialog').open&&state.phase==='wave'){accumulator+=dt*speed;while(accumulator>=R.STEP&&state.phase==='wave'&&!paused){R.tick(state,R.STEP);processEvents();accumulator-=R.STEP;}saveClock+=dt;if(saveClock>=2){saveClock=0;save();}}else accumulator=0;field.draw(state,paused?0:dt);if(resultDelay>0&&!paused&&!$('dialog').open){resultDelay-=dt;if(resultDelay<=0&&state.phase==='won')result();}uiClock+=dt;if(uiClock>.12){uiClock=0;refresh();}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
 const assetLoad=field.load();
 assetLoad.then(async ok=>{if(ok){const maps=[selectedMap,...(state?[state.map]:[])];ok=(await Promise.all([...new Set(maps)].map(m=>field.ensureMap(m)))).every(Boolean);}if(playing&&field.loaded)return;ready=ok;$('loading').hidden=ok;if(!ok){$('loading').innerHTML='<p class="asset-error">Не удалось загрузить изображения острова.</p><button id="retry-assets" class="primary">Повторить загрузку</button>';$('retry-assets').onclick=()=>location.reload();}refresh();});
 if(state?.phase==='won'){R.record(profile,state);persistProfile();selectedMap=R.unlocked(profile);}storageWarning();renderLobby();initTelegram();window.addEventListener('load',initTelegram);
 // Диагностика только для чтения: не меняет партию и не обходит покупки.
 window.БастионИгра={состояние:()=>state?JSON.parse(R.snapshot(state)):null,готов:()=>ready,события:()=>{try{return JSON.parse(read('bastion_events_v1')||'[]');}catch(_){return [];}}};
})();
